# coding: utf-8

"""
    The Selling Partner API for Fulfillment Outbound

    The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.

    The version of the OpenAPI document: 2026-07-04
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pprint
import re  # noqa: F401

import six

from spapi.configuration import Configuration


class FulfillmentOrder(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_id': 'str',
        'channel': 'str',
        'receive_time': 'datetime',
        'status': 'str',
        'status_update_time': 'datetime',
        'fulfillment_configuration': 'OrderResponseFulfillmentConfiguration',
        'origin': 'OrderOrigin',
        'destination': 'OrderDestination',
        'line_items': 'List[OrderLineItem]',
        'shipments': 'List[Shipment]',
        'payment_information': 'PaymentInformation',
    }

    attribute_map = {
        'order_id': 'orderId',
        'channel': 'channel',
        'receive_time': 'receiveTime',
        'status': 'status',
        'status_update_time': 'statusUpdateTime',
        'fulfillment_configuration': 'fulfillmentConfiguration',
        'origin': 'origin',
        'destination': 'destination',
        'line_items': 'lineItems',
        'shipments': 'shipments',
        'payment_information': 'paymentInformation',
    }

    def __init__(self, order_id=None, channel=None, receive_time=None, status=None, status_update_time=None, fulfillment_configuration=None, origin=None, destination=None, line_items=None, shipments=None, payment_information=None, _configuration=None):  # noqa: E501
        """FulfillmentOrder - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._order_id = None
        self._channel = None
        self._receive_time = None
        self._status = None
        self._status_update_time = None
        self._fulfillment_configuration = None
        self._origin = None
        self._destination = None
        self._line_items = None
        self._shipments = None
        self._payment_information = None
        self.discriminator = None

        self.order_id = order_id
        if channel is not None:
            self.channel = channel
        self.receive_time = receive_time
        if status is not None:
            self.status = status
        if status_update_time is not None:
            self.status_update_time = status_update_time
        if fulfillment_configuration is not None:
            self.fulfillment_configuration = fulfillment_configuration
        if origin is not None:
            self.origin = origin
        if destination is not None:
            self.destination = destination
        self.line_items = line_items
        if shipments is not None:
            self.shipments = shipments
        if payment_information is not None:
            self.payment_information = payment_information

    @property
    def order_id(self):
        """Gets the order_id of this FulfillmentOrder.  # noqa: E501

        The fulfillment order identifier submitted with the `createOrder` operation.  # noqa: E501

        :return: The order_id of this FulfillmentOrder.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this FulfillmentOrder.

        The fulfillment order identifier submitted with the `createOrder` operation.  # noqa: E501

        :param order_id: The order_id of this FulfillmentOrder.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id

    @property
    def channel(self):
        """Gets the channel of this FulfillmentOrder.  # noqa: E501

        The sales channel for the fulfillment order.  # noqa: E501

        :return: The channel of this FulfillmentOrder.  # noqa: E501
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this FulfillmentOrder.

        The sales channel for the fulfillment order.  # noqa: E501

        :param channel: The channel of this FulfillmentOrder.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                channel is not None and len(channel) > 40):
            raise ValueError("Invalid value for `channel`, length must be less than or equal to `40`")  # noqa: E501

        self._channel = channel

    @property
    def receive_time(self):
        """Gets the receive_time of this FulfillmentOrder.  # noqa: E501

        Date timestamp in [ISO 8601](https://developer-docs.amazon/sp-api/docs/iso-8601) date time format.  # noqa: E501

        :return: The receive_time of this FulfillmentOrder.  # noqa: E501
        :rtype: datetime
        """
        return self._receive_time

    @receive_time.setter
    def receive_time(self, receive_time):
        """Sets the receive_time of this FulfillmentOrder.

        Date timestamp in [ISO 8601](https://developer-docs.amazon/sp-api/docs/iso-8601) date time format.  # noqa: E501

        :param receive_time: The receive_time of this FulfillmentOrder.  # noqa: E501
        :type: datetime
        """
        if self._configuration.client_side_validation and receive_time is None:
            raise ValueError("Invalid value for `receive_time`, must not be `None`")  # noqa: E501

        self._receive_time = receive_time

    @property
    def status(self):
        """Gets the status of this FulfillmentOrder.  # noqa: E501

        The current status of the fulfillment order. Possible values: `PROCESSING`, `COMPLETE`, `COMPLETE_PARTIAL`, `CANCELLED`, `UNFULFILLABLE`, `INVALID`.  # noqa: E501

        :return: The status of this FulfillmentOrder.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this FulfillmentOrder.

        The current status of the fulfillment order. Possible values: `PROCESSING`, `COMPLETE`, `COMPLETE_PARTIAL`, `CANCELLED`, `UNFULFILLABLE`, `INVALID`.  # noqa: E501

        :param status: The status of this FulfillmentOrder.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def status_update_time(self):
        """Gets the status_update_time of this FulfillmentOrder.  # noqa: E501

        Date timestamp in [ISO 8601](https://developer-docs.amazon/sp-api/docs/iso-8601) date time format.  # noqa: E501

        :return: The status_update_time of this FulfillmentOrder.  # noqa: E501
        :rtype: datetime
        """
        return self._status_update_time

    @status_update_time.setter
    def status_update_time(self, status_update_time):
        """Sets the status_update_time of this FulfillmentOrder.

        Date timestamp in [ISO 8601](https://developer-docs.amazon/sp-api/docs/iso-8601) date time format.  # noqa: E501

        :param status_update_time: The status_update_time of this FulfillmentOrder.  # noqa: E501
        :type: datetime
        """

        self._status_update_time = status_update_time

    @property
    def fulfillment_configuration(self):
        """Gets the fulfillment_configuration of this FulfillmentOrder.  # noqa: E501


        :return: The fulfillment_configuration of this FulfillmentOrder.  # noqa: E501
        :rtype: OrderResponseFulfillmentConfiguration
        """
        return self._fulfillment_configuration

    @fulfillment_configuration.setter
    def fulfillment_configuration(self, fulfillment_configuration):
        """Sets the fulfillment_configuration of this FulfillmentOrder.


        :param fulfillment_configuration: The fulfillment_configuration of this FulfillmentOrder.  # noqa: E501
        :type: OrderResponseFulfillmentConfiguration
        """

        self._fulfillment_configuration = fulfillment_configuration

    @property
    def origin(self):
        """Gets the origin of this FulfillmentOrder.  # noqa: E501


        :return: The origin of this FulfillmentOrder.  # noqa: E501
        :rtype: OrderOrigin
        """
        return self._origin

    @origin.setter
    def origin(self, origin):
        """Sets the origin of this FulfillmentOrder.


        :param origin: The origin of this FulfillmentOrder.  # noqa: E501
        :type: OrderOrigin
        """

        self._origin = origin

    @property
    def destination(self):
        """Gets the destination of this FulfillmentOrder.  # noqa: E501


        :return: The destination of this FulfillmentOrder.  # noqa: E501
        :rtype: OrderDestination
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this FulfillmentOrder.


        :param destination: The destination of this FulfillmentOrder.  # noqa: E501
        :type: OrderDestination
        """

        self._destination = destination

    @property
    def line_items(self):
        """Gets the line_items of this FulfillmentOrder.  # noqa: E501

        A list of items in the fulfillment order.  # noqa: E501

        :return: The line_items of this FulfillmentOrder.  # noqa: E501
        :rtype: List[OrderLineItem]
        """
        return self._line_items

    @line_items.setter
    def line_items(self, line_items):
        """Sets the line_items of this FulfillmentOrder.

        A list of items in the fulfillment order.  # noqa: E501

        :param line_items: The line_items of this FulfillmentOrder.  # noqa: E501
        :type: List[OrderLineItem]
        """
        if self._configuration.client_side_validation and line_items is None:
            raise ValueError("Invalid value for `line_items`, must not be `None`")  # noqa: E501

        self._line_items = line_items

    @property
    def shipments(self):
        """Gets the shipments of this FulfillmentOrder.  # noqa: E501

        An array of fulfillment shipment information.  # noqa: E501

        :return: The shipments of this FulfillmentOrder.  # noqa: E501
        :rtype: List[Shipment]
        """
        return self._shipments

    @shipments.setter
    def shipments(self, shipments):
        """Sets the shipments of this FulfillmentOrder.

        An array of fulfillment shipment information.  # noqa: E501

        :param shipments: The shipments of this FulfillmentOrder.  # noqa: E501
        :type: List[Shipment]
        """

        self._shipments = shipments

    @property
    def payment_information(self):
        """Gets the payment_information of this FulfillmentOrder.  # noqa: E501


        :return: The payment_information of this FulfillmentOrder.  # noqa: E501
        :rtype: PaymentInformation
        """
        return self._payment_information

    @payment_information.setter
    def payment_information(self, payment_information):
        """Sets the payment_information of this FulfillmentOrder.


        :param payment_information: The payment_information of this FulfillmentOrder.  # noqa: E501
        :type: PaymentInformation
        """

        self._payment_information = payment_information

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FulfillmentOrder, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FulfillmentOrder):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FulfillmentOrder):
            return True

        return self.to_dict() != other.to_dict()
