/**
 * The Selling Partner API for Orders
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { TimeWindow } from './TimeWindow.js'

/**
 * The BusinessHour model module.
 * @module orders_v2026_01_01/model/BusinessHour
 * @version 2026-01-01
 */
export class BusinessHour {
  /**
   * Constructs a new <code>BusinessHour</code>.
   * Business days and hours when the destination is open for deliveries.
   * @alias module:orders_v2026_01_01/model/BusinessHour
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>BusinessHour</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {BusinessHour} obj Optional instance to populate.
   * @return {BusinessHour} The populated <code>BusinessHour</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new BusinessHour()
      if (data.hasOwnProperty('dayOfWeek')) { obj.dayOfWeek = ApiClient.convertToType(data.dayOfWeek, 'String') }
      if (data.hasOwnProperty('timeWindows')) { obj.timeWindows = ApiClient.convertToType(data.timeWindows, [TimeWindow]) }
    }
    return obj
  }
}

/**
 * Allowed values for the <code>dayOfWeek</code> property.
 * @enum {String}
 * @readonly
 */
BusinessHour.DayOfWeekEnum = {

  /**
     * value: "SUN"
     * @const
     */
  SUN: 'SUN',

  /**
     * value: "MON"
     * @const
     */
  MON: 'MON',

  /**
     * value: "TUE"
     * @const
     */
  TUE: 'TUE',

  /**
     * value: "WED"
     * @const
     */
  WED: 'WED',

  /**
     * value: "THU"
     * @const
     */
  THU: 'THU',

  /**
     * value: "FRI"
     * @const
     */
  FRI: 'FRI',

  /**
     * value: "SAT"
     * @const
     */
  SAT: 'SAT'
}
/**
 * Specific day of the week for which operating hours are being defined.
 * @member {String} dayOfWeek
 * @type {String}
 */
BusinessHour.prototype.dayOfWeek = undefined

/**
 * Collection of time windows during which the location is available for deliveries on the specified day.
 * @member {Array[]} timeWindows
 * @type {Array[]}
 */
BusinessHour.prototype.timeWindows = undefined
