/**
 * The Selling Partner API for Orders
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { AddressExtendedFields } from './AddressExtendedFields.js'

/**
 * The CustomerAddress model module.
 * @module orders_v2026_01_01/model/CustomerAddress
 * @version 2026-01-01
 */
export class CustomerAddress {
  /**
   * Constructs a new <code>CustomerAddress</code>.
   * The physical address of the customer.
   * @alias module:orders_v2026_01_01/model/CustomerAddress
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>CustomerAddress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {CustomerAddress} obj Optional instance to populate.
   * @return {CustomerAddress} The populated <code>CustomerAddress</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new CustomerAddress()
      if (data.hasOwnProperty('name')) { obj.name = ApiClient.convertToType(data.name, 'String') }
      if (data.hasOwnProperty('companyName')) { obj.companyName = ApiClient.convertToType(data.companyName, 'String') }
      if (data.hasOwnProperty('addressLine1')) { obj.addressLine1 = ApiClient.convertToType(data.addressLine1, 'String') }
      if (data.hasOwnProperty('addressLine2')) { obj.addressLine2 = ApiClient.convertToType(data.addressLine2, 'String') }
      if (data.hasOwnProperty('addressLine3')) { obj.addressLine3 = ApiClient.convertToType(data.addressLine3, 'String') }
      if (data.hasOwnProperty('city')) { obj.city = ApiClient.convertToType(data.city, 'String') }
      if (data.hasOwnProperty('districtOrCounty')) { obj.districtOrCounty = ApiClient.convertToType(data.districtOrCounty, 'String') }
      if (data.hasOwnProperty('stateOrRegion')) { obj.stateOrRegion = ApiClient.convertToType(data.stateOrRegion, 'String') }
      if (data.hasOwnProperty('municipality')) { obj.municipality = ApiClient.convertToType(data.municipality, 'String') }
      if (data.hasOwnProperty('postalCode')) { obj.postalCode = ApiClient.convertToType(data.postalCode, 'String') }
      if (data.hasOwnProperty('countryCode')) { obj.countryCode = ApiClient.convertToType(data.countryCode, 'String') }
      if (data.hasOwnProperty('phone')) { obj.phone = ApiClient.convertToType(data.phone, 'String') }
      if (data.hasOwnProperty('extendedFields')) { obj.extendedFields = AddressExtendedFields.constructFromObject(data.extendedFields) }
      if (data.hasOwnProperty('addressType')) { obj.addressType = ApiClient.convertToType(data.addressType, 'String') }
    }
    return obj
  }
}

/**
 * The full name of the person who will receive the delivery at this address.
 * @member {String} name
 * @type {String}
 */
CustomerAddress.prototype.name = undefined

/**
 * The name of the business or organization at this address.
 * @member {String} companyName
 * @type {String}
 */
CustomerAddress.prototype.companyName = undefined

/**
 * The primary street address.
 * @member {String} addressLine1
 * @type {String}
 */
CustomerAddress.prototype.addressLine1 = undefined

/**
 * Additional address information.
 * @member {String} addressLine2
 * @type {String}
 */
CustomerAddress.prototype.addressLine2 = undefined

/**
 * Additional address information.
 * @member {String} addressLine3
 * @type {String}
 */
CustomerAddress.prototype.addressLine3 = undefined

/**
 * The city of the address.
 * @member {String} city
 * @type {String}
 */
CustomerAddress.prototype.city = undefined

/**
 * The district or county of the address.
 * @member {String} districtOrCounty
 * @type {String}
 */
CustomerAddress.prototype.districtOrCounty = undefined

/**
 * The state, province, or region of the address.
 * @member {String} stateOrRegion
 * @type {String}
 */
CustomerAddress.prototype.stateOrRegion = undefined

/**
 * The municipality of the address.
 * @member {String} municipality
 * @type {String}
 */
CustomerAddress.prototype.municipality = undefined

/**
 * The postal code, ZIP code, or equivalent mailing code of the address.
 * @member {String} postalCode
 * @type {String}
 */
CustomerAddress.prototype.postalCode = undefined

/**
 * The two-letter country code identifying the country of the address, in ISO 3166-1 format.
 * @member {String} countryCode
 * @type {String}
 */
CustomerAddress.prototype.countryCode = undefined

/**
 * The contact phone number for delivery coordination and customer communication.  **Note**: The buyer phone number will be suppressed in some cases, including but not limited to:  - All FBA (Fulfillment by Amazon) orders. - Shipped FBM (Fulfilled by the merchant) orders when current date is past the latest delivery date.
 * @member {String} phone
 * @type {String}
 */
CustomerAddress.prototype.phone = undefined

/**
 * @member {AddressExtendedFields} extendedFields
 * @type {AddressExtendedFields}
 */
CustomerAddress.prototype.extendedFields = undefined

/**
 * The type of location.  **Possible values**: `RESIDENTIAL`, `COMMERCIAL`, `PICKUP_POINT`
 * @member {String} addressType
 * @type {String}
 */
CustomerAddress.prototype.addressType = undefined
