export type FulfillmentStatus = "PENDING_AVAILABILITY" | "PENDING" | "UNSHIPPED" | "PARTIALLY_SHIPPED" | "SHIPPED" | "CANCELLED" | "UNFULFILLABLE";
/**
 * @typedef {'PENDING_AVAILABILITY'|'PENDING'|'UNSHIPPED'|'PARTIALLY_SHIPPED'|'SHIPPED'|'CANCELLED'|'UNFULFILLABLE'} FulfillmentStatus
 */
export const FulfillmentStatus: Readonly<{
    PENDING_AVAILABILITY: "PENDING_AVAILABILITY";
    PENDING: "PENDING";
    UNSHIPPED: "UNSHIPPED";
    PARTIALLY_SHIPPED: "PARTIALLY_SHIPPED";
    SHIPPED: "SHIPPED";
    CANCELLED: "CANCELLED";
    UNFULFILLABLE: "UNFULFILLABLE";
}>;
//# sourceMappingURL=FulfillmentStatus.d.ts.map