<?php

/**
 * VendorShippingLabelsApiTest
 * PHP version 8.3.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Selling Partner API
 *
 * The Selling Partner API enables developers to programmatically retrieve information from various domains.
 * These APIs provide tools for building fast, flexible, and custom applications,
 * as well as demand-based decision support systems.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpApi\Test\Api;

use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;
use SpApi\Api\vendor\df\shipping\v2021_12_28\VendorShippingLabelsApi;
use SpApi\Configuration;

/**
 * VendorShippingLabelsApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @internal
 */
class VendorShippingLabelsApiTest extends TestCase
{
    private static string $endpoint = 'http://localhost:3000';
    private static string $authEndpoint = 'http://localhost:3000/auth/o2/token';

    private VendorShippingLabelsApi $api;
    private Client $httpClient;

    protected function setUp(): void
    {
        $this->httpClient = new Client();

        $config = new Configuration([
            'clientId' => 'clientId',
            'clientSecret' => 'clientSecret',
            'refreshToken' => 'refreshToken',
            'endpoint' => self::$authEndpoint,
            'region' => 'NA',
        ]);
        $config->setHost(self::$endpoint);

        $this->api = new VendorShippingLabelsApi($config, null, false);
    }


    public function testcreateShippingLabels()
    {
        $operationId = 'createShippingLabels';
        // Strip trailing _0 suffix (added by codegen for duplicate operationIds)
        $mockOperationId = preg_replace('/_\d+$/', '', $operationId);
        $this->instructBackendMock('vendorShippingLabels', $mockOperationId, '200');
        
        $purchase_order_number = $this->generateMockData('string');
        
        $body = $this->generateMockData('\SpApi\Model\vendor\df\shipping\v2021_12_28\CreateShippingLabelsRequest');
        

        $response = $this->api->createShippingLabelsWithHttpInfo($purchase_order_number, $body);

        $this->assertEquals(200, $response[1]);
        $this->assertValidResponsePayload(200, $response[0]);
    }


    public function testgetShippingLabel()
    {
        $operationId = 'getShippingLabel';
        // Strip trailing _0 suffix (added by codegen for duplicate operationIds)
        $mockOperationId = preg_replace('/_\d+$/', '', $operationId);
        $this->instructBackendMock('vendorShippingLabels', $mockOperationId, '200');
        
        $purchase_order_number = $this->generateMockData('string');
        

        $response = $this->api->getShippingLabelWithHttpInfo($purchase_order_number);

        $this->assertEquals(200, $response[1]);
        $this->assertValidResponsePayload(200, $response[0]);
    }


    public function testgetShippingLabels()
    {
        $operationId = 'getShippingLabels';
        // Strip trailing _0 suffix (added by codegen for duplicate operationIds)
        $mockOperationId = preg_replace('/_\d+$/', '', $operationId);
        $this->instructBackendMock('vendorShippingLabels', $mockOperationId, '200');
        
        $created_after = $this->generateMockData('\DateTime');
        
        $created_before = $this->generateMockData('\DateTime');
        

        $response = $this->api->getShippingLabelsWithHttpInfo($created_after, $created_before, null, null, null, null);

        $this->assertEquals(200, $response[1]);
        $this->assertValidResponsePayload(200, $response[0]);
    }


    public function testsubmitShippingLabelRequest()
    {
        $operationId = 'submitShippingLabelRequest';
        // Strip trailing _0 suffix (added by codegen for duplicate operationIds)
        $mockOperationId = preg_replace('/_\d+$/', '', $operationId);
        $this->instructBackendMock('vendorShippingLabels', $mockOperationId, '202');
        
        $body = $this->generateMockData('\SpApi\Model\vendor\df\shipping\v2021_12_28\SubmitShippingLabelsRequest');
        

        $response = $this->api->submitShippingLabelRequestWithHttpInfo($body);

        $this->assertEquals(202, $response[1]);
        $this->assertValidResponsePayload(202, $response[0]);
    }


    private function instructBackendMock(string $basename, string $response, string $code): void
    {
        $lowerCaseCompressedBasename = strtolower(preg_replace('/[\W\s]/', '', $basename));
        $url = self::$endpoint . '/response/' . $lowerCaseCompressedBasename . '-' . $response . '/code/' . $code;
        $this->httpClient->post($url);
    }

    private function assertValidResponsePayload(int $statusCode, $body): void
    {
        if ($statusCode !== 204) {
            $this->assertNotNull($body);
        }
    }

    private function generateMockData(string $dataType, bool $isArray = false)
    {
        if ($isArray) {
            return [$this->generateMockData($dataType)];
        }

        $basicTypes = [
            'string' => 'TestString123',
            'int' => 123,
            'integer' => 123,
            'float' => 123.45,
            'bool' => true,
            'boolean' => true,
            'object' => new \stdClass(),
            '\DateTime' => new \DateTime(),
            '\SplFileObject' => null,
        ];

        $lowerType = strtolower($dataType);
        if (isset($basicTypes[$lowerType])) {
            return $basicTypes[$lowerType];
        }

        // For model objects, try to instantiate them
        if (class_exists($dataType)) {
            try {
                return new $dataType();
            } catch (\Throwable $e) {
                return null;
            }
        }

        return 'TestString123';
    }
}
