<?php

/**
 * VendorShippingApiTest
 * PHP version 8.3.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Selling Partner API
 *
 * The Selling Partner API enables developers to programmatically retrieve information from various domains.
 * These APIs provide tools for building fast, flexible, and custom applications,
 * as well as demand-based decision support systems.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpApi\Test\Api;

use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;
use SpApi\Api\vendor\df\shipping\v2021_12_28\VendorShippingApi;
use SpApi\Configuration;

/**
 * VendorShippingApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @internal
 */
class VendorShippingApiTest extends TestCase
{
    private static string $endpoint = 'http://localhost:3000';
    private static string $authEndpoint = 'http://localhost:3000/auth/o2/token';

    private VendorShippingApi $api;
    private Client $httpClient;

    protected function setUp(): void
    {
        $this->httpClient = new Client();

        $config = new Configuration([
            'clientId' => 'clientId',
            'clientSecret' => 'clientSecret',
            'refreshToken' => 'refreshToken',
            'endpoint' => self::$authEndpoint,
            'region' => 'NA',
        ]);
        $config->setHost(self::$endpoint);

        $this->api = new VendorShippingApi($config, null, false);
    }


    public function testgetPackingSlip()
    {
        $operationId = 'getPackingSlip';
        // Strip trailing _0 suffix (added by codegen for duplicate operationIds)
        $mockOperationId = preg_replace('/_\d+$/', '', $operationId);
        $this->instructBackendMock('vendorShipping', $mockOperationId, '200');
        
        $purchase_order_number = $this->generateMockData('string');
        

        $response = $this->api->getPackingSlipWithHttpInfo($purchase_order_number);

        $this->assertEquals(200, $response[1]);
        $this->assertValidResponsePayload(200, $response[0]);
    }


    public function testgetPackingSlips()
    {
        $operationId = 'getPackingSlips';
        // Strip trailing _0 suffix (added by codegen for duplicate operationIds)
        $mockOperationId = preg_replace('/_\d+$/', '', $operationId);
        $this->instructBackendMock('vendorShipping', $mockOperationId, '200');
        
        $created_after = $this->generateMockData('\DateTime');
        
        $created_before = $this->generateMockData('\DateTime');
        

        $response = $this->api->getPackingSlipsWithHttpInfo($created_after, $created_before, null, null, null, null);

        $this->assertEquals(200, $response[1]);
        $this->assertValidResponsePayload(200, $response[0]);
    }


    public function testsubmitShipmentConfirmations()
    {
        $operationId = 'submitShipmentConfirmations';
        // Strip trailing _0 suffix (added by codegen for duplicate operationIds)
        $mockOperationId = preg_replace('/_\d+$/', '', $operationId);
        $this->instructBackendMock('vendorShipping', $mockOperationId, '202');
        
        $body = $this->generateMockData('\SpApi\Model\vendor\df\shipping\v2021_12_28\SubmitShipmentConfirmationsRequest');
        

        $response = $this->api->submitShipmentConfirmationsWithHttpInfo($body);

        $this->assertEquals(202, $response[1]);
        $this->assertValidResponsePayload(202, $response[0]);
    }


    public function testsubmitShipmentStatusUpdates()
    {
        $operationId = 'submitShipmentStatusUpdates';
        // Strip trailing _0 suffix (added by codegen for duplicate operationIds)
        $mockOperationId = preg_replace('/_\d+$/', '', $operationId);
        $this->instructBackendMock('vendorShipping', $mockOperationId, '202');
        
        $body = $this->generateMockData('\SpApi\Model\vendor\df\shipping\v2021_12_28\SubmitShipmentStatusUpdatesRequest');
        

        $response = $this->api->submitShipmentStatusUpdatesWithHttpInfo($body);

        $this->assertEquals(202, $response[1]);
        $this->assertValidResponsePayload(202, $response[0]);
    }


    private function instructBackendMock(string $basename, string $response, string $code): void
    {
        $lowerCaseCompressedBasename = strtolower(preg_replace('/[\W\s]/', '', $basename));
        $url = self::$endpoint . '/response/' . $lowerCaseCompressedBasename . '-' . $response . '/code/' . $code;
        $this->httpClient->post($url);
    }

    private function assertValidResponsePayload(int $statusCode, $body): void
    {
        if ($statusCode !== 204) {
            $this->assertNotNull($body);
        }
    }

    private function generateMockData(string $dataType, bool $isArray = false)
    {
        // Handle array and specific object types
        if ($isArray) {
            $elementType = substr($dataType, 0, -2);
            return [$this->generateMockData($dataType)];
        }
        if ($dataType === '\DateTime' || $dataType === 'DateTime') {
            return new \DateTime();
        }

        if (class_exists($dataType)) {
            $reflectionClass = new ReflectionClass($dataType);
            $instance = $reflectionClass->newInstance();
            // Enum
            if (method_exists($instance, 'getAllowableEnumValues')) {
                $allowableValues = $instance::getAllowableEnumValues();
                return reset($allowableValues);
            }
            // Populate object properties recursively
            $openAPITypes = $instance::openAPITypes();
            $setters = $dataType::setters();

            foreach ($openAPITypes as $propertyName => $propertyType) {
                // Skip if the property is nullable
                if ($dataType::isNullable($propertyName)) {
                    continue;
                }

                // Generate dummy value based on the type
                $dummyValue = self::getDummyValueForType($propertyType, $propertyName);

                // Check if a setter exists for the property
                if (array_key_exists($propertyName, $setters)) {
                    $setterMethod = $setters[$propertyName];
                    if (method_exists($instance, $setterMethod)) {
                        // Call the setter method with the dummy value
                        $instance->$setterMethod($dummyValue);
                    }
                }
            }

            return $instance;
        }

        // Handle primitive types
        return match ($dataType) {
            'int' => 1,
            'float' => 1.0,
            'bool' => false,
            'string' => 'test',
            'array' => ["1"],
            default => null,
        };
    }
}
