/**
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon store products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-05-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The PostalCode model module.
 * @module pricing_v2022_05_01/model/PostalCode
 * @version 2022-05-01
 */
export declare class PostalCode {
    /**
     * Constructs a new <code>PostalCode</code>.
     * Postal code value with country code
     * @alias module:pricing_v2022_05_01/model/PostalCode
     * @class
     */
    constructor();
    /**
     * Constructs a <code>PostalCode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {PostalCode} obj Optional instance to populate.
     * @return {PostalCode} The populated <code>PostalCode</code> instance.
     */
    static constructFromObject(data: Object, obj: PostalCode): PostalCode;
}
//# sourceMappingURL=PostalCode.d.ts.map