export type AccountType = "SHIPPER_ACCOUNT" | "SHIPPER_ACCOUNT_WITH_INVOICE" | "AMAZON_ACCOUNT";
/**
 * @typedef {'SHIPPER_ACCOUNT'|'SHIPPER_ACCOUNT_WITH_INVOICE'|'AMAZON_ACCOUNT'} AccountType
 */
export const AccountType: Readonly<{
    SHIPPER_ACCOUNT: "SHIPPER_ACCOUNT";
    SHIPPER_ACCOUNT_WITH_INVOICE: "SHIPPER_ACCOUNT_WITH_INVOICE";
    AMAZON_ACCOUNT: "AMAZON_ACCOUNT";
}>;
//# sourceMappingURL=AccountType.d.ts.map