/**
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The Address model module.
 * @module shipping_v2/model/Address
 * @version v2
 */
export declare class Address {
    name: string;
    addressLine1: string;
    stateOrRegion: string;
    city: string;
    countryCode: string;
    postalCode: string;
    /**
     * Constructs a new <code>Address</code>.
     * The address.
     * @alias module:shipping_v2/model/Address
     * @class
     * @param name {String} The name of the person, business or institution at the address.
     * @param addressLine1 {String} The first line of the address.
     * @param stateOrRegion {String} The state, county or region where the person, business or institution is located.
     * @param city {String} The city or town where the person, business or institution is located.
     * @param countryCode {String} The two digit country code. Follows ISO 3166-1 alpha-2 format.
     * @param postalCode {String} The postal code of that address. It contains a series of letters or digits or both, sometimes including spaces or punctuation.
     */
    constructor(name: string, addressLine1: string, stateOrRegion: string, city: string, countryCode: string, postalCode: string);
    /**
     * Constructs a <code>Address</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {Address} obj Optional instance to populate.
     * @return {Address} The populated <code>Address</code> instance.
     */
    static constructFromObject(data: Object, obj: Address): Address;
}
//# sourceMappingURL=Address.d.ts.map