export type ClaimReason = "LOST_IN_TRANSIT" | "DAMAGED_IN_TRANSIT" | "DELIVERED_NOT_RECEIVED" | "ITEM_MISSING_SWITCHEROO" | "COD_ABUSE";
/**
 * @typedef {'LOST_IN_TRANSIT'|'DAMAGED_IN_TRANSIT'|'DELIVERED_NOT_RECEIVED'|'ITEM_MISSING_SWITCHEROO'|'COD_ABUSE'} ClaimReason
 */
export const ClaimReason: Readonly<{
    LOST_IN_TRANSIT: "LOST_IN_TRANSIT";
    DAMAGED_IN_TRANSIT: "DAMAGED_IN_TRANSIT";
    DELIVERED_NOT_RECEIVED: "DELIVERED_NOT_RECEIVED";
    ITEM_MISSING_SWITCHEROO: "ITEM_MISSING_SWITCHEROO";
    COD_ABUSE: "COD_ABUSE";
}>;
//# sourceMappingURL=ClaimReason.d.ts.map