export type IneligibilityReasonCode = "NO_COVERAGE" | "PICKUP_SLOT_RESTRICTION" | "UNSUPPORTED_VAS" | "VAS_COMBINATION_RESTRICTION" | "SIZE_RESTRICTIONS" | "WEIGHT_RESTRICTIONS" | "LATE_DELIVERY" | "PROGRAM_CONSTRAINTS" | "TERMS_AND_CONDITIONS_NOT_ACCEPTED" | "UNKNOWN";
/**
 * @typedef {'NO_COVERAGE'|'PICKUP_SLOT_RESTRICTION'|'UNSUPPORTED_VAS'|'VAS_COMBINATION_RESTRICTION'|'SIZE_RESTRICTIONS'|'WEIGHT_RESTRICTIONS'|'LATE_DELIVERY'|'PROGRAM_CONSTRAINTS'|'TERMS_AND_CONDITIONS_NOT_ACCEPTED'|'UNKNOWN'} IneligibilityReasonCode
 */
export const IneligibilityReasonCode: Readonly<{
    NO_COVERAGE: "NO_COVERAGE";
    PICKUP_SLOT_RESTRICTION: "PICKUP_SLOT_RESTRICTION";
    UNSUPPORTED_VAS: "UNSUPPORTED_VAS";
    VAS_COMBINATION_RESTRICTION: "VAS_COMBINATION_RESTRICTION";
    SIZE_RESTRICTIONS: "SIZE_RESTRICTIONS";
    WEIGHT_RESTRICTIONS: "WEIGHT_RESTRICTIONS";
    LATE_DELIVERY: "LATE_DELIVERY";
    PROGRAM_CONSTRAINTS: "PROGRAM_CONSTRAINTS";
    TERMS_AND_CONDITIONS_NOT_ACCEPTED: "TERMS_AND_CONDITIONS_NOT_ACCEPTED";
    UNKNOWN: "UNKNOWN";
}>;
//# sourceMappingURL=IneligibilityReasonCode.d.ts.map