export type LabelAttribute = "PACKAGE_CLIENT_REFERENCE_ID" | "SELLER_DISPLAY_NAME" | "COLLECT_ON_DELIVERY_AMOUNT";
/**
 * @typedef {'PACKAGE_CLIENT_REFERENCE_ID'|'SELLER_DISPLAY_NAME'|'COLLECT_ON_DELIVERY_AMOUNT'} LabelAttribute
 */
export const LabelAttribute: Readonly<{
    PACKAGE_CLIENT_REFERENCE_ID: "PACKAGE_CLIENT_REFERENCE_ID";
    SELLER_DISPLAY_NAME: "SELLER_DISPLAY_NAME";
    COLLECT_ON_DELIVERY_AMOUNT: "COLLECT_ON_DELIVERY_AMOUNT";
}>;
//# sourceMappingURL=LabelAttribute.d.ts.map