/**
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The Location model module.
 * @module shipping_v2/model/Location
 * @version v2
 */
export declare class Location {
    /**
     * Constructs a new <code>Location</code>.
     * The location where the person, business or institution is located.
     * @alias module:shipping_v2/model/Location
     * @class
     */
    constructor();
    /**
     * Constructs a <code>Location</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {Location} obj Optional instance to populate.
     * @return {Location} The populated <code>Location</code> instance.
     */
    static constructFromObject(data: Object, obj: Location): Location;
}
//# sourceMappingURL=Location.d.ts.map