export type RateItemID = "BASE_RATE" | "TRANSACTION_FEE" | "ADULT_SIGNATURE_CONFIRMATION" | "SIGNATURE_CONFIRMATION" | "NO_CONFIRMATION" | "WAIVE_SIGNATURE" | "IMPLIED_LIABILITY" | "HIDDEN_POSTAGE" | "DECLARED_VALUE" | "SUNDAY_HOLIDAY_DELIVERY" | "DELIVERY_CONFIRMATION" | "IMPORT_DUTY_CHARGE" | "VAT" | "NO_SATURDAY_DELIVERY" | "INSURANCE" | "COD" | "FUEL_SURCHARGE" | "INSPECTION_CHARGE" | "DELIVERY_AREA_SURCHARGE" | "WAYBILL_CHARGE" | "AMAZON_SPONSORED_DISCOUNT" | "INTEGRATOR_SPONSORED_DISCOUNT" | "OVERSIZE_SURCHARGE" | "CONGESTION_CHARGE" | "RESIDENTIAL_SURCHARGE" | "ADDITIONAL_SURCHARGE" | "SURCHARGE" | "REBATE" | "HIGH_CUBE_SURCHARGE" | "HIGH_LENGTH_SURCHARGE" | "HIGH_WIDTH_SURCHARGE" | "DEMAND_SURCHARGE" | "NONSTANDARD_FEE";
/**
 * @typedef {'BASE_RATE'|'TRANSACTION_FEE'|'ADULT_SIGNATURE_CONFIRMATION'|'SIGNATURE_CONFIRMATION'|'NO_CONFIRMATION'|'WAIVE_SIGNATURE'|'IMPLIED_LIABILITY'|'HIDDEN_POSTAGE'|'DECLARED_VALUE'|'SUNDAY_HOLIDAY_DELIVERY'|'DELIVERY_CONFIRMATION'|'IMPORT_DUTY_CHARGE'|'VAT'|'NO_SATURDAY_DELIVERY'|'INSURANCE'|'COD'|'FUEL_SURCHARGE'|'INSPECTION_CHARGE'|'DELIVERY_AREA_SURCHARGE'|'WAYBILL_CHARGE'|'AMAZON_SPONSORED_DISCOUNT'|'INTEGRATOR_SPONSORED_DISCOUNT'|'OVERSIZE_SURCHARGE'|'CONGESTION_CHARGE'|'RESIDENTIAL_SURCHARGE'|'ADDITIONAL_SURCHARGE'|'SURCHARGE'|'REBATE'|'HIGH_CUBE_SURCHARGE'|'HIGH_LENGTH_SURCHARGE'|'HIGH_WIDTH_SURCHARGE'|'DEMAND_SURCHARGE'|'NONSTANDARD_FEE'} RateItemID
 */
export const RateItemID: (() => void) & {
    BASE_RATE: string;
    TRANSACTION_FEE: string;
    ADULT_SIGNATURE_CONFIRMATION: string;
    SIGNATURE_CONFIRMATION: string;
    NO_CONFIRMATION: string;
    WAIVE_SIGNATURE: string;
    IMPLIED_LIABILITY: string;
    HIDDEN_POSTAGE: string;
    DECLARED_VALUE: string;
    SUNDAY_HOLIDAY_DELIVERY: string;
    DELIVERY_CONFIRMATION: string;
    IMPORT_DUTY_CHARGE: string;
    VAT: string;
    NO_SATURDAY_DELIVERY: string;
    INSURANCE: string;
    COD: string;
    FUEL_SURCHARGE: string;
    INSPECTION_CHARGE: string;
    DELIVERY_AREA_SURCHARGE: string;
    WAYBILL_CHARGE: string;
    AMAZON_SPONSORED_DISCOUNT: string;
    INTEGRATOR_SPONSORED_DISCOUNT: string;
    OVERSIZE_SURCHARGE: string;
    CONGESTION_CHARGE: string;
    RESIDENTIAL_SURCHARGE: string;
    ADDITIONAL_SURCHARGE: string;
    SURCHARGE: string;
    REBATE: string;
    HIGH_CUBE_SURCHARGE: string;
    HIGH_LENGTH_SURCHARGE: string;
    HIGH_WIDTH_SURCHARGE: string;
    DEMAND_SURCHARGE: string;
    NONSTANDARD_FEE: string;
    constructFromObject: (object: any) => any;
};
//# sourceMappingURL=RateItemID.d.ts.map