/**
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
import { DetailCodes } from './DetailCodes.js';
/**
 * The TrackingDetailCodes model module.
 * @module shipping_v2/model/TrackingDetailCodes
 * @version v2
 */
export declare class TrackingDetailCodes {
    forward: DetailCodes[];
    returns: DetailCodes[];
    /**
     * Constructs a new <code>TrackingDetailCodes</code>.
     * Contains detail codes that provide additional details related to the forward and return leg of the shipment.
     * @alias module:shipping_v2/model/TrackingDetailCodes
     * @class
     * @param forward {DetailCodes[]} Contains detail codes that provide additional details related to the forward leg of the shipment.
     * @param returns {DetailCodes[]} Contains detail codes that provide additional details related to the return leg of the shipment.
     */
    constructor(forward: DetailCodes[], returns: DetailCodes[]);
    /**
     * Constructs a <code>TrackingDetailCodes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {TrackingDetailCodes} obj Optional instance to populate.
     * @return {TrackingDetailCodes} The populated <code>TrackingDetailCodes</code> instance.
     */
    static constructFromObject(data: Object, obj: TrackingDetailCodes): TrackingDetailCodes;
}
//# sourceMappingURL=TrackingDetailCodes.d.ts.map