/**
 * The Selling Partner API for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2026-07-04
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { Amount } from './Amount.js'
import { ProductIdentifier } from './ProductIdentifier.js'

/**
 * The ShipmentItem model module.
 * @module fulfillmentoutbound_v2026_07_04/model/ShipmentItem
 * @version 2026-07-04
 */
export class ShipmentItem {
  /**
   * Constructs a new <code>ShipmentItem</code>.
   * Item information for a shipment in a fulfillment order.
   * @alias module:fulfillmentoutbound_v2026_07_04/model/ShipmentItem
   * @class
   * @param productIdentifier {ProductIdentifier}
   * @param lineItemId {String} The fulfillment order item identifier that the seller created and submitted with a call to the `createOrder` operation.
   * @param amount {Amount}
   */
  constructor (productIdentifier, lineItemId, amount) {
    this.productIdentifier = productIdentifier
    this.lineItemId = lineItemId
    this.amount = amount
  }

  /**
   * Constructs a <code>ShipmentItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {ShipmentItem} obj Optional instance to populate.
   * @return {ShipmentItem} The populated <code>ShipmentItem</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new ShipmentItem()
      if (data.hasOwnProperty('productIdentifier')) { obj.productIdentifier = ProductIdentifier.constructFromObject(data.productIdentifier) }
      if (data.hasOwnProperty('lineItemId')) { obj.lineItemId = ApiClient.convertToType(data.lineItemId, 'String') }
      if (data.hasOwnProperty('amount')) { obj.amount = Amount.constructFromObject(data.amount) }
      if (data.hasOwnProperty('packageId')) { obj.packageId = ApiClient.convertToType(data.packageId, 'String') }
      if (data.hasOwnProperty('unitIdentifiers')) { obj.unitIdentifiers = ApiClient.convertToType(data.unitIdentifiers, { String: ['String'] }) }
      if (data.hasOwnProperty('shipmentItemId')) { obj.shipmentItemId = ApiClient.convertToType(data.shipmentItemId, 'String') }
    }
    return obj
  }
}

/**
 * @member {ProductIdentifier} productIdentifier
 * @type {ProductIdentifier}
 */
ShipmentItem.prototype.productIdentifier = undefined

/**
 * The fulfillment order item identifier that the seller created and submitted with a call to the `createOrder` operation.
 * @member {String} lineItemId
 * @type {String}
 */
ShipmentItem.prototype.lineItemId = undefined

/**
 * @member {Amount} amount
 * @type {Amount}
 */
ShipmentItem.prototype.amount = undefined

/**
 * An identifier for the package that contains the item quantity.
 * @member {String} packageId
 * @type {String}
 */
ShipmentItem.prototype.packageId = undefined

/**
 * A map of unit identifier types to lists of identifier values
 * @member {Object} unitIdentifiers
 * @type {Object}
 */
ShipmentItem.prototype.unitIdentifiers = undefined

/**
 * A unique identifier for the shipment item.
 * @member {String} shipmentItemId
 * @type {String}
 */
ShipmentItem.prototype.shipmentItemId = undefined
