/*
 * Selling Partner API for A+ Content Management
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ Content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.apluscontent.v2020_11_01;

import com.google.gson.annotations.SerializedName;
import java.util.Objects;

/** A product in the three-column comparison table. */
@io.swagger.v3.oas.annotations.media.Schema(description = "A product in the three-column comparison table.")
public class ThreeColumnComparisonProduct {
    @SerializedName("position")
    private Integer position = null;

    @SerializedName("productTitle")
    private TextComponent productTitle = null;

    @SerializedName("productAsin")
    private TextComponent productAsin = null;

    @SerializedName("image")
    private ImageComponent image = null;

    public ThreeColumnComparisonProduct position(Integer position) {
        this.position = position;
        return this;
    }

    /**
     * Location of the product within the comparison table. Must be a value between 1 and 3.
     *
     * @return position
     */
    @io.swagger.v3.oas.annotations.media.Schema(
            description = "Location of the product within the comparison table. Must be a value between 1 and 3.")
    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public ThreeColumnComparisonProduct productTitle(TextComponent productTitle) {
        this.productTitle = productTitle;
        return this;
    }

    /**
     * Get productTitle
     *
     * @return productTitle
     */
    @io.swagger.v3.oas.annotations.media.Schema(description = "")
    public TextComponent getProductTitle() {
        return productTitle;
    }

    public void setProductTitle(TextComponent productTitle) {
        this.productTitle = productTitle;
    }

    public ThreeColumnComparisonProduct productAsin(TextComponent productAsin) {
        this.productAsin = productAsin;
        return this;
    }

    /**
     * Get productAsin
     *
     * @return productAsin
     */
    @io.swagger.v3.oas.annotations.media.Schema(description = "")
    public TextComponent getProductAsin() {
        return productAsin;
    }

    public void setProductAsin(TextComponent productAsin) {
        this.productAsin = productAsin;
    }

    public ThreeColumnComparisonProduct image(ImageComponent image) {
        this.image = image;
        return this;
    }

    /**
     * Get image
     *
     * @return image
     */
    @io.swagger.v3.oas.annotations.media.Schema(description = "")
    public ImageComponent getImage() {
        return image;
    }

    public void setImage(ImageComponent image) {
        this.image = image;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ThreeColumnComparisonProduct threeColumnComparisonProduct = (ThreeColumnComparisonProduct) o;
        return Objects.equals(this.position, threeColumnComparisonProduct.position)
                && Objects.equals(this.productTitle, threeColumnComparisonProduct.productTitle)
                && Objects.equals(this.productAsin, threeColumnComparisonProduct.productAsin)
                && Objects.equals(this.image, threeColumnComparisonProduct.image);
    }

    @Override
    public int hashCode() {
        return Objects.hash(position, productTitle, productAsin, image);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ThreeColumnComparisonProduct {\n");
        sb.append("    position: ").append(toIndentedString(position)).append("\n");
        sb.append("    productTitle: ").append(toIndentedString(productTitle)).append("\n");
        sb.append("    productAsin: ").append(toIndentedString(productAsin)).append("\n");
        sb.append("    image: ").append(toIndentedString(image)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /** Convert the given object to string with each line indented by 4 spaces (except the first line). */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
