/**
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForRetailProcurementShipments);
  }
}(this, function(expect, SellingPartnerApiForRetailProcurementShipments) {
  'use strict';

  var instance;

  beforeEach(function() {
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShipmentMeasurements', function() {
    it('should create an instance of ShipmentMeasurements', function() {
      // uncomment below and update the code to test ShipmentMeasurements
      //var instance = new SellingPartnerApiForRetailProcurementShipments.ShipmentMeasurements();
      //expect(instance).to.be.a(SellingPartnerApiForRetailProcurementShipments.ShipmentMeasurements);
    });

    it('should have the property grossShipmentWeight (base name: "grossShipmentWeight")', function() {
      // uncomment below and update the code to test the property grossShipmentWeight
      //var instance = new SellingPartnerApiForRetailProcurementShipments.ShipmentMeasurements();
      //expect(instance).to.be();
    });

    it('should have the property shipmentVolume (base name: "shipmentVolume")', function() {
      // uncomment below and update the code to test the property shipmentVolume
      //var instance = new SellingPartnerApiForRetailProcurementShipments.ShipmentMeasurements();
      //expect(instance).to.be();
    });

    it('should have the property cartonCount (base name: "cartonCount")', function() {
      // uncomment below and update the code to test the property cartonCount
      //var instance = new SellingPartnerApiForRetailProcurementShipments.ShipmentMeasurements();
      //expect(instance).to.be();
    });

    it('should have the property palletCount (base name: "palletCount")', function() {
      // uncomment below and update the code to test the property palletCount
      //var instance = new SellingPartnerApiForRetailProcurementShipments.ShipmentMeasurements();
      //expect(instance).to.be();
    });

  });

}));