/*
 * Selling Partner API for Shipment Invoicing
 * The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.invoicing.v0;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import software.amazon.spapi.JSON;

/** The shipment invoice status response. */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.9.0")
public class ShipmentInvoiceStatusResponse {
    public static final String SERIALIZED_NAME_SHIPMENTS = "Shipments";

    @SerializedName(SERIALIZED_NAME_SHIPMENTS)
    private ShipmentInvoiceStatusInfo shipments;

    public ShipmentInvoiceStatusResponse() {}

    public ShipmentInvoiceStatusResponse shipments(ShipmentInvoiceStatusInfo shipments) {
        this.shipments = shipments;
        return this;
    }

    /**
     * Get shipments
     *
     * @return shipments
     */
    @javax.annotation.Nullable public ShipmentInvoiceStatusInfo getShipments() {
        return shipments;
    }

    public void setShipments(ShipmentInvoiceStatusInfo shipments) {
        this.shipments = shipments;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipmentInvoiceStatusResponse shipmentInvoiceStatusResponse = (ShipmentInvoiceStatusResponse) o;
        return Objects.equals(this.shipments, shipmentInvoiceStatusResponse.shipments);
    }

    @Override
    public int hashCode() {
        return Objects.hash(shipments);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ShipmentInvoiceStatusResponse {\n");
        sb.append("    shipments: ").append(toIndentedString(shipments)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /** Convert the given object to string with each line indented by 4 spaces (except the first line). */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("Shipments");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ShipmentInvoiceStatusResponse
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ShipmentInvoiceStatusResponse.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in ShipmentInvoiceStatusResponse is not found in the empty JSON string",
                        ShipmentInvoiceStatusResponse.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries =
                jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ShipmentInvoiceStatusResponse.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(
                        "The field `%s` in the JSON string is not defined in the `ShipmentInvoiceStatusResponse` properties. JSON: %s",
                        entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the optional field `Shipments`
        if (jsonObj.get("Shipments") != null && !jsonObj.get("Shipments").isJsonNull()) {
            ShipmentInvoiceStatusInfo.validateJsonElement(jsonObj.get("Shipments"));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ShipmentInvoiceStatusResponse.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ShipmentInvoiceStatusResponse' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ShipmentInvoiceStatusResponse> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(ShipmentInvoiceStatusResponse.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<ShipmentInvoiceStatusResponse>() {
                        @Override
                        public void write(JsonWriter out, ShipmentInvoiceStatusResponse value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public ShipmentInvoiceStatusResponse read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of ShipmentInvoiceStatusResponse given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ShipmentInvoiceStatusResponse
     * @throws IOException if the JSON string is invalid with respect to ShipmentInvoiceStatusResponse
     */
    public static ShipmentInvoiceStatusResponse fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ShipmentInvoiceStatusResponse.class);
    }

    /**
     * Convert an instance of ShipmentInvoiceStatusResponse to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
