/**
 * @typedef {'ASIN'|'SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE'|'SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE'|'AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE'|'AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE'} ListOffersSortKey
 */
export class ListOffersSortKey {
    static constructFromObject(object: any): any;
    ASIN: string;
    SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE: string;
    SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE: string;
    AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE: string;
    AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE: string;
}
//# sourceMappingURL=ListOffersSortKey.d.ts.map