/**
 * @typedef {'SHIPPED_SUBSCRIPTION_UNITS'|'TOTAL_SUBSCRIPTIONS_REVENUE'|'ACTIVE_SUBSCRIPTIONS'|'NEXT_90DAYS_SHIPPED_SUBSCRIPTION_UNITS'|'NEXT_60DAYS_SHIPPED_SUBSCRIPTION_UNITS'|'NEXT_30DAYS_SHIPPED_SUBSCRIPTION_UNITS'|'NEXT_90DAYS_TOTAL_SUBSCRIPTIONS_REVENUE'|'NEXT_60DAYS_TOTAL_SUBSCRIPTIONS_REVENUE'|'NEXT_30DAYS_TOTAL_SUBSCRIPTIONS_REVENUE'} ListOfferMetricsSortKey
 */
export class ListOfferMetricsSortKey {
    static constructFromObject(object: any): any;
    SHIPPED_SUBSCRIPTION_UNITS: string;
    TOTAL_SUBSCRIPTIONS_REVENUE: string;
    ACTIVE_SUBSCRIPTIONS: string;
    NEXT_90DAYS_SHIPPED_SUBSCRIPTION_UNITS: string;
    NEXT_60DAYS_SHIPPED_SUBSCRIPTION_UNITS: string;
    NEXT_30DAYS_SHIPPED_SUBSCRIPTION_UNITS: string;
    NEXT_90DAYS_TOTAL_SUBSCRIPTIONS_REVENUE: string;
    NEXT_60DAYS_TOTAL_SUBSCRIPTIONS_REVENUE: string;
    NEXT_30DAYS_TOTAL_SUBSCRIPTIONS_REVENUE: string;
}
//# sourceMappingURL=ListOfferMetricsSortKey.d.ts.map