export type ListOffersSortKey = "ASIN" | "SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE" | "SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE" | "AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE" | "AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE";
/**
 * @typedef {'ASIN'|'SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE'|'SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE'|'AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE'|'AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE'} ListOffersSortKey
 */
export const ListOffersSortKey: (() => void) & {
    ASIN: string;
    SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE: string;
    SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE: string;
    AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE: string;
    AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE: string;
    constructFromObject: (object: any) => any;
};
//# sourceMappingURL=ListOffersSortKey.d.ts.map