export type ListOffersSortKey = "ASIN" | "SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE" | "SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE" | "AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE" | "AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE";
/**
 * @typedef {'ASIN'|'SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE'|'SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE'|'AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE'|'AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE'} ListOffersSortKey
 */
export const ListOffersSortKey: Readonly<{
    ASIN: "ASIN";
    SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE: "SELLING_PARTNER_FUNDED_BASE_DISCOUNT_PERCENTAGE";
    SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE: "SELLING_PARTNER_FUNDED_TIERED_DISCOUNT_PERCENTAGE";
    AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE: "AMAZON_FUNDED_BASE_DISCOUNT_PERCENTAGE";
    AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE: "AMAZON_FUNDED_TIERED_DISCOUNT_PERCENTAGE";
}>;
//# sourceMappingURL=ListOffersSortKey.d.ts.map