export type ListOfferMetricsSortKey = "SHIPPED_SUBSCRIPTION_UNITS" | "TOTAL_SUBSCRIPTIONS_REVENUE" | "ACTIVE_SUBSCRIPTIONS" | "NEXT_90DAYS_SHIPPED_SUBSCRIPTION_UNITS" | "NEXT_60DAYS_SHIPPED_SUBSCRIPTION_UNITS" | "NEXT_30DAYS_SHIPPED_SUBSCRIPTION_UNITS" | "NEXT_90DAYS_TOTAL_SUBSCRIPTIONS_REVENUE" | "NEXT_60DAYS_TOTAL_SUBSCRIPTIONS_REVENUE" | "NEXT_30DAYS_TOTAL_SUBSCRIPTIONS_REVENUE";
/**
 * @typedef {'SHIPPED_SUBSCRIPTION_UNITS'|'TOTAL_SUBSCRIPTIONS_REVENUE'|'ACTIVE_SUBSCRIPTIONS'|'NEXT_90DAYS_SHIPPED_SUBSCRIPTION_UNITS'|'NEXT_60DAYS_SHIPPED_SUBSCRIPTION_UNITS'|'NEXT_30DAYS_SHIPPED_SUBSCRIPTION_UNITS'|'NEXT_90DAYS_TOTAL_SUBSCRIPTIONS_REVENUE'|'NEXT_60DAYS_TOTAL_SUBSCRIPTIONS_REVENUE'|'NEXT_30DAYS_TOTAL_SUBSCRIPTIONS_REVENUE'} ListOfferMetricsSortKey
 */
export const ListOfferMetricsSortKey: Readonly<{
    SHIPPED_SUBSCRIPTION_UNITS: "SHIPPED_SUBSCRIPTION_UNITS";
    TOTAL_SUBSCRIPTIONS_REVENUE: "TOTAL_SUBSCRIPTIONS_REVENUE";
    ACTIVE_SUBSCRIPTIONS: "ACTIVE_SUBSCRIPTIONS";
    NEXT_90DAYS_SHIPPED_SUBSCRIPTION_UNITS: "NEXT_90DAYS_SHIPPED_SUBSCRIPTION_UNITS";
    NEXT_60DAYS_SHIPPED_SUBSCRIPTION_UNITS: "NEXT_60DAYS_SHIPPED_SUBSCRIPTION_UNITS";
    NEXT_30DAYS_SHIPPED_SUBSCRIPTION_UNITS: "NEXT_30DAYS_SHIPPED_SUBSCRIPTION_UNITS";
    NEXT_90DAYS_TOTAL_SUBSCRIPTIONS_REVENUE: "NEXT_90DAYS_TOTAL_SUBSCRIPTIONS_REVENUE";
    NEXT_60DAYS_TOTAL_SUBSCRIPTIONS_REVENUE: "NEXT_60DAYS_TOTAL_SUBSCRIPTIONS_REVENUE";
    NEXT_30DAYS_TOTAL_SUBSCRIPTIONS_REVENUE: "NEXT_30DAYS_TOTAL_SUBSCRIPTIONS_REVENUE";
}>;
//# sourceMappingURL=ListOfferMetricsSortKey.d.ts.map