export type Metric = "SHIPPED_SUBSCRIPTION_UNITS" | "TOTAL_SUBSCRIPTIONS_REVENUE" | "ACTIVE_SUBSCRIPTIONS" | "NOT_DELIVERED_DUE_TO_OOS" | "SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE" | "LOST_REVENUE_DUE_TO_OOS" | "SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REORDERS" | "COUPONS_REVENUE_PENETRATION" | "REVENUE_BY_DELIVERIES" | "SUBSCRIBER_RETENTION" | "REVENUE_PENETRATION_BY_SELLER_FUNDING" | "SHARE_OF_COUPON_SUBSCRIPTIONS" | "SUBSCRIBER_LIFETIME_VALUE_BY_CUSTOMER_SEGMENT" | "SIGNUP_CONVERSION_BY_SELLER_FUNDING";
/**
 * @typedef {'SHIPPED_SUBSCRIPTION_UNITS'|'TOTAL_SUBSCRIPTIONS_REVENUE'|'ACTIVE_SUBSCRIPTIONS'|'NOT_DELIVERED_DUE_TO_OOS'|'SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE'|'LOST_REVENUE_DUE_TO_OOS'|'SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REORDERS'|'COUPONS_REVENUE_PENETRATION'|'REVENUE_BY_DELIVERIES'|'SUBSCRIBER_RETENTION'|'REVENUE_PENETRATION_BY_SELLER_FUNDING'|'SHARE_OF_COUPON_SUBSCRIPTIONS'|'SUBSCRIBER_LIFETIME_VALUE_BY_CUSTOMER_SEGMENT'|'SIGNUP_CONVERSION_BY_SELLER_FUNDING'} Metric
 */
export const Metric: Readonly<{
    SHIPPED_SUBSCRIPTION_UNITS: "SHIPPED_SUBSCRIPTION_UNITS";
    TOTAL_SUBSCRIPTIONS_REVENUE: "TOTAL_SUBSCRIPTIONS_REVENUE";
    ACTIVE_SUBSCRIPTIONS: "ACTIVE_SUBSCRIPTIONS";
    NOT_DELIVERED_DUE_TO_OOS: "NOT_DELIVERED_DUE_TO_OOS";
    SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE: "SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE";
    LOST_REVENUE_DUE_TO_OOS: "LOST_REVENUE_DUE_TO_OOS";
    SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REORDERS: "SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REORDERS";
    COUPONS_REVENUE_PENETRATION: "COUPONS_REVENUE_PENETRATION";
    REVENUE_BY_DELIVERIES: "REVENUE_BY_DELIVERIES";
    SUBSCRIBER_RETENTION: "SUBSCRIBER_RETENTION";
    REVENUE_PENETRATION_BY_SELLER_FUNDING: "REVENUE_PENETRATION_BY_SELLER_FUNDING";
    SHARE_OF_COUPON_SUBSCRIPTIONS: "SHARE_OF_COUPON_SUBSCRIPTIONS";
    SUBSCRIBER_LIFETIME_VALUE_BY_CUSTOMER_SEGMENT: "SUBSCRIBER_LIFETIME_VALUE_BY_CUSTOMER_SEGMENT";
    SIGNUP_CONVERSION_BY_SELLER_FUNDING: "SIGNUP_CONVERSION_BY_SELLER_FUNDING";
}>;
//# sourceMappingURL=Metric.d.ts.map