export type Metric = "SHIPPED_SUBSCRIPTION_UNITS" | "TOTAL_SUBSCRIPTIONS_REVENUE" | "ACTIVE_SUBSCRIPTIONS" | "NOT_DELIVERED_DUE_TO_OOS" | "SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE" | "LOST_REVENUE_DUE_TO_OOS" | "SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REORDERS" | "COUPONS_REVENUE_PENETRATION" | "REVENUE_BY_DELIVERIES" | "SUBSCRIBER_RETENTION" | "REVENUE_PENETRATION_BY_SELLER_FUNDING" | "SHARE_OF_COUPON_SUBSCRIPTIONS" | "SUBSCRIBER_LIFETIME_VALUE_BY_CUSTOMER_SEGMENT" | "SIGNUP_CONVERSION_BY_SELLER_FUNDING" | "REVENUE_PENETRATION";
/**
 * @typedef {'SHIPPED_SUBSCRIPTION_UNITS'|'TOTAL_SUBSCRIPTIONS_REVENUE'|'ACTIVE_SUBSCRIPTIONS'|'NOT_DELIVERED_DUE_TO_OOS'|'SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE'|'LOST_REVENUE_DUE_TO_OOS'|'SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REORDERS'|'COUPONS_REVENUE_PENETRATION'|'REVENUE_BY_DELIVERIES'|'SUBSCRIBER_RETENTION'|'REVENUE_PENETRATION_BY_SELLER_FUNDING'|'SHARE_OF_COUPON_SUBSCRIPTIONS'|'SUBSCRIBER_LIFETIME_VALUE_BY_CUSTOMER_SEGMENT'|'SIGNUP_CONVERSION_BY_SELLER_FUNDING'|'REVENUE_PENETRATION'} Metric
 */
export const Metric: (() => void) & {
    SHIPPED_SUBSCRIPTION_UNITS: string;
    TOTAL_SUBSCRIPTIONS_REVENUE: string;
    ACTIVE_SUBSCRIPTIONS: string;
    NOT_DELIVERED_DUE_TO_OOS: string;
    SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE: string;
    LOST_REVENUE_DUE_TO_OOS: string;
    SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REORDERS: string;
    COUPONS_REVENUE_PENETRATION: string;
    REVENUE_BY_DELIVERIES: string;
    SUBSCRIBER_RETENTION: string;
    REVENUE_PENETRATION_BY_SELLER_FUNDING: string;
    SHARE_OF_COUPON_SUBSCRIPTIONS: string;
    SUBSCRIBER_LIFETIME_VALUE_BY_CUSTOMER_SEGMENT: string;
    SIGNUP_CONVERSION_BY_SELLER_FUNDING: string;
    REVENUE_PENETRATION: string;
    constructFromObject: (object: any) => any;
};
//# sourceMappingURL=Metric.d.ts.map