/**
 * Selling Partner API for Listings Items
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you can use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, refer to the [Listings Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2021-08-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
import { IssueEnforcementAction } from './IssueEnforcementAction.js';
import { IssueExemption } from './IssueExemption.js';
/**
 * The IssueEnforcements model module.
 * @module listingsitems_v2021_08_01/model/IssueEnforcements
 * @version 2021-08-01
 */
export declare class IssueEnforcements {
    actions: IssueEnforcementAction[];
    exemption: IssueExemption;
    /**
     * Constructs a new <code>IssueEnforcements</code>.
     * Provides information about the enforcement actions taken by Amazon that affect the publishing or status of a listing. It also includes details about any associated exemptions.
     * @alias module:listingsitems_v2021_08_01/model/IssueEnforcements
     * @class
     * @param actions {IssueEnforcementAction[]} List of enforcement actions taken by Amazon that affect the publishing or status of a listing.
     * @param exemption {IssueExemption}
     */
    constructor(actions: IssueEnforcementAction[], exemption: IssueExemption);
    /**
     * Constructs a <code>IssueEnforcements</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {IssueEnforcements} obj Optional instance to populate.
     * @return {IssueEnforcements} The populated <code>IssueEnforcements</code> instance.
     */
    static constructFromObject(data: Object, obj: IssueEnforcements): IssueEnforcements;
}
//# sourceMappingURL=IssueEnforcements.d.ts.map