/**
 * Selling Partner API for Orders
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The AssociatedItem model module.
 * @module orders_v0/model/AssociatedItem
 * @version v0
 */
export declare class AssociatedItem {
    /**
     * Constructs a new <code>AssociatedItem</code>.
     * An item that is associated with an order item. For example, a tire installation service that is purchased with tires.
     * @alias module:orders_v0/model/AssociatedItem
     * @class
     */
    constructor();
    /**
     * Constructs a <code>AssociatedItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {AssociatedItem} obj Optional instance to populate.
     * @return {AssociatedItem} The populated <code>AssociatedItem</code> instance.
     */
    static constructFromObject(data: Object, obj: AssociatedItem): AssociatedItem;
}
//# sourceMappingURL=AssociatedItem.d.ts.map