/*
 * Selling Partner API for Notifications
 * The Selling Partner API for Notifications lets you subscribe to notifications that are relevant to a selling partner's business. Using this API you can create a destination to receive notifications, subscribe to notifications, delete notification subscriptions, and more.  For more information, refer to the [Notifications Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide).
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.notifications.v1;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import software.amazon.spapi.JSON;

/**
 * A &#x60;notificationType&#x60; filter. This object contains all of the available filters and properties that you can
 * use to define a &#x60;notificationType&#x60; specific filter.
 */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.9.0")
public class EventFilter {
    public static final String SERIALIZED_NAME_AGGREGATION_SETTINGS = "aggregationSettings";

    @SerializedName(SERIALIZED_NAME_AGGREGATION_SETTINGS)
    private AggregationSettings aggregationSettings;

    public static final String SERIALIZED_NAME_MARKETPLACE_IDS = "marketplaceIds";

    @SerializedName(SERIALIZED_NAME_MARKETPLACE_IDS)
    private List<String> marketplaceIds = new ArrayList<>();

    public static final String SERIALIZED_NAME_ORDER_CHANGE_TYPES = "orderChangeTypes";

    @SerializedName(SERIALIZED_NAME_ORDER_CHANGE_TYPES)
    private List<OrderChangeTypeEnum> orderChangeTypes = new ArrayList<>();

    public static final String SERIALIZED_NAME_TRACKING_IDENTIFIER = "trackingIdentifier";

    @SerializedName(SERIALIZED_NAME_TRACKING_IDENTIFIER)
    private TrackingIdentifier trackingIdentifier;

    /**
     * An &#x60;eventFilterType&#x60; value that the &#x60;notificationType&#x60; supports. The subscription service
     * uses the &#x60;eventFilterType&#x60; to determine the type of event filter. To determine if a specific
     * &#x60;notificationType&#x60; supports an &#x60;eventFilterType&#x60;, refer to [Notification Type Values](
     * https://developer-docs.amazon.com/sp-api/docs/notification-type-values).
     */
    @JsonAdapter(EventFilterTypeEnum.Adapter.class)
    public enum EventFilterTypeEnum {
        ANY_OFFER_CHANGED("ANY_OFFER_CHANGED"),

        ORDER_CHANGE("ORDER_CHANGE"),

        SHIPMENT_TRACKING_MILESTONE_CHANGED("SHIPMENT_TRACKING_MILESTONE_CHANGED");

        private String value;

        EventFilterTypeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static EventFilterTypeEnum fromValue(String value) {
            for (EventFilterTypeEnum b : EventFilterTypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        public static class Adapter extends TypeAdapter<EventFilterTypeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final EventFilterTypeEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public EventFilterTypeEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return EventFilterTypeEnum.fromValue(value);
            }
        }

        public static void validateJsonElement(JsonElement jsonElement) throws IOException {
            String value = jsonElement.getAsString();
            EventFilterTypeEnum.fromValue(value);
        }
    }

    public static final String SERIALIZED_NAME_EVENT_FILTER_TYPE = "eventFilterType";

    @SerializedName(SERIALIZED_NAME_EVENT_FILTER_TYPE)
    private EventFilterTypeEnum eventFilterType;

    public EventFilter() {}

    public EventFilter aggregationSettings(AggregationSettings aggregationSettings) {
        this.aggregationSettings = aggregationSettings;
        return this;
    }

    /**
     * Get aggregationSettings
     *
     * @return aggregationSettings
     */
    @javax.annotation.Nullable public AggregationSettings getAggregationSettings() {
        return aggregationSettings;
    }

    public void setAggregationSettings(AggregationSettings aggregationSettings) {
        this.aggregationSettings = aggregationSettings;
    }

    public EventFilter marketplaceIds(List<String> marketplaceIds) {
        this.marketplaceIds = marketplaceIds;
        return this;
    }

    public EventFilter addMarketplaceIdsItem(String marketplaceIdsItem) {
        if (this.marketplaceIds == null) {
            this.marketplaceIds = new ArrayList<>();
        }
        this.marketplaceIds.add(marketplaceIdsItem);
        return this;
    }

    /**
     * A list of marketplace identifiers you can subscribe to (for example, &#x60;ATVPDKIKX0DER&#x60;). To receive
     * notifications in every marketplace, do not provide this list.
     *
     * @return marketplaceIds
     */
    @javax.annotation.Nullable public List<String> getMarketplaceIds() {
        return marketplaceIds;
    }

    public void setMarketplaceIds(List<String> marketplaceIds) {
        this.marketplaceIds = marketplaceIds;
    }

    public EventFilter orderChangeTypes(List<OrderChangeTypeEnum> orderChangeTypes) {
        this.orderChangeTypes = orderChangeTypes;
        return this;
    }

    public EventFilter addOrderChangeTypesItem(OrderChangeTypeEnum orderChangeTypesItem) {
        if (this.orderChangeTypes == null) {
            this.orderChangeTypes = new ArrayList<>();
        }
        this.orderChangeTypes.add(orderChangeTypesItem);
        return this;
    }

    /**
     * A list of order change types you can subscribe to (for example, &#x60;BuyerRequestedChange&#x60;). To receive
     * notifications of all change types, do not provide this list.
     *
     * @return orderChangeTypes
     */
    @javax.annotation.Nullable public List<OrderChangeTypeEnum> getOrderChangeTypes() {
        return orderChangeTypes;
    }

    public void setOrderChangeTypes(List<OrderChangeTypeEnum> orderChangeTypes) {
        this.orderChangeTypes = orderChangeTypes;
    }

    public EventFilter trackingIdentifier(TrackingIdentifier trackingIdentifier) {
        this.trackingIdentifier = trackingIdentifier;
        return this;
    }

    /**
     * Get trackingIdentifier
     *
     * @return trackingIdentifier
     */
    @javax.annotation.Nullable public TrackingIdentifier getTrackingIdentifier() {
        return trackingIdentifier;
    }

    public void setTrackingIdentifier(TrackingIdentifier trackingIdentifier) {
        this.trackingIdentifier = trackingIdentifier;
    }

    public EventFilter eventFilterType(EventFilterTypeEnum eventFilterType) {
        this.eventFilterType = eventFilterType;
        return this;
    }

    /**
     * An &#x60;eventFilterType&#x60; value that the &#x60;notificationType&#x60; supports. The subscription service
     * uses the &#x60;eventFilterType&#x60; to determine the type of event filter. To determine if a specific
     * &#x60;notificationType&#x60; supports an &#x60;eventFilterType&#x60;, refer to [Notification Type Values](
     * https://developer-docs.amazon.com/sp-api/docs/notification-type-values).
     *
     * @return eventFilterType
     */
    @javax.annotation.Nonnull
    public EventFilterTypeEnum getEventFilterType() {
        return eventFilterType;
    }

    public void setEventFilterType(EventFilterTypeEnum eventFilterType) {
        this.eventFilterType = eventFilterType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EventFilter eventFilter = (EventFilter) o;
        return Objects.equals(this.aggregationSettings, eventFilter.aggregationSettings)
                && Objects.equals(this.marketplaceIds, eventFilter.marketplaceIds)
                && Objects.equals(this.orderChangeTypes, eventFilter.orderChangeTypes)
                && Objects.equals(this.trackingIdentifier, eventFilter.trackingIdentifier)
                && Objects.equals(this.eventFilterType, eventFilter.eventFilterType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(aggregationSettings, marketplaceIds, orderChangeTypes, trackingIdentifier, eventFilterType);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EventFilter {\n");
        sb.append("    aggregationSettings: ")
                .append(toIndentedString(aggregationSettings))
                .append("\n");
        sb.append("    marketplaceIds: ")
                .append(toIndentedString(marketplaceIds))
                .append("\n");
        sb.append("    orderChangeTypes: ")
                .append(toIndentedString(orderChangeTypes))
                .append("\n");
        sb.append("    trackingIdentifier: ")
                .append(toIndentedString(trackingIdentifier))
                .append("\n");
        sb.append("    eventFilterType: ")
                .append(toIndentedString(eventFilterType))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /** Convert the given object to string with each line indented by 4 spaces (except the first line). */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("aggregationSettings");
        openapiFields.add("marketplaceIds");
        openapiFields.add("orderChangeTypes");
        openapiFields.add("trackingIdentifier");
        openapiFields.add("eventFilterType");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("eventFilterType");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to EventFilter
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!EventFilter.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in EventFilter is not found in the empty JSON string",
                        EventFilter.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries =
                jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!EventFilter.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(
                        "The field `%s` in the JSON string is not defined in the `EventFilter` properties. JSON: %s",
                        entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : EventFilter.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s",
                        requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the optional field `aggregationSettings`
        if (jsonObj.get("aggregationSettings") != null
                && !jsonObj.get("aggregationSettings").isJsonNull()) {
            AggregationSettings.validateJsonElement(jsonObj.get("aggregationSettings"));
        }
        // ensure the optional json data is an array if present
        if (jsonObj.get("marketplaceIds") != null
                && !jsonObj.get("marketplaceIds").isJsonNull()
                && !jsonObj.get("marketplaceIds").isJsonArray()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `marketplaceIds` to be an array in the JSON string but got `%s`",
                    jsonObj.get("marketplaceIds").toString()));
        }
        // ensure the optional json data is an array if present
        if (jsonObj.get("orderChangeTypes") != null
                && !jsonObj.get("orderChangeTypes").isJsonNull()
                && !jsonObj.get("orderChangeTypes").isJsonArray()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `orderChangeTypes` to be an array in the JSON string but got `%s`",
                    jsonObj.get("orderChangeTypes").toString()));
        }
        // validate the optional field `trackingIdentifier`
        if (jsonObj.get("trackingIdentifier") != null
                && !jsonObj.get("trackingIdentifier").isJsonNull()) {
            TrackingIdentifier.validateJsonElement(jsonObj.get("trackingIdentifier"));
        }
        if (!jsonObj.get("eventFilterType").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `eventFilterType` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("eventFilterType").toString()));
        }
        // validate the required field `eventFilterType`
        EventFilterTypeEnum.validateJsonElement(jsonObj.get("eventFilterType"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!EventFilter.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'EventFilter' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<EventFilter> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(EventFilter.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<EventFilter>() {
                        @Override
                        public void write(JsonWriter out, EventFilter value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public EventFilter read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of EventFilter given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of EventFilter
     * @throws IOException if the JSON string is invalid with respect to EventFilter
     */
    public static EventFilter fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, EventFilter.class);
    }

    /**
     * Convert an instance of EventFilter to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
