/**
 * The Selling Partner API for Amazon External Fulfillment Shipments Processing
 * You can use the External Fulfillment Shipments API to retrieve, manage, and track shipments processed through Amazon's external fulfillment network. Use this API to get shipment details, monitor status changes, and access fulfillment requirements.
 *
 * The version of the OpenAPI document: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { RequirementLevel } from './RequirementLevel.js'

/**
 * The ComplianceAttributes model module.
 * @module externalfulfillmentshipments_v2024_09_11/model/ComplianceAttributes
 * @version 2024-09-11
 */
export class ComplianceAttributes {
  /**
   * Constructs a new <code>ComplianceAttributes</code>.
   * All necessary compliance attributes specific to the line item.
   * @alias module:externalfulfillmentshipments_v2024_09_11/model/ComplianceAttributes
   * @class
   * @param hazmatLabelsRequirement {RequirementLevel}
   * @param serialNumberRequirement {RequirementLevel}
   * @param countryOfOriginRequirement {RequirementLevel}
   * @param itemValueRequirement {RequirementLevel}
   */
  constructor (hazmatLabelsRequirement, serialNumberRequirement, countryOfOriginRequirement, itemValueRequirement) {
    this.hazmatLabelsRequirement = hazmatLabelsRequirement
    this.serialNumberRequirement = serialNumberRequirement
    this.countryOfOriginRequirement = countryOfOriginRequirement
    this.itemValueRequirement = itemValueRequirement
  }

  /**
   * Constructs a <code>ComplianceAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {ComplianceAttributes} obj Optional instance to populate.
   * @return {ComplianceAttributes} The populated <code>ComplianceAttributes</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new ComplianceAttributes()
      if (data.hasOwnProperty('hazmatLabelsRequirement')) { obj.hazmatLabelsRequirement = RequirementLevel.constructFromObject(data.hazmatLabelsRequirement) }
      if (data.hasOwnProperty('serialNumberRequirement')) { obj.serialNumberRequirement = RequirementLevel.constructFromObject(data.serialNumberRequirement) }
      if (data.hasOwnProperty('countryOfOriginRequirement')) { obj.countryOfOriginRequirement = RequirementLevel.constructFromObject(data.countryOfOriginRequirement) }
      if (data.hasOwnProperty('itemValueRequirement')) { obj.itemValueRequirement = RequirementLevel.constructFromObject(data.itemValueRequirement) }
    }
    return obj
  }
}

/**
 * @member {RequirementLevel} hazmatLabelsRequirement
 * @type {RequirementLevel}
 */
ComplianceAttributes.prototype.hazmatLabelsRequirement = undefined

/**
 * @member {RequirementLevel} serialNumberRequirement
 * @type {RequirementLevel}
 */
ComplianceAttributes.prototype.serialNumberRequirement = undefined

/**
 * @member {RequirementLevel} countryOfOriginRequirement
 * @type {RequirementLevel}
 */
ComplianceAttributes.prototype.countryOfOriginRequirement = undefined

/**
 * @member {RequirementLevel} itemValueRequirement
 * @type {RequirementLevel}
 */
ComplianceAttributes.prototype.itemValueRequirement = undefined
