export type PackageStatus = "CREATED" | "PICKUP_SLOT_RETRIEVED" | "INVOICE_GENERATED" | "SHIPLABEL_GENERATED" | "SHIPPED" | "DELIVERED";
/**
 * @typedef {'CREATED'|'PICKUP_SLOT_RETRIEVED'|'INVOICE_GENERATED'|'SHIPLABEL_GENERATED'|'SHIPPED'|'DELIVERED'} PackageStatus
 */
export const PackageStatus: Readonly<{
    CREATED: "CREATED";
    PICKUP_SLOT_RETRIEVED: "PICKUP_SLOT_RETRIEVED";
    INVOICE_GENERATED: "INVOICE_GENERATED";
    SHIPLABEL_GENERATED: "SHIPLABEL_GENERATED";
    SHIPPED: "SHIPPED";
    DELIVERED: "DELIVERED";
    constructFromObject: (object: any) => any;
}>;
//# sourceMappingURL=PackageStatus.d.ts.map