/*
 * The Selling Partner API for Support
 *
 * The Selling Partner API for Support provides programmatic access to information about Selling Partner support.
 *
 * The version of the OpenAPI document: 2025-02-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = software.amzn.spapi.Client.OpenAPIDateConverter;

namespace software.amzn.spapi.Model.Support.v2025_02_01
{
    /// <summary>
    /// The content of an email contact.
    /// </summary>
    [DataContract(Name = "EmailContent")]
    public partial class EmailContent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailContent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EmailContent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailContent" /> class.
        /// </summary>
        /// <param name="sender">sender (required).</param>
        /// <param name="message">The email body of the contact. (required).</param>
        /// <param name="attachments">All attachments included in the contact..</param>
        public EmailContent(Participant sender = default(Participant), string message = default(string), List<Attachment>? attachments = default(List<Attachment>?))
        {
            // to ensure "sender" is required (not null)
            if (sender == null)
            {
                throw new ArgumentNullException("sender is a required property for EmailContent and cannot be null");
            }
            this.Sender = sender;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for EmailContent and cannot be null");
            }
            this.Message = message;
            this.Attachments = attachments;
        }

        /// <summary>
        /// Gets or Sets Sender
        /// </summary>
        [DataMember(Name = "sender", IsRequired = true, EmitDefaultValue = true)]
        public Participant Sender { get; set; }

        /// <summary>
        /// The email body of the contact.
        /// </summary>
        /// <value>The email body of the contact.</value>
        /*
        <example>sample email message</example>
        */
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// All attachments included in the contact.
        /// </summary>
        /// <value>All attachments included in the contact.</value>
        /*
        <example>[{name&#x3D;testAttachment.txt, downloadUrl&#x3D;https://filelocation/filename}]</example>
        */
        [DataMember(Name = "attachments", EmitDefaultValue = false)]
        public List<Attachment>? Attachments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailContent {\n");
            sb.Append("  Sender: ").Append(Sender).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Attachments: ").Append(Attachments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
