# coding: utf-8

"""
    The Selling Partner API for Transfers.

    The Selling Partner API for Transfers enables selling partners to retrieve payment methods and initiate payouts for their seller accounts. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE.

    The version of the OpenAPI document: 2024-06-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pprint
import re  # noqa: F401

import six

from spapi.configuration import Configuration


class ExpectedPayout(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'partner_metadata': 'PartnerMetadata',
        'amount': 'Currency',
        'status': 'ExpectedPayoutStatusName',
        'period': 'Period',
        'scheduled_date': 'datetime',
        'account_tail': 'str',
        'payment_method': 'PaymentMethodName',
        'related_identifiers': 'List[RelatedIdentifier]',
    }

    attribute_map = {
        'partner_metadata': 'partnerMetadata',
        'amount': 'amount',
        'status': 'status',
        'period': 'period',
        'scheduled_date': 'scheduledDate',
        'account_tail': 'accountTail',
        'payment_method': 'paymentMethod',
        'related_identifiers': 'relatedIdentifiers',
    }

    def __init__(self, partner_metadata=None, amount=None, status=None, period=None, scheduled_date=None, account_tail=None, payment_method=None, related_identifiers=None, _configuration=None):  # noqa: E501
        """ExpectedPayout - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._partner_metadata = None
        self._amount = None
        self._status = None
        self._period = None
        self._scheduled_date = None
        self._account_tail = None
        self._payment_method = None
        self._related_identifiers = None
        self.discriminator = None

        self.partner_metadata = partner_metadata
        if amount is not None:
            self.amount = amount
        self.status = status
        if period is not None:
            self.period = period
        if scheduled_date is not None:
            self.scheduled_date = scheduled_date
        if account_tail is not None:
            self.account_tail = account_tail
        if payment_method is not None:
            self.payment_method = payment_method
        if related_identifiers is not None:
            self.related_identifiers = related_identifiers

    @property
    def partner_metadata(self):
        """Gets the partner_metadata of this ExpectedPayout.  # noqa: E501


        :return: The partner_metadata of this ExpectedPayout.  # noqa: E501
        :rtype: PartnerMetadata
        """
        return self._partner_metadata

    @partner_metadata.setter
    def partner_metadata(self, partner_metadata):
        """Sets the partner_metadata of this ExpectedPayout.


        :param partner_metadata: The partner_metadata of this ExpectedPayout.  # noqa: E501
        :type: PartnerMetadata
        """
        if self._configuration.client_side_validation and partner_metadata is None:
            raise ValueError("Invalid value for `partner_metadata`, must not be `None`")  # noqa: E501

        self._partner_metadata = partner_metadata

    @property
    def amount(self):
        """Gets the amount of this ExpectedPayout.  # noqa: E501


        :return: The amount of this ExpectedPayout.  # noqa: E501
        :rtype: Currency
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ExpectedPayout.


        :param amount: The amount of this ExpectedPayout.  # noqa: E501
        :type: Currency
        """

        self._amount = amount

    @property
    def status(self):
        """Gets the status of this ExpectedPayout.  # noqa: E501


        :return: The status of this ExpectedPayout.  # noqa: E501
        :rtype: ExpectedPayoutStatusName
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ExpectedPayout.


        :param status: The status of this ExpectedPayout.  # noqa: E501
        :type: ExpectedPayoutStatusName
        """
        if self._configuration.client_side_validation and status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def period(self):
        """Gets the period of this ExpectedPayout.  # noqa: E501


        :return: The period of this ExpectedPayout.  # noqa: E501
        :rtype: Period
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this ExpectedPayout.


        :param period: The period of this ExpectedPayout.  # noqa: E501
        :type: Period
        """

        self._period = period

    @property
    def scheduled_date(self):
        """Gets the scheduled_date of this ExpectedPayout.  # noqa: E501

        A date in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.  # noqa: E501

        :return: The scheduled_date of this ExpectedPayout.  # noqa: E501
        :rtype: datetime
        """
        return self._scheduled_date

    @scheduled_date.setter
    def scheduled_date(self, scheduled_date):
        """Sets the scheduled_date of this ExpectedPayout.

        A date in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.  # noqa: E501

        :param scheduled_date: The scheduled_date of this ExpectedPayout.  # noqa: E501
        :type: datetime
        """

        self._scheduled_date = scheduled_date

    @property
    def account_tail(self):
        """Gets the account_tail of this ExpectedPayout.  # noqa: E501

        The last few digits of the payment instrument.  # noqa: E501

        :return: The account_tail of this ExpectedPayout.  # noqa: E501
        :rtype: str
        """
        return self._account_tail

    @account_tail.setter
    def account_tail(self, account_tail):
        """Sets the account_tail of this ExpectedPayout.

        The last few digits of the payment instrument.  # noqa: E501

        :param account_tail: The account_tail of this ExpectedPayout.  # noqa: E501
        :type: str
        """

        self._account_tail = account_tail

    @property
    def payment_method(self):
        """Gets the payment_method of this ExpectedPayout.  # noqa: E501


        :return: The payment_method of this ExpectedPayout.  # noqa: E501
        :rtype: PaymentMethodName
        """
        return self._payment_method

    @payment_method.setter
    def payment_method(self, payment_method):
        """Sets the payment_method of this ExpectedPayout.


        :param payment_method: The payment_method of this ExpectedPayout.  # noqa: E501
        :type: PaymentMethodName
        """

        self._payment_method = payment_method

    @property
    def related_identifiers(self):
        """Gets the related_identifiers of this ExpectedPayout.  # noqa: E501

        Related business identifiers of the payout.  # noqa: E501

        :return: The related_identifiers of this ExpectedPayout.  # noqa: E501
        :rtype: List[RelatedIdentifier]
        """
        return self._related_identifiers

    @related_identifiers.setter
    def related_identifiers(self, related_identifiers):
        """Sets the related_identifiers of this ExpectedPayout.

        Related business identifiers of the payout.  # noqa: E501

        :param related_identifiers: The related_identifiers of this ExpectedPayout.  # noqa: E501
        :type: List[RelatedIdentifier]
        """

        self._related_identifiers = related_identifiers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExpectedPayout, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExpectedPayout):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ExpectedPayout):
            return True

        return self.to_dict() != other.to_dict()
