export type ReplenishmentOrderStatus = "CONFIRMED" | "CREATED" | "ELIGIBLE" | "EXECUTING" | "FAILURE" | "INELIGIBLE" | "INVENTORY_OUTBOUND" | "SUCCESS" | "VALIDATING";
/**
 * @typedef {'CONFIRMED'|'CREATED'|'ELIGIBLE'|'EXECUTING'|'FAILURE'|'INELIGIBLE'|'INVENTORY_OUTBOUND'|'SUCCESS'|'VALIDATING'} ReplenishmentOrderStatus
 */
export const ReplenishmentOrderStatus: Readonly<{
    CONFIRMED: "CONFIRMED";
    CREATED: "CREATED";
    ELIGIBLE: "ELIGIBLE";
    EXECUTING: "EXECUTING";
    FAILURE: "FAILURE";
    INELIGIBLE: "INELIGIBLE";
    INVENTORY_OUTBOUND: "INVENTORY_OUTBOUND";
    SUCCESS: "SUCCESS";
    VALIDATING: "VALIDATING";
}>;
//# sourceMappingURL=ReplenishmentOrderStatus.d.ts.map