/**
 * The Selling Partner API for Transfers.
 * The Selling Partner API for Transfers enables selling partners to retrieve payment methods and initiate payouts for their seller accounts. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE.
 *
 * The version of the OpenAPI document: 2024-06-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'

/**
 * @typedef {'STARTED'|'IN_TRANSIT'|'PAID'|'FAILED'|'CANCELLED'|'NO_PAYOUT'} PayoutStatusName
 */
export const PayoutStatusName = Object.assign(
  function () {},
  {
    STARTED: 'STARTED',
    IN_TRANSIT: 'IN_TRANSIT',
    PAID: 'PAID',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
    NO_PAYOUT: 'NO_PAYOUT',
    constructFromObject: function (object) {
      return object
    }
  })
