/**
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForServices);
  }
}(this, function(expect, SellingPartnerApiForServices) {
  'use strict';

  var instance;

  beforeEach(function() {
    try{
     instance = new SellingPartnerApiForServices.FixedSlot();
    } catch (e) {
     //Handle the cases when this model extends another model by using Model.call(this);
     instance = Object.create(SellingPartnerApiForServices.FixedSlot.prototype);
    }
  });

  afterEach(function() {
    instance = null;
  })

  describe('FixedSlot', function() {
    it('should create an instance of FixedSlot', function() {
      expect(instance).to.be.a(SellingPartnerApiForServices.FixedSlot);
    });

    it('should have the property startDateTime (base name: "startDateTime")', function() {
      // verify property exists
      expect(instance).to.have.property('startDateTime');

      // set and verify value
      var validValue = generateMockData('Date');
      instance.startDateTime = validValue;
      expect(instance.startDateTime).to.equal(validValue);
    });

    it('should have the property scheduledCapacity (base name: "scheduledCapacity")', function() {
      // verify property exists
      expect(instance).to.have.property('scheduledCapacity');

      // set and verify value
      var validValue = generateMockData('Number');
      instance.scheduledCapacity = validValue;
      expect(instance.scheduledCapacity).to.equal(validValue);
    });

    it('should have the property availableCapacity (base name: "availableCapacity")', function() {
      // verify property exists
      expect(instance).to.have.property('availableCapacity');

      // set and verify value
      var validValue = generateMockData('Number');
      instance.availableCapacity = validValue;
      expect(instance.availableCapacity).to.equal(validValue);
    });

    it('should have the property encumberedCapacity (base name: "encumberedCapacity")', function() {
      // verify property exists
      expect(instance).to.have.property('encumberedCapacity');

      // set and verify value
      var validValue = generateMockData('Number');
      instance.encumberedCapacity = validValue;
      expect(instance.encumberedCapacity).to.equal(validValue);
    });

    it('should have the property reservedCapacity (base name: "reservedCapacity")', function() {
      // verify property exists
      expect(instance).to.have.property('reservedCapacity');

      // set and verify value
      var validValue = generateMockData('Number');
      instance.reservedCapacity = validValue;
      expect(instance.reservedCapacity).to.equal(validValue);
    });

  });

  // Helper function to generate random test data
  function generateMockData(dataType, isArray = false) {
    if (!dataType) return {};

    // Handle array types
    if (isArray) {
      return [generateMockData(dataType), generateMockData(dataType)];
    }

    switch(dataType) {
      case 'String':
        return 'mock-' + Math.random().toString(36).substring(2, 10);
      case 'Number':
        return Math.floor(Math.random() * 1000);
      case 'Boolean':
        return Math.random() > 0.5;
      case 'Date':
        return new Date().toISOString();
      default:
        try {
          const ModelClass = SellingPartnerApiForServices[dataType];
          if (ModelClass) {
            const instance = Object.create(ModelClass.prototype);
            return instance;
          }
        } catch (e) {
          console.error("Error creating instance of", dataType);
          return {};
        }
        return {};
    }
  }

}));
