/**
 * The Selling Partner API for Amazon External Fulfillment Location Management
 * You can use the External Fulfillment Location API to manage locations in the sandbox environment for end-to-end testing. This API is available only in the sandbox environment.
 *
 * The version of the OpenAPI document: 2026-07-30
 * Contact: marketplaceapitest@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The Error model module.
 * @module externalfulfillmentlocation_v2026_07_30/model/Error
 * @version 2026-07-30
 */
export declare class Error {
    code: string;
    message: string;
    /**
     * Constructs a new <code>Error</code>.
     * An error response returned when the request is unsuccessful.
     * @alias module:externalfulfillmentlocation_v2026_07_30/model/Error
     * @class
     * @param code {String} An error code that identifies the type of error that occurred.
     * @param message {String} A message that describes the error condition.
     */
    constructor(code: string, message: string);
    /**
     * Constructs a <code>Error</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {Error} obj Optional instance to populate.
     * @return {Error} The populated <code>Error</code> instance.
     */
    static constructFromObject(data: Object, obj: Error): Error;
}
//# sourceMappingURL=Error.d.ts.map