/**
 * The Selling Partner API for FBA inbound operations.
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
import { Address } from './Address.js';
/**
 * The InboundPlan model module.
 * @module fulfillmentinbound_v2024_03_20/model/InboundPlan
 * @version 2024-03-20
 */
export declare class InboundPlan {
    createdAt: Date;
    inboundPlanId: string;
    lastUpdatedAt: Date;
    marketplaceIds: string[];
    name: string;
    sourceAddress: Address;
    status: string;
    /**
     * Constructs a new <code>InboundPlan</code>.
     * Inbound plan containing details of the inbound workflow.
     * @alias module:fulfillmentinbound_v2024_03_20/model/InboundPlan
     * @class
     * @param createdAt {Date} The time at which the inbound plan was created. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime with pattern `yyyy-MM-ddTHH:mm:ssZ`.
     * @param inboundPlanId {String} Identifier of an inbound plan.
     * @param lastUpdatedAt {Date} The time at which the inbound plan was last updated. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime format with pattern `yyyy-MM-ddTHH:mm:ssZ`.
     * @param marketplaceIds {String[]} A list of marketplace IDs.
     * @param name {String} Human-readable name of the inbound plan.
     * @param sourceAddress {Address}
     * @param status {String} Current status of the inbound plan. Possible values: `ACTIVE`, `VOIDED`, `SHIPPED`, `ERRORED`.
     */
    constructor(createdAt: Date, inboundPlanId: string, lastUpdatedAt: Date, marketplaceIds: string[], name: string, sourceAddress: Address, status: string);
    /**
     * Constructs a <code>InboundPlan</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {InboundPlan} obj Optional instance to populate.
     * @return {InboundPlan} The populated <code>InboundPlan</code> instance.
     */
    static constructFromObject(data: Object, obj: InboundPlan): InboundPlan;
}
//# sourceMappingURL=InboundPlan.d.ts.map