export type ReasonComment = "APPOINTMENT_REQUESTED_BY_MISTAKE" | "VEHICLE_DELAY" | "SLOT_NOT_SUITABLE" | "OUTSIDE_CARRIER_BUSINESS_HOURS" | "UNFAVOURABLE_EXTERNAL_CONDITIONS" | "PROCUREMENT_DELAY" | "SHIPPING_PLAN_CHANGED" | "INCREASED_QUANTITY" | "OTHER";
/**
 * @typedef {'APPOINTMENT_REQUESTED_BY_MISTAKE'|'VEHICLE_DELAY'|'SLOT_NOT_SUITABLE'|'OUTSIDE_CARRIER_BUSINESS_HOURS'|'UNFAVOURABLE_EXTERNAL_CONDITIONS'|'PROCUREMENT_DELAY'|'SHIPPING_PLAN_CHANGED'|'INCREASED_QUANTITY'|'OTHER'} ReasonComment
 */
export const ReasonComment: Readonly<{
    APPOINTMENT_REQUESTED_BY_MISTAKE: "APPOINTMENT_REQUESTED_BY_MISTAKE";
    VEHICLE_DELAY: "VEHICLE_DELAY";
    SLOT_NOT_SUITABLE: "SLOT_NOT_SUITABLE";
    OUTSIDE_CARRIER_BUSINESS_HOURS: "OUTSIDE_CARRIER_BUSINESS_HOURS";
    UNFAVOURABLE_EXTERNAL_CONDITIONS: "UNFAVOURABLE_EXTERNAL_CONDITIONS";
    PROCUREMENT_DELAY: "PROCUREMENT_DELAY";
    SHIPPING_PLAN_CHANGED: "SHIPPING_PLAN_CHANGED";
    INCREASED_QUANTITY: "INCREASED_QUANTITY";
    OTHER: "OTHER";
}>;
//# sourceMappingURL=ReasonComment.d.ts.map