export type ReasonComment = "APPOINTMENT_REQUESTED_BY_MISTAKE" | "VEHICLE_DELAY" | "SLOT_NOT_SUITABLE" | "OUTSIDE_CARRIER_BUSINESS_HOURS" | "UNFAVOURABLE_EXTERNAL_CONDITIONS" | "PROCUREMENT_DELAY" | "SHIPPING_PLAN_CHANGED" | "INCREASED_QUANTITY" | "OTHER";
/**
 * @typedef {'APPOINTMENT_REQUESTED_BY_MISTAKE'|'VEHICLE_DELAY'|'SLOT_NOT_SUITABLE'|'OUTSIDE_CARRIER_BUSINESS_HOURS'|'UNFAVOURABLE_EXTERNAL_CONDITIONS'|'PROCUREMENT_DELAY'|'SHIPPING_PLAN_CHANGED'|'INCREASED_QUANTITY'|'OTHER'} ReasonComment
 */
export const ReasonComment: (() => void) & {
    APPOINTMENT_REQUESTED_BY_MISTAKE: string;
    VEHICLE_DELAY: string;
    SLOT_NOT_SUITABLE: string;
    OUTSIDE_CARRIER_BUSINESS_HOURS: string;
    UNFAVOURABLE_EXTERNAL_CONDITIONS: string;
    PROCUREMENT_DELAY: string;
    SHIPPING_PLAN_CHANGED: string;
    INCREASED_QUANTITY: string;
    OTHER: string;
    constructFromObject: (object: any) => any;
};
//# sourceMappingURL=ReasonComment.d.ts.map