/**
 * The Selling Partner API for FBA inbound operations.
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The TaxDetails model module.
 * @module fulfillmentinbound_v2024_03_20/model/TaxDetails
 * @version 2024-03-20
 */
export declare class TaxDetails {
    /**
     * Constructs a new <code>TaxDetails</code>.
     * Information used to determine the tax compliance.
     * @alias module:fulfillmentinbound_v2024_03_20/model/TaxDetails
     * @class
     */
    constructor();
    /**
     * Constructs a <code>TaxDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {TaxDetails} obj Optional instance to populate.
     * @return {TaxDetails} The populated <code>TaxDetails</code> instance.
     */
    static constructFromObject(data: Object, obj: TaxDetails): TaxDetails;
}
//# sourceMappingURL=TaxDetails.d.ts.map