/*
 * The Selling Partner API for Transfers.
 * The Selling Partner API for Transfers enables selling partners to retrieve payment methods and initiate payouts for their seller accounts. This API supports the following marketplaces: DE, FR, IT, ES, SE, NL, PL, and BE.
 *
 * The version of the OpenAPI document: 2024-06-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.transfers.v2024_06_01;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** Enumerated set of expected payout status names. */
@JsonAdapter(ExpectedPayoutStatusName.Adapter.class)
public enum ExpectedPayoutStatusName {
    SCHEDULED("SCHEDULED"),

    DISABLED("DISABLED"),

    AT_RISK("AT_RISK"),

    NO_PAYOUT_EXPECTED("NO_PAYOUT_EXPECTED");

    private String value;

    ExpectedPayoutStatusName(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static ExpectedPayoutStatusName fromValue(String value) {
        for (ExpectedPayoutStatusName b : ExpectedPayoutStatusName.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ExpectedPayoutStatusName> {
        @Override
        public void write(final JsonWriter jsonWriter, final ExpectedPayoutStatusName enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public ExpectedPayoutStatusName read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return ExpectedPayoutStatusName.fromValue(value);
        }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        String value = jsonElement.getAsString();
        ExpectedPayoutStatusName.fromValue(value);
    }
}
