/*
 * Selling Partner API for Finances
 * The Selling Partner API for Finances provides financial information that is relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.finances.v0;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import software.amazon.spapi.JSON;

/** An item of a debt payment or debt adjustment. */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.9.0")
public class DebtRecoveryItem {
    public static final String SERIALIZED_NAME_RECOVERY_AMOUNT = "RecoveryAmount";

    @SerializedName(SERIALIZED_NAME_RECOVERY_AMOUNT)
    private Currency recoveryAmount;

    public static final String SERIALIZED_NAME_ORIGINAL_AMOUNT = "OriginalAmount";

    @SerializedName(SERIALIZED_NAME_ORIGINAL_AMOUNT)
    private Currency originalAmount;

    public static final String SERIALIZED_NAME_GROUP_BEGIN_DATE = "GroupBeginDate";

    @SerializedName(SERIALIZED_NAME_GROUP_BEGIN_DATE)
    private OffsetDateTime groupBeginDate;

    public static final String SERIALIZED_NAME_GROUP_END_DATE = "GroupEndDate";

    @SerializedName(SERIALIZED_NAME_GROUP_END_DATE)
    private OffsetDateTime groupEndDate;

    public DebtRecoveryItem() {}

    public DebtRecoveryItem recoveryAmount(Currency recoveryAmount) {
        this.recoveryAmount = recoveryAmount;
        return this;
    }

    /**
     * Get recoveryAmount
     *
     * @return recoveryAmount
     */
    @javax.annotation.Nullable public Currency getRecoveryAmount() {
        return recoveryAmount;
    }

    public void setRecoveryAmount(Currency recoveryAmount) {
        this.recoveryAmount = recoveryAmount;
    }

    public DebtRecoveryItem originalAmount(Currency originalAmount) {
        this.originalAmount = originalAmount;
        return this;
    }

    /**
     * Get originalAmount
     *
     * @return originalAmount
     */
    @javax.annotation.Nullable public Currency getOriginalAmount() {
        return originalAmount;
    }

    public void setOriginalAmount(Currency originalAmount) {
        this.originalAmount = originalAmount;
    }

    public DebtRecoveryItem groupBeginDate(OffsetDateTime groupBeginDate) {
        this.groupBeginDate = groupBeginDate;
        return this;
    }

    /**
     * A date in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
     *
     * @return groupBeginDate
     */
    @javax.annotation.Nullable public OffsetDateTime getGroupBeginDate() {
        return groupBeginDate;
    }

    public void setGroupBeginDate(OffsetDateTime groupBeginDate) {
        this.groupBeginDate = groupBeginDate;
    }

    public DebtRecoveryItem groupEndDate(OffsetDateTime groupEndDate) {
        this.groupEndDate = groupEndDate;
        return this;
    }

    /**
     * A date in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
     *
     * @return groupEndDate
     */
    @javax.annotation.Nullable public OffsetDateTime getGroupEndDate() {
        return groupEndDate;
    }

    public void setGroupEndDate(OffsetDateTime groupEndDate) {
        this.groupEndDate = groupEndDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DebtRecoveryItem debtRecoveryItem = (DebtRecoveryItem) o;
        return Objects.equals(this.recoveryAmount, debtRecoveryItem.recoveryAmount)
                && Objects.equals(this.originalAmount, debtRecoveryItem.originalAmount)
                && Objects.equals(this.groupBeginDate, debtRecoveryItem.groupBeginDate)
                && Objects.equals(this.groupEndDate, debtRecoveryItem.groupEndDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(recoveryAmount, originalAmount, groupBeginDate, groupEndDate);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DebtRecoveryItem {\n");
        sb.append("    recoveryAmount: ")
                .append(toIndentedString(recoveryAmount))
                .append("\n");
        sb.append("    originalAmount: ")
                .append(toIndentedString(originalAmount))
                .append("\n");
        sb.append("    groupBeginDate: ")
                .append(toIndentedString(groupBeginDate))
                .append("\n");
        sb.append("    groupEndDate: ").append(toIndentedString(groupEndDate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /** Convert the given object to string with each line indented by 4 spaces (except the first line). */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("RecoveryAmount");
        openapiFields.add("OriginalAmount");
        openapiFields.add("GroupBeginDate");
        openapiFields.add("GroupEndDate");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DebtRecoveryItem
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!DebtRecoveryItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in DebtRecoveryItem is not found in the empty JSON string",
                        DebtRecoveryItem.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries =
                jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!DebtRecoveryItem.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(
                        "The field `%s` in the JSON string is not defined in the `DebtRecoveryItem` properties. JSON: %s",
                        entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the optional field `RecoveryAmount`
        if (jsonObj.get("RecoveryAmount") != null
                && !jsonObj.get("RecoveryAmount").isJsonNull()) {
            Currency.validateJsonElement(jsonObj.get("RecoveryAmount"));
        }
        // validate the optional field `OriginalAmount`
        if (jsonObj.get("OriginalAmount") != null
                && !jsonObj.get("OriginalAmount").isJsonNull()) {
            Currency.validateJsonElement(jsonObj.get("OriginalAmount"));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DebtRecoveryItem.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DebtRecoveryItem' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DebtRecoveryItem> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(DebtRecoveryItem.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<DebtRecoveryItem>() {
                        @Override
                        public void write(JsonWriter out, DebtRecoveryItem value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public DebtRecoveryItem read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of DebtRecoveryItem given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DebtRecoveryItem
     * @throws IOException if the JSON string is invalid with respect to DebtRecoveryItem
     */
    public static DebtRecoveryItem fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DebtRecoveryItem.class);
    }

    /**
     * Convert an instance of DebtRecoveryItem to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
