/*
 * Selling Partner API for Finances
 * The Selling Partner API for Finances provides financial information that is relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.finances.v0;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import software.amazon.spapi.JSON;

/** All the information that is related to a financial event. */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.9.0")
public class FinancialEvents {
    public static final String SERIALIZED_NAME_SHIPMENT_EVENT_LIST = "ShipmentEventList";

    @SerializedName(SERIALIZED_NAME_SHIPMENT_EVENT_LIST)
    private ShipmentEventList shipmentEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_SHIPMENT_SETTLE_EVENT_LIST = "ShipmentSettleEventList";

    @SerializedName(SERIALIZED_NAME_SHIPMENT_SETTLE_EVENT_LIST)
    private ShipmentSettleEventList shipmentSettleEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_REFUND_EVENT_LIST = "RefundEventList";

    @SerializedName(SERIALIZED_NAME_REFUND_EVENT_LIST)
    private ShipmentEventList refundEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_GUARANTEE_CLAIM_EVENT_LIST = "GuaranteeClaimEventList";

    @SerializedName(SERIALIZED_NAME_GUARANTEE_CLAIM_EVENT_LIST)
    private ShipmentEventList guaranteeClaimEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_EB_T_REFUND_REIMBURSEMENT_ONLY_EVENT_LIST =
            "EBTRefundReimbursementOnlyEventList";

    @SerializedName(SERIALIZED_NAME_EB_T_REFUND_REIMBURSEMENT_ONLY_EVENT_LIST)
    private EBTRefundReimbursementOnlyEventList ebTRefundReimbursementOnlyEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_CHARGEBACK_EVENT_LIST = "ChargebackEventList";

    @SerializedName(SERIALIZED_NAME_CHARGEBACK_EVENT_LIST)
    private ShipmentEventList chargebackEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_PAY_WITH_AMAZON_EVENT_LIST = "PayWithAmazonEventList";

    @SerializedName(SERIALIZED_NAME_PAY_WITH_AMAZON_EVENT_LIST)
    private PayWithAmazonEventList payWithAmazonEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_SERVICE_PROVIDER_CREDIT_EVENT_LIST = "ServiceProviderCreditEventList";

    @SerializedName(SERIALIZED_NAME_SERVICE_PROVIDER_CREDIT_EVENT_LIST)
    private SolutionProviderCreditEventList serviceProviderCreditEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_RETROCHARGE_EVENT_LIST = "RetrochargeEventList";

    @SerializedName(SERIALIZED_NAME_RETROCHARGE_EVENT_LIST)
    private RetrochargeEventList retrochargeEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_RENTAL_TRANSACTION_EVENT_LIST = "RentalTransactionEventList";

    @SerializedName(SERIALIZED_NAME_RENTAL_TRANSACTION_EVENT_LIST)
    private RentalTransactionEventList rentalTransactionEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_PRODUCT_ADS_PAYMENT_EVENT_LIST = "ProductAdsPaymentEventList";

    @SerializedName(SERIALIZED_NAME_PRODUCT_ADS_PAYMENT_EVENT_LIST)
    private ProductAdsPaymentEventList productAdsPaymentEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_SERVICE_FEE_EVENT_LIST = "ServiceFeeEventList";

    @SerializedName(SERIALIZED_NAME_SERVICE_FEE_EVENT_LIST)
    private ServiceFeeEventList serviceFeeEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_SELLER_DEAL_PAYMENT_EVENT_LIST = "SellerDealPaymentEventList";

    @SerializedName(SERIALIZED_NAME_SELLER_DEAL_PAYMENT_EVENT_LIST)
    private SellerDealPaymentEventList sellerDealPaymentEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_DEBT_RECOVERY_EVENT_LIST = "DebtRecoveryEventList";

    @SerializedName(SERIALIZED_NAME_DEBT_RECOVERY_EVENT_LIST)
    private DebtRecoveryEventList debtRecoveryEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_LOAN_SERVICING_EVENT_LIST = "LoanServicingEventList";

    @SerializedName(SERIALIZED_NAME_LOAN_SERVICING_EVENT_LIST)
    private LoanServicingEventList loanServicingEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_ADJUSTMENT_EVENT_LIST = "AdjustmentEventList";

    @SerializedName(SERIALIZED_NAME_ADJUSTMENT_EVENT_LIST)
    private AdjustmentEventList adjustmentEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_SA_F_E_T_REIMBURSEMENT_EVENT_LIST = "SAFETReimbursementEventList";

    @SerializedName(SERIALIZED_NAME_SA_F_E_T_REIMBURSEMENT_EVENT_LIST)
    private SAFETReimbursementEventList saFETReimbursementEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_SELLER_REVIEW_ENROLLMENT_PAYMENT_EVENT_LIST =
            "SellerReviewEnrollmentPaymentEventList";

    @SerializedName(SERIALIZED_NAME_SELLER_REVIEW_ENROLLMENT_PAYMENT_EVENT_LIST)
    private SellerReviewEnrollmentPaymentEventList sellerReviewEnrollmentPaymentEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_FB_A_LIQUIDATION_EVENT_LIST = "FBALiquidationEventList";

    @SerializedName(SERIALIZED_NAME_FB_A_LIQUIDATION_EVENT_LIST)
    private FBALiquidationEventList fbALiquidationEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_COUPON_PAYMENT_EVENT_LIST = "CouponPaymentEventList";

    @SerializedName(SERIALIZED_NAME_COUPON_PAYMENT_EVENT_LIST)
    private CouponPaymentEventList couponPaymentEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_IMAGING_SERVICES_FEE_EVENT_LIST = "ImagingServicesFeeEventList";

    @SerializedName(SERIALIZED_NAME_IMAGING_SERVICES_FEE_EVENT_LIST)
    private ImagingServicesFeeEventList imagingServicesFeeEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_NETWORK_COMMINGLING_TRANSACTION_EVENT_LIST =
            "NetworkComminglingTransactionEventList";

    @SerializedName(SERIALIZED_NAME_NETWORK_COMMINGLING_TRANSACTION_EVENT_LIST)
    private NetworkComminglingTransactionEventList networkComminglingTransactionEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_AFFORDABILITY_EXPENSE_EVENT_LIST = "AffordabilityExpenseEventList";

    @SerializedName(SERIALIZED_NAME_AFFORDABILITY_EXPENSE_EVENT_LIST)
    private AffordabilityExpenseEventList affordabilityExpenseEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_AFFORDABILITY_EXPENSE_REVERSAL_EVENT_LIST =
            "AffordabilityExpenseReversalEventList";

    @SerializedName(SERIALIZED_NAME_AFFORDABILITY_EXPENSE_REVERSAL_EVENT_LIST)
    private AffordabilityExpenseEventList affordabilityExpenseReversalEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_REMOVAL_SHIPMENT_EVENT_LIST = "RemovalShipmentEventList";

    @SerializedName(SERIALIZED_NAME_REMOVAL_SHIPMENT_EVENT_LIST)
    private RemovalShipmentEventList removalShipmentEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_REMOVAL_SHIPMENT_ADJUSTMENT_EVENT_LIST =
            "RemovalShipmentAdjustmentEventList";

    @SerializedName(SERIALIZED_NAME_REMOVAL_SHIPMENT_ADJUSTMENT_EVENT_LIST)
    private RemovalShipmentAdjustmentEventList removalShipmentAdjustmentEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_TRIAL_SHIPMENT_EVENT_LIST = "TrialShipmentEventList";

    @SerializedName(SERIALIZED_NAME_TRIAL_SHIPMENT_EVENT_LIST)
    private TrialShipmentEventList trialShipmentEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_TD_S_REIMBURSEMENT_EVENT_LIST = "TDSReimbursementEventList";

    @SerializedName(SERIALIZED_NAME_TD_S_REIMBURSEMENT_EVENT_LIST)
    private TDSReimbursementEventList tdSReimbursementEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_ADHOC_DISBURSEMENT_EVENT_LIST = "AdhocDisbursementEventList";

    @SerializedName(SERIALIZED_NAME_ADHOC_DISBURSEMENT_EVENT_LIST)
    private AdhocDisbursementEventList adhocDisbursementEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_TAX_WITHHOLDING_EVENT_LIST = "TaxWithholdingEventList";

    @SerializedName(SERIALIZED_NAME_TAX_WITHHOLDING_EVENT_LIST)
    private TaxWithholdingEventList taxWithholdingEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_CHARGE_REFUND_EVENT_LIST = "ChargeRefundEventList";

    @SerializedName(SERIALIZED_NAME_CHARGE_REFUND_EVENT_LIST)
    private ChargeRefundEventList chargeRefundEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_FAILED_ADHOC_DISBURSEMENT_EVENT_LIST =
            "FailedAdhocDisbursementEventList";

    @SerializedName(SERIALIZED_NAME_FAILED_ADHOC_DISBURSEMENT_EVENT_LIST)
    private FailedAdhocDisbursementEventList failedAdhocDisbursementEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_VALUE_ADDED_SERVICE_CHARGE_EVENT_LIST =
            "ValueAddedServiceChargeEventList";

    @SerializedName(SERIALIZED_NAME_VALUE_ADDED_SERVICE_CHARGE_EVENT_LIST)
    private ValueAddedServiceChargeEventList valueAddedServiceChargeEventList = new ArrayList<>();

    public static final String SERIALIZED_NAME_CAPACITY_RESERVATION_BILLING_EVENT_LIST =
            "CapacityReservationBillingEventList";

    @SerializedName(SERIALIZED_NAME_CAPACITY_RESERVATION_BILLING_EVENT_LIST)
    private CapacityReservationBillingEventList capacityReservationBillingEventList = new ArrayList<>();

    public FinancialEvents() {}

    public FinancialEvents shipmentEventList(ShipmentEventList shipmentEventList) {
        this.shipmentEventList = shipmentEventList;
        return this;
    }

    /**
     * Get shipmentEventList
     *
     * @return shipmentEventList
     */
    @javax.annotation.Nullable public ShipmentEventList getShipmentEventList() {
        return shipmentEventList;
    }

    public void setShipmentEventList(ShipmentEventList shipmentEventList) {
        this.shipmentEventList = shipmentEventList;
    }

    public FinancialEvents shipmentSettleEventList(ShipmentSettleEventList shipmentSettleEventList) {
        this.shipmentSettleEventList = shipmentSettleEventList;
        return this;
    }

    /**
     * Get shipmentSettleEventList
     *
     * @return shipmentSettleEventList
     */
    @javax.annotation.Nullable public ShipmentSettleEventList getShipmentSettleEventList() {
        return shipmentSettleEventList;
    }

    public void setShipmentSettleEventList(ShipmentSettleEventList shipmentSettleEventList) {
        this.shipmentSettleEventList = shipmentSettleEventList;
    }

    public FinancialEvents refundEventList(ShipmentEventList refundEventList) {
        this.refundEventList = refundEventList;
        return this;
    }

    /**
     * Get refundEventList
     *
     * @return refundEventList
     */
    @javax.annotation.Nullable public ShipmentEventList getRefundEventList() {
        return refundEventList;
    }

    public void setRefundEventList(ShipmentEventList refundEventList) {
        this.refundEventList = refundEventList;
    }

    public FinancialEvents guaranteeClaimEventList(ShipmentEventList guaranteeClaimEventList) {
        this.guaranteeClaimEventList = guaranteeClaimEventList;
        return this;
    }

    /**
     * Get guaranteeClaimEventList
     *
     * @return guaranteeClaimEventList
     */
    @javax.annotation.Nullable public ShipmentEventList getGuaranteeClaimEventList() {
        return guaranteeClaimEventList;
    }

    public void setGuaranteeClaimEventList(ShipmentEventList guaranteeClaimEventList) {
        this.guaranteeClaimEventList = guaranteeClaimEventList;
    }

    public FinancialEvents ebTRefundReimbursementOnlyEventList(
            EBTRefundReimbursementOnlyEventList ebTRefundReimbursementOnlyEventList) {
        this.ebTRefundReimbursementOnlyEventList = ebTRefundReimbursementOnlyEventList;
        return this;
    }

    /**
     * Get ebTRefundReimbursementOnlyEventList
     *
     * @return ebTRefundReimbursementOnlyEventList
     */
    @javax.annotation.Nullable public EBTRefundReimbursementOnlyEventList getEbTRefundReimbursementOnlyEventList() {
        return ebTRefundReimbursementOnlyEventList;
    }

    public void setEbTRefundReimbursementOnlyEventList(
            EBTRefundReimbursementOnlyEventList ebTRefundReimbursementOnlyEventList) {
        this.ebTRefundReimbursementOnlyEventList = ebTRefundReimbursementOnlyEventList;
    }

    public FinancialEvents chargebackEventList(ShipmentEventList chargebackEventList) {
        this.chargebackEventList = chargebackEventList;
        return this;
    }

    /**
     * Get chargebackEventList
     *
     * @return chargebackEventList
     */
    @javax.annotation.Nullable public ShipmentEventList getChargebackEventList() {
        return chargebackEventList;
    }

    public void setChargebackEventList(ShipmentEventList chargebackEventList) {
        this.chargebackEventList = chargebackEventList;
    }

    public FinancialEvents payWithAmazonEventList(PayWithAmazonEventList payWithAmazonEventList) {
        this.payWithAmazonEventList = payWithAmazonEventList;
        return this;
    }

    /**
     * Get payWithAmazonEventList
     *
     * @return payWithAmazonEventList
     */
    @javax.annotation.Nullable public PayWithAmazonEventList getPayWithAmazonEventList() {
        return payWithAmazonEventList;
    }

    public void setPayWithAmazonEventList(PayWithAmazonEventList payWithAmazonEventList) {
        this.payWithAmazonEventList = payWithAmazonEventList;
    }

    public FinancialEvents serviceProviderCreditEventList(
            SolutionProviderCreditEventList serviceProviderCreditEventList) {
        this.serviceProviderCreditEventList = serviceProviderCreditEventList;
        return this;
    }

    /**
     * Get serviceProviderCreditEventList
     *
     * @return serviceProviderCreditEventList
     */
    @javax.annotation.Nullable public SolutionProviderCreditEventList getServiceProviderCreditEventList() {
        return serviceProviderCreditEventList;
    }

    public void setServiceProviderCreditEventList(SolutionProviderCreditEventList serviceProviderCreditEventList) {
        this.serviceProviderCreditEventList = serviceProviderCreditEventList;
    }

    public FinancialEvents retrochargeEventList(RetrochargeEventList retrochargeEventList) {
        this.retrochargeEventList = retrochargeEventList;
        return this;
    }

    /**
     * Get retrochargeEventList
     *
     * @return retrochargeEventList
     */
    @javax.annotation.Nullable public RetrochargeEventList getRetrochargeEventList() {
        return retrochargeEventList;
    }

    public void setRetrochargeEventList(RetrochargeEventList retrochargeEventList) {
        this.retrochargeEventList = retrochargeEventList;
    }

    public FinancialEvents rentalTransactionEventList(RentalTransactionEventList rentalTransactionEventList) {
        this.rentalTransactionEventList = rentalTransactionEventList;
        return this;
    }

    /**
     * Get rentalTransactionEventList
     *
     * @return rentalTransactionEventList
     */
    @javax.annotation.Nullable public RentalTransactionEventList getRentalTransactionEventList() {
        return rentalTransactionEventList;
    }

    public void setRentalTransactionEventList(RentalTransactionEventList rentalTransactionEventList) {
        this.rentalTransactionEventList = rentalTransactionEventList;
    }

    public FinancialEvents productAdsPaymentEventList(ProductAdsPaymentEventList productAdsPaymentEventList) {
        this.productAdsPaymentEventList = productAdsPaymentEventList;
        return this;
    }

    /**
     * Get productAdsPaymentEventList
     *
     * @return productAdsPaymentEventList
     */
    @javax.annotation.Nullable public ProductAdsPaymentEventList getProductAdsPaymentEventList() {
        return productAdsPaymentEventList;
    }

    public void setProductAdsPaymentEventList(ProductAdsPaymentEventList productAdsPaymentEventList) {
        this.productAdsPaymentEventList = productAdsPaymentEventList;
    }

    public FinancialEvents serviceFeeEventList(ServiceFeeEventList serviceFeeEventList) {
        this.serviceFeeEventList = serviceFeeEventList;
        return this;
    }

    /**
     * Get serviceFeeEventList
     *
     * @return serviceFeeEventList
     */
    @javax.annotation.Nullable public ServiceFeeEventList getServiceFeeEventList() {
        return serviceFeeEventList;
    }

    public void setServiceFeeEventList(ServiceFeeEventList serviceFeeEventList) {
        this.serviceFeeEventList = serviceFeeEventList;
    }

    public FinancialEvents sellerDealPaymentEventList(SellerDealPaymentEventList sellerDealPaymentEventList) {
        this.sellerDealPaymentEventList = sellerDealPaymentEventList;
        return this;
    }

    /**
     * Get sellerDealPaymentEventList
     *
     * @return sellerDealPaymentEventList
     */
    @javax.annotation.Nullable public SellerDealPaymentEventList getSellerDealPaymentEventList() {
        return sellerDealPaymentEventList;
    }

    public void setSellerDealPaymentEventList(SellerDealPaymentEventList sellerDealPaymentEventList) {
        this.sellerDealPaymentEventList = sellerDealPaymentEventList;
    }

    public FinancialEvents debtRecoveryEventList(DebtRecoveryEventList debtRecoveryEventList) {
        this.debtRecoveryEventList = debtRecoveryEventList;
        return this;
    }

    /**
     * Get debtRecoveryEventList
     *
     * @return debtRecoveryEventList
     */
    @javax.annotation.Nullable public DebtRecoveryEventList getDebtRecoveryEventList() {
        return debtRecoveryEventList;
    }

    public void setDebtRecoveryEventList(DebtRecoveryEventList debtRecoveryEventList) {
        this.debtRecoveryEventList = debtRecoveryEventList;
    }

    public FinancialEvents loanServicingEventList(LoanServicingEventList loanServicingEventList) {
        this.loanServicingEventList = loanServicingEventList;
        return this;
    }

    /**
     * Get loanServicingEventList
     *
     * @return loanServicingEventList
     */
    @javax.annotation.Nullable public LoanServicingEventList getLoanServicingEventList() {
        return loanServicingEventList;
    }

    public void setLoanServicingEventList(LoanServicingEventList loanServicingEventList) {
        this.loanServicingEventList = loanServicingEventList;
    }

    public FinancialEvents adjustmentEventList(AdjustmentEventList adjustmentEventList) {
        this.adjustmentEventList = adjustmentEventList;
        return this;
    }

    /**
     * Get adjustmentEventList
     *
     * @return adjustmentEventList
     */
    @javax.annotation.Nullable public AdjustmentEventList getAdjustmentEventList() {
        return adjustmentEventList;
    }

    public void setAdjustmentEventList(AdjustmentEventList adjustmentEventList) {
        this.adjustmentEventList = adjustmentEventList;
    }

    public FinancialEvents saFETReimbursementEventList(SAFETReimbursementEventList saFETReimbursementEventList) {
        this.saFETReimbursementEventList = saFETReimbursementEventList;
        return this;
    }

    /**
     * Get saFETReimbursementEventList
     *
     * @return saFETReimbursementEventList
     */
    @javax.annotation.Nullable public SAFETReimbursementEventList getSaFETReimbursementEventList() {
        return saFETReimbursementEventList;
    }

    public void setSaFETReimbursementEventList(SAFETReimbursementEventList saFETReimbursementEventList) {
        this.saFETReimbursementEventList = saFETReimbursementEventList;
    }

    public FinancialEvents sellerReviewEnrollmentPaymentEventList(
            SellerReviewEnrollmentPaymentEventList sellerReviewEnrollmentPaymentEventList) {
        this.sellerReviewEnrollmentPaymentEventList = sellerReviewEnrollmentPaymentEventList;
        return this;
    }

    /**
     * Get sellerReviewEnrollmentPaymentEventList
     *
     * @return sellerReviewEnrollmentPaymentEventList
     */
    @javax.annotation.Nullable public SellerReviewEnrollmentPaymentEventList getSellerReviewEnrollmentPaymentEventList() {
        return sellerReviewEnrollmentPaymentEventList;
    }

    public void setSellerReviewEnrollmentPaymentEventList(
            SellerReviewEnrollmentPaymentEventList sellerReviewEnrollmentPaymentEventList) {
        this.sellerReviewEnrollmentPaymentEventList = sellerReviewEnrollmentPaymentEventList;
    }

    public FinancialEvents fbALiquidationEventList(FBALiquidationEventList fbALiquidationEventList) {
        this.fbALiquidationEventList = fbALiquidationEventList;
        return this;
    }

    /**
     * Get fbALiquidationEventList
     *
     * @return fbALiquidationEventList
     */
    @javax.annotation.Nullable public FBALiquidationEventList getFbALiquidationEventList() {
        return fbALiquidationEventList;
    }

    public void setFbALiquidationEventList(FBALiquidationEventList fbALiquidationEventList) {
        this.fbALiquidationEventList = fbALiquidationEventList;
    }

    public FinancialEvents couponPaymentEventList(CouponPaymentEventList couponPaymentEventList) {
        this.couponPaymentEventList = couponPaymentEventList;
        return this;
    }

    /**
     * Get couponPaymentEventList
     *
     * @return couponPaymentEventList
     */
    @javax.annotation.Nullable public CouponPaymentEventList getCouponPaymentEventList() {
        return couponPaymentEventList;
    }

    public void setCouponPaymentEventList(CouponPaymentEventList couponPaymentEventList) {
        this.couponPaymentEventList = couponPaymentEventList;
    }

    public FinancialEvents imagingServicesFeeEventList(ImagingServicesFeeEventList imagingServicesFeeEventList) {
        this.imagingServicesFeeEventList = imagingServicesFeeEventList;
        return this;
    }

    /**
     * Get imagingServicesFeeEventList
     *
     * @return imagingServicesFeeEventList
     */
    @javax.annotation.Nullable public ImagingServicesFeeEventList getImagingServicesFeeEventList() {
        return imagingServicesFeeEventList;
    }

    public void setImagingServicesFeeEventList(ImagingServicesFeeEventList imagingServicesFeeEventList) {
        this.imagingServicesFeeEventList = imagingServicesFeeEventList;
    }

    public FinancialEvents networkComminglingTransactionEventList(
            NetworkComminglingTransactionEventList networkComminglingTransactionEventList) {
        this.networkComminglingTransactionEventList = networkComminglingTransactionEventList;
        return this;
    }

    /**
     * Get networkComminglingTransactionEventList
     *
     * @return networkComminglingTransactionEventList
     */
    @javax.annotation.Nullable public NetworkComminglingTransactionEventList getNetworkComminglingTransactionEventList() {
        return networkComminglingTransactionEventList;
    }

    public void setNetworkComminglingTransactionEventList(
            NetworkComminglingTransactionEventList networkComminglingTransactionEventList) {
        this.networkComminglingTransactionEventList = networkComminglingTransactionEventList;
    }

    public FinancialEvents affordabilityExpenseEventList(AffordabilityExpenseEventList affordabilityExpenseEventList) {
        this.affordabilityExpenseEventList = affordabilityExpenseEventList;
        return this;
    }

    /**
     * Get affordabilityExpenseEventList
     *
     * @return affordabilityExpenseEventList
     */
    @javax.annotation.Nullable public AffordabilityExpenseEventList getAffordabilityExpenseEventList() {
        return affordabilityExpenseEventList;
    }

    public void setAffordabilityExpenseEventList(AffordabilityExpenseEventList affordabilityExpenseEventList) {
        this.affordabilityExpenseEventList = affordabilityExpenseEventList;
    }

    public FinancialEvents affordabilityExpenseReversalEventList(
            AffordabilityExpenseEventList affordabilityExpenseReversalEventList) {
        this.affordabilityExpenseReversalEventList = affordabilityExpenseReversalEventList;
        return this;
    }

    /**
     * Get affordabilityExpenseReversalEventList
     *
     * @return affordabilityExpenseReversalEventList
     */
    @javax.annotation.Nullable public AffordabilityExpenseEventList getAffordabilityExpenseReversalEventList() {
        return affordabilityExpenseReversalEventList;
    }

    public void setAffordabilityExpenseReversalEventList(
            AffordabilityExpenseEventList affordabilityExpenseReversalEventList) {
        this.affordabilityExpenseReversalEventList = affordabilityExpenseReversalEventList;
    }

    public FinancialEvents removalShipmentEventList(RemovalShipmentEventList removalShipmentEventList) {
        this.removalShipmentEventList = removalShipmentEventList;
        return this;
    }

    /**
     * Get removalShipmentEventList
     *
     * @return removalShipmentEventList
     */
    @javax.annotation.Nullable public RemovalShipmentEventList getRemovalShipmentEventList() {
        return removalShipmentEventList;
    }

    public void setRemovalShipmentEventList(RemovalShipmentEventList removalShipmentEventList) {
        this.removalShipmentEventList = removalShipmentEventList;
    }

    public FinancialEvents removalShipmentAdjustmentEventList(
            RemovalShipmentAdjustmentEventList removalShipmentAdjustmentEventList) {
        this.removalShipmentAdjustmentEventList = removalShipmentAdjustmentEventList;
        return this;
    }

    /**
     * Get removalShipmentAdjustmentEventList
     *
     * @return removalShipmentAdjustmentEventList
     */
    @javax.annotation.Nullable public RemovalShipmentAdjustmentEventList getRemovalShipmentAdjustmentEventList() {
        return removalShipmentAdjustmentEventList;
    }

    public void setRemovalShipmentAdjustmentEventList(
            RemovalShipmentAdjustmentEventList removalShipmentAdjustmentEventList) {
        this.removalShipmentAdjustmentEventList = removalShipmentAdjustmentEventList;
    }

    public FinancialEvents trialShipmentEventList(TrialShipmentEventList trialShipmentEventList) {
        this.trialShipmentEventList = trialShipmentEventList;
        return this;
    }

    /**
     * Get trialShipmentEventList
     *
     * @return trialShipmentEventList
     */
    @javax.annotation.Nullable public TrialShipmentEventList getTrialShipmentEventList() {
        return trialShipmentEventList;
    }

    public void setTrialShipmentEventList(TrialShipmentEventList trialShipmentEventList) {
        this.trialShipmentEventList = trialShipmentEventList;
    }

    public FinancialEvents tdSReimbursementEventList(TDSReimbursementEventList tdSReimbursementEventList) {
        this.tdSReimbursementEventList = tdSReimbursementEventList;
        return this;
    }

    /**
     * Get tdSReimbursementEventList
     *
     * @return tdSReimbursementEventList
     */
    @javax.annotation.Nullable public TDSReimbursementEventList getTdSReimbursementEventList() {
        return tdSReimbursementEventList;
    }

    public void setTdSReimbursementEventList(TDSReimbursementEventList tdSReimbursementEventList) {
        this.tdSReimbursementEventList = tdSReimbursementEventList;
    }

    public FinancialEvents adhocDisbursementEventList(AdhocDisbursementEventList adhocDisbursementEventList) {
        this.adhocDisbursementEventList = adhocDisbursementEventList;
        return this;
    }

    /**
     * Get adhocDisbursementEventList
     *
     * @return adhocDisbursementEventList
     */
    @javax.annotation.Nullable public AdhocDisbursementEventList getAdhocDisbursementEventList() {
        return adhocDisbursementEventList;
    }

    public void setAdhocDisbursementEventList(AdhocDisbursementEventList adhocDisbursementEventList) {
        this.adhocDisbursementEventList = adhocDisbursementEventList;
    }

    public FinancialEvents taxWithholdingEventList(TaxWithholdingEventList taxWithholdingEventList) {
        this.taxWithholdingEventList = taxWithholdingEventList;
        return this;
    }

    /**
     * Get taxWithholdingEventList
     *
     * @return taxWithholdingEventList
     */
    @javax.annotation.Nullable public TaxWithholdingEventList getTaxWithholdingEventList() {
        return taxWithholdingEventList;
    }

    public void setTaxWithholdingEventList(TaxWithholdingEventList taxWithholdingEventList) {
        this.taxWithholdingEventList = taxWithholdingEventList;
    }

    public FinancialEvents chargeRefundEventList(ChargeRefundEventList chargeRefundEventList) {
        this.chargeRefundEventList = chargeRefundEventList;
        return this;
    }

    /**
     * Get chargeRefundEventList
     *
     * @return chargeRefundEventList
     */
    @javax.annotation.Nullable public ChargeRefundEventList getChargeRefundEventList() {
        return chargeRefundEventList;
    }

    public void setChargeRefundEventList(ChargeRefundEventList chargeRefundEventList) {
        this.chargeRefundEventList = chargeRefundEventList;
    }

    public FinancialEvents failedAdhocDisbursementEventList(
            FailedAdhocDisbursementEventList failedAdhocDisbursementEventList) {
        this.failedAdhocDisbursementEventList = failedAdhocDisbursementEventList;
        return this;
    }

    /**
     * Get failedAdhocDisbursementEventList
     *
     * @return failedAdhocDisbursementEventList
     */
    @javax.annotation.Nullable public FailedAdhocDisbursementEventList getFailedAdhocDisbursementEventList() {
        return failedAdhocDisbursementEventList;
    }

    public void setFailedAdhocDisbursementEventList(FailedAdhocDisbursementEventList failedAdhocDisbursementEventList) {
        this.failedAdhocDisbursementEventList = failedAdhocDisbursementEventList;
    }

    public FinancialEvents valueAddedServiceChargeEventList(
            ValueAddedServiceChargeEventList valueAddedServiceChargeEventList) {
        this.valueAddedServiceChargeEventList = valueAddedServiceChargeEventList;
        return this;
    }

    /**
     * Get valueAddedServiceChargeEventList
     *
     * @return valueAddedServiceChargeEventList
     */
    @javax.annotation.Nullable public ValueAddedServiceChargeEventList getValueAddedServiceChargeEventList() {
        return valueAddedServiceChargeEventList;
    }

    public void setValueAddedServiceChargeEventList(ValueAddedServiceChargeEventList valueAddedServiceChargeEventList) {
        this.valueAddedServiceChargeEventList = valueAddedServiceChargeEventList;
    }

    public FinancialEvents capacityReservationBillingEventList(
            CapacityReservationBillingEventList capacityReservationBillingEventList) {
        this.capacityReservationBillingEventList = capacityReservationBillingEventList;
        return this;
    }

    /**
     * Get capacityReservationBillingEventList
     *
     * @return capacityReservationBillingEventList
     */
    @javax.annotation.Nullable public CapacityReservationBillingEventList getCapacityReservationBillingEventList() {
        return capacityReservationBillingEventList;
    }

    public void setCapacityReservationBillingEventList(
            CapacityReservationBillingEventList capacityReservationBillingEventList) {
        this.capacityReservationBillingEventList = capacityReservationBillingEventList;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FinancialEvents financialEvents = (FinancialEvents) o;
        return Objects.equals(this.shipmentEventList, financialEvents.shipmentEventList)
                && Objects.equals(this.shipmentSettleEventList, financialEvents.shipmentSettleEventList)
                && Objects.equals(this.refundEventList, financialEvents.refundEventList)
                && Objects.equals(this.guaranteeClaimEventList, financialEvents.guaranteeClaimEventList)
                && Objects.equals(
                        this.ebTRefundReimbursementOnlyEventList, financialEvents.ebTRefundReimbursementOnlyEventList)
                && Objects.equals(this.chargebackEventList, financialEvents.chargebackEventList)
                && Objects.equals(this.payWithAmazonEventList, financialEvents.payWithAmazonEventList)
                && Objects.equals(this.serviceProviderCreditEventList, financialEvents.serviceProviderCreditEventList)
                && Objects.equals(this.retrochargeEventList, financialEvents.retrochargeEventList)
                && Objects.equals(this.rentalTransactionEventList, financialEvents.rentalTransactionEventList)
                && Objects.equals(this.productAdsPaymentEventList, financialEvents.productAdsPaymentEventList)
                && Objects.equals(this.serviceFeeEventList, financialEvents.serviceFeeEventList)
                && Objects.equals(this.sellerDealPaymentEventList, financialEvents.sellerDealPaymentEventList)
                && Objects.equals(this.debtRecoveryEventList, financialEvents.debtRecoveryEventList)
                && Objects.equals(this.loanServicingEventList, financialEvents.loanServicingEventList)
                && Objects.equals(this.adjustmentEventList, financialEvents.adjustmentEventList)
                && Objects.equals(this.saFETReimbursementEventList, financialEvents.saFETReimbursementEventList)
                && Objects.equals(
                        this.sellerReviewEnrollmentPaymentEventList,
                        financialEvents.sellerReviewEnrollmentPaymentEventList)
                && Objects.equals(this.fbALiquidationEventList, financialEvents.fbALiquidationEventList)
                && Objects.equals(this.couponPaymentEventList, financialEvents.couponPaymentEventList)
                && Objects.equals(this.imagingServicesFeeEventList, financialEvents.imagingServicesFeeEventList)
                && Objects.equals(
                        this.networkComminglingTransactionEventList,
                        financialEvents.networkComminglingTransactionEventList)
                && Objects.equals(this.affordabilityExpenseEventList, financialEvents.affordabilityExpenseEventList)
                && Objects.equals(
                        this.affordabilityExpenseReversalEventList,
                        financialEvents.affordabilityExpenseReversalEventList)
                && Objects.equals(this.removalShipmentEventList, financialEvents.removalShipmentEventList)
                && Objects.equals(
                        this.removalShipmentAdjustmentEventList, financialEvents.removalShipmentAdjustmentEventList)
                && Objects.equals(this.trialShipmentEventList, financialEvents.trialShipmentEventList)
                && Objects.equals(this.tdSReimbursementEventList, financialEvents.tdSReimbursementEventList)
                && Objects.equals(this.adhocDisbursementEventList, financialEvents.adhocDisbursementEventList)
                && Objects.equals(this.taxWithholdingEventList, financialEvents.taxWithholdingEventList)
                && Objects.equals(this.chargeRefundEventList, financialEvents.chargeRefundEventList)
                && Objects.equals(
                        this.failedAdhocDisbursementEventList, financialEvents.failedAdhocDisbursementEventList)
                && Objects.equals(
                        this.valueAddedServiceChargeEventList, financialEvents.valueAddedServiceChargeEventList)
                && Objects.equals(
                        this.capacityReservationBillingEventList, financialEvents.capacityReservationBillingEventList);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                shipmentEventList,
                shipmentSettleEventList,
                refundEventList,
                guaranteeClaimEventList,
                ebTRefundReimbursementOnlyEventList,
                chargebackEventList,
                payWithAmazonEventList,
                serviceProviderCreditEventList,
                retrochargeEventList,
                rentalTransactionEventList,
                productAdsPaymentEventList,
                serviceFeeEventList,
                sellerDealPaymentEventList,
                debtRecoveryEventList,
                loanServicingEventList,
                adjustmentEventList,
                saFETReimbursementEventList,
                sellerReviewEnrollmentPaymentEventList,
                fbALiquidationEventList,
                couponPaymentEventList,
                imagingServicesFeeEventList,
                networkComminglingTransactionEventList,
                affordabilityExpenseEventList,
                affordabilityExpenseReversalEventList,
                removalShipmentEventList,
                removalShipmentAdjustmentEventList,
                trialShipmentEventList,
                tdSReimbursementEventList,
                adhocDisbursementEventList,
                taxWithholdingEventList,
                chargeRefundEventList,
                failedAdhocDisbursementEventList,
                valueAddedServiceChargeEventList,
                capacityReservationBillingEventList);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FinancialEvents {\n");
        sb.append("    shipmentEventList: ")
                .append(toIndentedString(shipmentEventList))
                .append("\n");
        sb.append("    shipmentSettleEventList: ")
                .append(toIndentedString(shipmentSettleEventList))
                .append("\n");
        sb.append("    refundEventList: ")
                .append(toIndentedString(refundEventList))
                .append("\n");
        sb.append("    guaranteeClaimEventList: ")
                .append(toIndentedString(guaranteeClaimEventList))
                .append("\n");
        sb.append("    ebTRefundReimbursementOnlyEventList: ")
                .append(toIndentedString(ebTRefundReimbursementOnlyEventList))
                .append("\n");
        sb.append("    chargebackEventList: ")
                .append(toIndentedString(chargebackEventList))
                .append("\n");
        sb.append("    payWithAmazonEventList: ")
                .append(toIndentedString(payWithAmazonEventList))
                .append("\n");
        sb.append("    serviceProviderCreditEventList: ")
                .append(toIndentedString(serviceProviderCreditEventList))
                .append("\n");
        sb.append("    retrochargeEventList: ")
                .append(toIndentedString(retrochargeEventList))
                .append("\n");
        sb.append("    rentalTransactionEventList: ")
                .append(toIndentedString(rentalTransactionEventList))
                .append("\n");
        sb.append("    productAdsPaymentEventList: ")
                .append(toIndentedString(productAdsPaymentEventList))
                .append("\n");
        sb.append("    serviceFeeEventList: ")
                .append(toIndentedString(serviceFeeEventList))
                .append("\n");
        sb.append("    sellerDealPaymentEventList: ")
                .append(toIndentedString(sellerDealPaymentEventList))
                .append("\n");
        sb.append("    debtRecoveryEventList: ")
                .append(toIndentedString(debtRecoveryEventList))
                .append("\n");
        sb.append("    loanServicingEventList: ")
                .append(toIndentedString(loanServicingEventList))
                .append("\n");
        sb.append("    adjustmentEventList: ")
                .append(toIndentedString(adjustmentEventList))
                .append("\n");
        sb.append("    saFETReimbursementEventList: ")
                .append(toIndentedString(saFETReimbursementEventList))
                .append("\n");
        sb.append("    sellerReviewEnrollmentPaymentEventList: ")
                .append(toIndentedString(sellerReviewEnrollmentPaymentEventList))
                .append("\n");
        sb.append("    fbALiquidationEventList: ")
                .append(toIndentedString(fbALiquidationEventList))
                .append("\n");
        sb.append("    couponPaymentEventList: ")
                .append(toIndentedString(couponPaymentEventList))
                .append("\n");
        sb.append("    imagingServicesFeeEventList: ")
                .append(toIndentedString(imagingServicesFeeEventList))
                .append("\n");
        sb.append("    networkComminglingTransactionEventList: ")
                .append(toIndentedString(networkComminglingTransactionEventList))
                .append("\n");
        sb.append("    affordabilityExpenseEventList: ")
                .append(toIndentedString(affordabilityExpenseEventList))
                .append("\n");
        sb.append("    affordabilityExpenseReversalEventList: ")
                .append(toIndentedString(affordabilityExpenseReversalEventList))
                .append("\n");
        sb.append("    removalShipmentEventList: ")
                .append(toIndentedString(removalShipmentEventList))
                .append("\n");
        sb.append("    removalShipmentAdjustmentEventList: ")
                .append(toIndentedString(removalShipmentAdjustmentEventList))
                .append("\n");
        sb.append("    trialShipmentEventList: ")
                .append(toIndentedString(trialShipmentEventList))
                .append("\n");
        sb.append("    tdSReimbursementEventList: ")
                .append(toIndentedString(tdSReimbursementEventList))
                .append("\n");
        sb.append("    adhocDisbursementEventList: ")
                .append(toIndentedString(adhocDisbursementEventList))
                .append("\n");
        sb.append("    taxWithholdingEventList: ")
                .append(toIndentedString(taxWithholdingEventList))
                .append("\n");
        sb.append("    chargeRefundEventList: ")
                .append(toIndentedString(chargeRefundEventList))
                .append("\n");
        sb.append("    failedAdhocDisbursementEventList: ")
                .append(toIndentedString(failedAdhocDisbursementEventList))
                .append("\n");
        sb.append("    valueAddedServiceChargeEventList: ")
                .append(toIndentedString(valueAddedServiceChargeEventList))
                .append("\n");
        sb.append("    capacityReservationBillingEventList: ")
                .append(toIndentedString(capacityReservationBillingEventList))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /** Convert the given object to string with each line indented by 4 spaces (except the first line). */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("ShipmentEventList");
        openapiFields.add("ShipmentSettleEventList");
        openapiFields.add("RefundEventList");
        openapiFields.add("GuaranteeClaimEventList");
        openapiFields.add("EBTRefundReimbursementOnlyEventList");
        openapiFields.add("ChargebackEventList");
        openapiFields.add("PayWithAmazonEventList");
        openapiFields.add("ServiceProviderCreditEventList");
        openapiFields.add("RetrochargeEventList");
        openapiFields.add("RentalTransactionEventList");
        openapiFields.add("ProductAdsPaymentEventList");
        openapiFields.add("ServiceFeeEventList");
        openapiFields.add("SellerDealPaymentEventList");
        openapiFields.add("DebtRecoveryEventList");
        openapiFields.add("LoanServicingEventList");
        openapiFields.add("AdjustmentEventList");
        openapiFields.add("SAFETReimbursementEventList");
        openapiFields.add("SellerReviewEnrollmentPaymentEventList");
        openapiFields.add("FBALiquidationEventList");
        openapiFields.add("CouponPaymentEventList");
        openapiFields.add("ImagingServicesFeeEventList");
        openapiFields.add("NetworkComminglingTransactionEventList");
        openapiFields.add("AffordabilityExpenseEventList");
        openapiFields.add("AffordabilityExpenseReversalEventList");
        openapiFields.add("RemovalShipmentEventList");
        openapiFields.add("RemovalShipmentAdjustmentEventList");
        openapiFields.add("TrialShipmentEventList");
        openapiFields.add("TDSReimbursementEventList");
        openapiFields.add("AdhocDisbursementEventList");
        openapiFields.add("TaxWithholdingEventList");
        openapiFields.add("ChargeRefundEventList");
        openapiFields.add("FailedAdhocDisbursementEventList");
        openapiFields.add("ValueAddedServiceChargeEventList");
        openapiFields.add("CapacityReservationBillingEventList");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to FinancialEvents
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!FinancialEvents.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in FinancialEvents is not found in the empty JSON string",
                        FinancialEvents.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries =
                jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!FinancialEvents.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(
                        "The field `%s` in the JSON string is not defined in the `FinancialEvents` properties. JSON: %s",
                        entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!FinancialEvents.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'FinancialEvents' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<FinancialEvents> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(FinancialEvents.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<FinancialEvents>() {
                        @Override
                        public void write(JsonWriter out, FinancialEvents value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public FinancialEvents read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of FinancialEvents given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of FinancialEvents
     * @throws IOException if the JSON string is invalid with respect to FinancialEvents
     */
    public static FinancialEvents fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, FinancialEvents.class);
    }

    /**
     * Convert an instance of FinancialEvents to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
