/*
 * Selling Partner API for Replenishment
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * The version of the OpenAPI document: 2022-11-07
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.replenishment.v2022_11_07;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import software.amazon.spapi.JSON;

/** An object which contains the projected subscriber demand for the offer over different time horizons. */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.9.0")
public class ForecastDeliveries {
    public static final String SERIALIZED_NAME_NEXT15_DAYS_DELIVERIES = "next15DaysDeliveries";

    @SerializedName(SERIALIZED_NAME_NEXT15_DAYS_DELIVERIES)
    private Long next15DaysDeliveries;

    public static final String SERIALIZED_NAME_NEXT30_DAYS_DELIVERIES = "next30DaysDeliveries";

    @SerializedName(SERIALIZED_NAME_NEXT30_DAYS_DELIVERIES)
    private Long next30DaysDeliveries;

    public static final String SERIALIZED_NAME_NEXT60_DAYS_DELIVERIES = "next60DaysDeliveries";

    @SerializedName(SERIALIZED_NAME_NEXT60_DAYS_DELIVERIES)
    private Long next60DaysDeliveries;

    public static final String SERIALIZED_NAME_NEXT90_DAYS_DELIVERIES = "next90DaysDeliveries";

    @SerializedName(SERIALIZED_NAME_NEXT90_DAYS_DELIVERIES)
    private Long next90DaysDeliveries;

    public ForecastDeliveries() {}

    public ForecastDeliveries next15DaysDeliveries(Long next15DaysDeliveries) {
        this.next15DaysDeliveries = next15DaysDeliveries;
        return this;
    }

    /**
     * The projected number of subscriber deliveries in the next 15 days. minimum: 0
     *
     * @return next15DaysDeliveries
     */
    @javax.annotation.Nullable public Long getNext15DaysDeliveries() {
        return next15DaysDeliveries;
    }

    public void setNext15DaysDeliveries(Long next15DaysDeliveries) {
        this.next15DaysDeliveries = next15DaysDeliveries;
    }

    public ForecastDeliveries next30DaysDeliveries(Long next30DaysDeliveries) {
        this.next30DaysDeliveries = next30DaysDeliveries;
        return this;
    }

    /**
     * The projected number of subscriber deliveries in the next 30 days. minimum: 0
     *
     * @return next30DaysDeliveries
     */
    @javax.annotation.Nullable public Long getNext30DaysDeliveries() {
        return next30DaysDeliveries;
    }

    public void setNext30DaysDeliveries(Long next30DaysDeliveries) {
        this.next30DaysDeliveries = next30DaysDeliveries;
    }

    public ForecastDeliveries next60DaysDeliveries(Long next60DaysDeliveries) {
        this.next60DaysDeliveries = next60DaysDeliveries;
        return this;
    }

    /**
     * The projected number of subscriber deliveries in the next 60 days. minimum: 0
     *
     * @return next60DaysDeliveries
     */
    @javax.annotation.Nullable public Long getNext60DaysDeliveries() {
        return next60DaysDeliveries;
    }

    public void setNext60DaysDeliveries(Long next60DaysDeliveries) {
        this.next60DaysDeliveries = next60DaysDeliveries;
    }

    public ForecastDeliveries next90DaysDeliveries(Long next90DaysDeliveries) {
        this.next90DaysDeliveries = next90DaysDeliveries;
        return this;
    }

    /**
     * The projected number of subscriber deliveries in the next 90 days. minimum: 0
     *
     * @return next90DaysDeliveries
     */
    @javax.annotation.Nullable public Long getNext90DaysDeliveries() {
        return next90DaysDeliveries;
    }

    public void setNext90DaysDeliveries(Long next90DaysDeliveries) {
        this.next90DaysDeliveries = next90DaysDeliveries;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ForecastDeliveries forecastDeliveries = (ForecastDeliveries) o;
        return Objects.equals(this.next15DaysDeliveries, forecastDeliveries.next15DaysDeliveries)
                && Objects.equals(this.next30DaysDeliveries, forecastDeliveries.next30DaysDeliveries)
                && Objects.equals(this.next60DaysDeliveries, forecastDeliveries.next60DaysDeliveries)
                && Objects.equals(this.next90DaysDeliveries, forecastDeliveries.next90DaysDeliveries);
    }

    @Override
    public int hashCode() {
        return Objects.hash(next15DaysDeliveries, next30DaysDeliveries, next60DaysDeliveries, next90DaysDeliveries);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ForecastDeliveries {\n");
        sb.append("    next15DaysDeliveries: ")
                .append(toIndentedString(next15DaysDeliveries))
                .append("\n");
        sb.append("    next30DaysDeliveries: ")
                .append(toIndentedString(next30DaysDeliveries))
                .append("\n");
        sb.append("    next60DaysDeliveries: ")
                .append(toIndentedString(next60DaysDeliveries))
                .append("\n");
        sb.append("    next90DaysDeliveries: ")
                .append(toIndentedString(next90DaysDeliveries))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /** Convert the given object to string with each line indented by 4 spaces (except the first line). */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("next15DaysDeliveries");
        openapiFields.add("next30DaysDeliveries");
        openapiFields.add("next60DaysDeliveries");
        openapiFields.add("next90DaysDeliveries");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ForecastDeliveries
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ForecastDeliveries.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in ForecastDeliveries is not found in the empty JSON string",
                        ForecastDeliveries.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries =
                jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ForecastDeliveries.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(
                        "The field `%s` in the JSON string is not defined in the `ForecastDeliveries` properties. JSON: %s",
                        entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ForecastDeliveries.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ForecastDeliveries' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ForecastDeliveries> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(ForecastDeliveries.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<ForecastDeliveries>() {
                        @Override
                        public void write(JsonWriter out, ForecastDeliveries value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public ForecastDeliveries read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of ForecastDeliveries given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ForecastDeliveries
     * @throws IOException if the JSON string is invalid with respect to ForecastDeliveries
     */
    public static ForecastDeliveries fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ForecastDeliveries.class);
    }

    /**
     * Convert an instance of ForecastDeliveries to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
