/*
 * Selling Partner API for Replenishment
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * The version of the OpenAPI document: 2022-11-07
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.replenishment.v2022_11_07;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/** The metric name and description. */
@JsonAdapter(Metric.Adapter.class)
public enum Metric {
    SHIPPED_SUBSCRIPTION_UNITS("SHIPPED_SUBSCRIPTION_UNITS"),

    TOTAL_SUBSCRIPTIONS_REVENUE("TOTAL_SUBSCRIPTIONS_REVENUE"),

    ACTIVE_SUBSCRIPTIONS("ACTIVE_SUBSCRIPTIONS"),

    NOT_DELIVERED_DUE_TO_OOS("NOT_DELIVERED_DUE_TO_OOS"),

    SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE("SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REVENUE"),

    LOST_REVENUE_DUE_TO_OOS("LOST_REVENUE_DUE_TO_OOS"),

    SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REORDERS("SUBSCRIBER_NON_SUBSCRIBER_AVERAGE_REORDERS"),

    COUPONS_REVENUE_PENETRATION("COUPONS_REVENUE_PENETRATION"),

    REVENUE_BY_DELIVERIES("REVENUE_BY_DELIVERIES"),

    SUBSCRIBER_RETENTION("SUBSCRIBER_RETENTION"),

    REVENUE_PENETRATION_BY_SELLER_FUNDING("REVENUE_PENETRATION_BY_SELLER_FUNDING"),

    SHARE_OF_COUPON_SUBSCRIPTIONS("SHARE_OF_COUPON_SUBSCRIPTIONS"),

    SUBSCRIBER_LIFETIME_VALUE_BY_CUSTOMER_SEGMENT("SUBSCRIBER_LIFETIME_VALUE_BY_CUSTOMER_SEGMENT"),

    SIGNUP_CONVERSION_BY_SELLER_FUNDING("SIGNUP_CONVERSION_BY_SELLER_FUNDING"),

    REVENUE_PENETRATION("REVENUE_PENETRATION");

    private String value;

    Metric(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static Metric fromValue(String value) {
        for (Metric b : Metric.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<Metric> {
        @Override
        public void write(final JsonWriter jsonWriter, final Metric enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public Metric read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return Metric.fromValue(value);
        }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        String value = jsonElement.getAsString();
        Metric.fromValue(value);
    }
}
