/**
 * Selling Partner API for Product Fees
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
import { MoneyType } from './MoneyType.js';
/**
 * The PriceToEstimateFees model module.
 * @module productfees_v0/model/PriceToEstimateFees
 * @version v0
 */
export declare class PriceToEstimateFees {
    listingPrice: MoneyType;
    /**
     * Constructs a new <code>PriceToEstimateFees</code>.
     * Price information for an item, used to estimate fees.
     * @alias module:productfees_v0/model/PriceToEstimateFees
     * @class
     * @param listingPrice {MoneyType}
     */
    constructor(listingPrice: MoneyType);
    /**
     * Constructs a <code>PriceToEstimateFees</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {PriceToEstimateFees} obj Optional instance to populate.
     * @return {PriceToEstimateFees} The populated <code>PriceToEstimateFees</code> instance.
     */
    static constructFromObject(data: Object, obj: PriceToEstimateFees): PriceToEstimateFees;
}
//# sourceMappingURL=PriceToEstimateFees.d.ts.map