/*
 * The Selling Partner API for Promotions
 * The Selling Partner API for Promotions enables selling partners to create and manage promotions.
 *
 * The version of the OpenAPI document: 2025-12-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.api.promotions.v2025_12_01;

import static org.junit.jupiter.api.Assertions.*;

import com.amazon.SellingPartnerAPIAA.LWAAuthorizationCredentials;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse.BodyHandlers;
import java.util.*;
import java.util.stream.Collectors;
import org.jeasy.random.EasyRandom;
import org.jeasy.random.EasyRandomParameters;
import org.junit.jupiter.api.Test;
import software.amazon.spapi.ApiResponse;
import software.amazon.spapi.models.productfees.v0.GetMyFeesEstimatesRequest;
import software.amazon.spapi.models.promotions.v2025_12_01.GetPromotionResponse;
import software.amazon.spapi.models.promotions.v2025_12_01.GetSelectionResponse;
import software.amazon.spapi.models.promotions.v2025_12_01.SearchPromotionsResponse;

public class PromotionsApiTest {

    private static final String endpoint = "http://localhost:3000";
    private static final String authEndpoint = "http://localhost:3000/auth/o2/token";
    private static final LWAAuthorizationCredentials credentials = LWAAuthorizationCredentials.builder()
            .clientId("clientId")
            .clientSecret("clientSecret")
            .refreshToken("refreshToken")
            .endpoint(authEndpoint)
            .build();

    private final PromotionsApi api = new PromotionsApi.Builder()
            .lwaAuthorizationCredentials(credentials)
            .endpoint(endpoint)
            .build();

    private final EasyRandom easyRandom = new EasyRandom(new EasyRandomParameters()
            .collectionSizeRange(1, 2)
            .randomizationDepth(10)
            .randomize(GetMyFeesEstimatesRequest.class, GetMyFeesEstimatesRequest::new));

    @Test
    public void getPromotionTest() throws Exception {
        instructBackendMock("promotions", "getPromotion", "200");

        String promotionId = easyRandom.nextObject(String.class);

        ApiResponse<GetPromotionResponse> response = api.getPromotionWithHttpInfo(promotionId, null, null);

        assertEquals(200, response.getStatusCode());
        assertValidResponsePayload(200, response.getData());
    }

    @Test
    public void getSelectionTest() throws Exception {
        instructBackendMock("promotions", "getSelection", "200");

        String promotionId = easyRandom.nextObject(String.class);

        String selectionId = easyRandom.nextObject(String.class);

        Integer revisionId = easyRandom.nextObject(Integer.class);

        ApiResponse<GetSelectionResponse> response =
                api.getSelectionWithHttpInfo(promotionId, selectionId, revisionId, null, null, null, null);

        assertEquals(200, response.getStatusCode());
        assertValidResponsePayload(200, response.getData());
    }

    @Test
    public void searchPromotionsTest() throws Exception {
        instructBackendMock("promotions", "searchPromotions", "200");

        List<String> marketplaceIds = easyRandom.objects(String.class, 2).collect(Collectors.toList());

        ApiResponse<SearchPromotionsResponse> response = api.searchPromotionsWithHttpInfo(
                marketplaceIds,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);

        assertEquals(200, response.getStatusCode());
        assertValidResponsePayload(200, response.getData());
    }

    private void instructBackendMock(String basename, String operationId, String code) throws Exception {
        String lowerCaseCompressedBasename = basename.replaceAll("/\"W| ", "").toLowerCase();
        String cleanOperationId = operationId.replaceAll("_\\d+$", "");
        HttpRequest request = HttpRequest.newBuilder()
                .uri(new URI(endpoint + "/response/" + lowerCaseCompressedBasename + "-" + cleanOperationId + "/code/"
                        + code))
                .POST(HttpRequest.BodyPublishers.noBody())
                .build();

        HttpClient.newHttpClient().send(request, BodyHandlers.discarding());
    }

    private static void assertValidResponsePayload(int statusCode, Object body) {
        if (statusCode != 204) assertNotNull(body);
    }
}
