/**
 * Selling Partner API for Fulfillment Inbound
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
export type PrepOwner = 'AMAZON' | 'SELLER';
/**
 * @typedef {'AMAZON'|'SELLER'} PrepOwner
 */
export declare const PrepOwner: (() => void) & {
    AMAZON: string;
    SELLER: string;
    constructFromObject: (object: any) => any;
};
//# sourceMappingURL=PrepOwner.d.ts.map