# coding: utf-8

"""
    Selling Partner API for A+ Content Management

    With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ Content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.

    The version of the OpenAPI document: 2020-11-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import pprint
import re  # noqa: F401

import six

from spapi.configuration import Configuration


class UpdateMediaRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'descriptions': 'List[Description]',
    }

    attribute_map = {
        'title': 'title',
        'descriptions': 'descriptions',
    }

    def __init__(self, title=None, descriptions=None, _configuration=None):  # noqa: E501
        """UpdateMediaRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._title = None
        self._descriptions = None
        self.discriminator = None

        if title is not None:
            self.title = title
        if descriptions is not None:
            self.descriptions = descriptions

    @property
    def title(self):
        """Gets the title of this UpdateMediaRequest.  # noqa: E501

        The updated title. When `associatedMediaId` query parameter is provided, updates the pairing title (minimum 3 words). When absent and `mediaId` is an image, updates the image title.  # noqa: E501

        :return: The title of this UpdateMediaRequest.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this UpdateMediaRequest.

        The updated title. When `associatedMediaId` query parameter is provided, updates the pairing title (minimum 3 words). When absent and `mediaId` is an image, updates the image title.  # noqa: E501

        :param title: The title of this UpdateMediaRequest.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def descriptions(self):
        """Gets the descriptions of this UpdateMediaRequest.  # noqa: E501

        A list of locale-keyed accessibility descriptions. At least one entry is required for video assets.  # noqa: E501

        :return: The descriptions of this UpdateMediaRequest.  # noqa: E501
        :rtype: List[Description]
        """
        return self._descriptions

    @descriptions.setter
    def descriptions(self, descriptions):
        """Sets the descriptions of this UpdateMediaRequest.

        A list of locale-keyed accessibility descriptions. At least one entry is required for video assets.  # noqa: E501

        :param descriptions: The descriptions of this UpdateMediaRequest.  # noqa: E501
        :type: List[Description]
        """

        self._descriptions = descriptions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateMediaRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateMediaRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateMediaRequest):
            return True

        return self.to_dict() != other.to_dict()
