export type AsinBadge = "BRAND_NOT_ELIGIBLE" | "CATALOG_NOT_FOUND" | "CONTENT_NOT_PUBLISHED" | "CONTENT_PUBLISHED";
/**
 * @typedef {'BRAND_NOT_ELIGIBLE'|'CATALOG_NOT_FOUND'|'CONTENT_NOT_PUBLISHED'|'CONTENT_PUBLISHED'} AsinBadge
 */
export const AsinBadge: Readonly<{
    BRAND_NOT_ELIGIBLE: "BRAND_NOT_ELIGIBLE";
    CATALOG_NOT_FOUND: "CATALOG_NOT_FOUND";
    CONTENT_NOT_PUBLISHED: "CONTENT_NOT_PUBLISHED";
    CONTENT_PUBLISHED: "CONTENT_PUBLISHED";
}>;
//# sourceMappingURL=AsinBadge.d.ts.map