export type ContentModuleType = "STANDARD_COMPANY_LOGO" | "STANDARD_COMPARISON_TABLE" | "STANDARD_FOUR_IMAGE_TEXT" | "STANDARD_FOUR_IMAGE_TEXT_QUADRANT" | "STANDARD_HEADER_IMAGE_TEXT" | "STANDARD_IMAGE_SIDEBAR" | "STANDARD_IMAGE_TEXT_OVERLAY" | "STANDARD_MULTIPLE_IMAGE_TEXT" | "STANDARD_PRODUCT_DESCRIPTION" | "STANDARD_SINGLE_IMAGE_HIGHLIGHTS" | "STANDARD_SINGLE_IMAGE_SPECS_DETAIL" | "STANDARD_SINGLE_SIDE_IMAGE" | "STANDARD_TECH_SPECS" | "STANDARD_TEXT" | "STANDARD_THREE_IMAGE_TEXT";
/**
 * @typedef {'STANDARD_COMPANY_LOGO'|'STANDARD_COMPARISON_TABLE'|'STANDARD_FOUR_IMAGE_TEXT'|'STANDARD_FOUR_IMAGE_TEXT_QUADRANT'|'STANDARD_HEADER_IMAGE_TEXT'|'STANDARD_IMAGE_SIDEBAR'|'STANDARD_IMAGE_TEXT_OVERLAY'|'STANDARD_MULTIPLE_IMAGE_TEXT'|'STANDARD_PRODUCT_DESCRIPTION'|'STANDARD_SINGLE_IMAGE_HIGHLIGHTS'|'STANDARD_SINGLE_IMAGE_SPECS_DETAIL'|'STANDARD_SINGLE_SIDE_IMAGE'|'STANDARD_TECH_SPECS'|'STANDARD_TEXT'|'STANDARD_THREE_IMAGE_TEXT'} ContentModuleType
 */
export const ContentModuleType: (() => void) & {
    STANDARD_COMPANY_LOGO: string;
    STANDARD_COMPARISON_TABLE: string;
    STANDARD_FOUR_IMAGE_TEXT: string;
    STANDARD_FOUR_IMAGE_TEXT_QUADRANT: string;
    STANDARD_HEADER_IMAGE_TEXT: string;
    STANDARD_IMAGE_SIDEBAR: string;
    STANDARD_IMAGE_TEXT_OVERLAY: string;
    STANDARD_MULTIPLE_IMAGE_TEXT: string;
    STANDARD_PRODUCT_DESCRIPTION: string;
    STANDARD_SINGLE_IMAGE_HIGHLIGHTS: string;
    STANDARD_SINGLE_IMAGE_SPECS_DETAIL: string;
    STANDARD_SINGLE_SIDE_IMAGE: string;
    STANDARD_TECH_SPECS: string;
    STANDARD_TEXT: string;
    STANDARD_THREE_IMAGE_TEXT: string;
    constructFromObject: (object: any) => any;
};
//# sourceMappingURL=ContentModuleType.d.ts.map