export type DecoratorType = "LIST_ITEM" | "LIST_ORDERED" | "LIST_UNORDERED" | "STYLE_BOLD" | "STYLE_ITALIC" | "STYLE_LINEBREAK" | "STYLE_PARAGRAPH" | "STYLE_UNDERLINE";
/**
 * @typedef {'LIST_ITEM'|'LIST_ORDERED'|'LIST_UNORDERED'|'STYLE_BOLD'|'STYLE_ITALIC'|'STYLE_LINEBREAK'|'STYLE_PARAGRAPH'|'STYLE_UNDERLINE'} DecoratorType
 */
export const DecoratorType: Readonly<{
    LIST_ITEM: "LIST_ITEM";
    LIST_ORDERED: "LIST_ORDERED";
    LIST_UNORDERED: "LIST_UNORDERED";
    STYLE_BOLD: "STYLE_BOLD";
    STYLE_ITALIC: "STYLE_ITALIC";
    STYLE_LINEBREAK: "STYLE_LINEBREAK";
    STYLE_PARAGRAPH: "STYLE_PARAGRAPH";
    STYLE_UNDERLINE: "STYLE_UNDERLINE";
}>;
//# sourceMappingURL=DecoratorType.d.ts.map