/*
 * The Selling Partner API for Orders
 * The Selling Partner API for Orders returns orders information. This API supports the following types of orders:  - FBM (Fulfilled by Merchant) - FBA (Fulfilled by Amazon) - read only - Amazon Fresh  This API does not display order data that is more than two years old, except in the JP, AU, and SG marketplaces, for which data from 2016 and after is available.
 *
 * The version of the OpenAPI document: 2026-01-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.orders.v2026_01_01;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import software.amazon.spapi.JSON;

/**
 * Information about a physical shipping package, including tracking details. **Note:** Only available for
 * merchant-fulfilled (FBM) orders.
 */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.9.0")
public class OrderPackage {
    public static final String SERIALIZED_NAME_PACKAGE_REFERENCE_ID = "packageReferenceId";

    @SerializedName(SERIALIZED_NAME_PACKAGE_REFERENCE_ID)
    private String packageReferenceId;

    public static final String SERIALIZED_NAME_CREATED_TIME = "createdTime";

    @SerializedName(SERIALIZED_NAME_CREATED_TIME)
    private OffsetDateTime createdTime;

    public static final String SERIALIZED_NAME_PACKAGE_STATUS = "packageStatus";

    @SerializedName(SERIALIZED_NAME_PACKAGE_STATUS)
    private PackageStatus packageStatus;

    public static final String SERIALIZED_NAME_CARRIER = "carrier";

    @SerializedName(SERIALIZED_NAME_CARRIER)
    private String carrier;

    public static final String SERIALIZED_NAME_SHIP_TIME = "shipTime";

    @SerializedName(SERIALIZED_NAME_SHIP_TIME)
    private OffsetDateTime shipTime;

    public static final String SERIALIZED_NAME_SHIPPING_SERVICE = "shippingService";

    @SerializedName(SERIALIZED_NAME_SHIPPING_SERVICE)
    private String shippingService;

    public static final String SERIALIZED_NAME_TRACKING_NUMBER = "trackingNumber";

    @SerializedName(SERIALIZED_NAME_TRACKING_NUMBER)
    private String trackingNumber;

    public static final String SERIALIZED_NAME_SHIP_FROM_ADDRESS = "shipFromAddress";

    @SerializedName(SERIALIZED_NAME_SHIP_FROM_ADDRESS)
    private MerchantAddress shipFromAddress;

    public static final String SERIALIZED_NAME_PACKAGE_ITEMS = "packageItems";

    @SerializedName(SERIALIZED_NAME_PACKAGE_ITEMS)
    private List<PackageItem> packageItems = new ArrayList<>();

    public OrderPackage() {}

    public OrderPackage packageReferenceId(String packageReferenceId) {
        this.packageReferenceId = packageReferenceId;
        return this;
    }

    /**
     * A unique identifier for this package within the context of the order.
     *
     * @return packageReferenceId
     */
    @javax.annotation.Nonnull
    public String getPackageReferenceId() {
        return packageReferenceId;
    }

    public void setPackageReferenceId(String packageReferenceId) {
        this.packageReferenceId = packageReferenceId;
    }

    public OrderPackage createdTime(OffsetDateTime createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * The exact time when this shipping package was created and prepared for shipment. In [ISO
     * 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     *
     * @return createdTime
     */
    @javax.annotation.Nullable public OffsetDateTime getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(OffsetDateTime createdTime) {
        this.createdTime = createdTime;
    }

    public OrderPackage packageStatus(PackageStatus packageStatus) {
        this.packageStatus = packageStatus;
        return this;
    }

    /**
     * Get packageStatus
     *
     * @return packageStatus
     */
    @javax.annotation.Nullable public PackageStatus getPackageStatus() {
        return packageStatus;
    }

    public void setPackageStatus(PackageStatus packageStatus) {
        this.packageStatus = packageStatus;
    }

    public OrderPackage carrier(String carrier) {
        this.carrier = carrier;
        return this;
    }

    /**
     * The carrier responsible for transporting this package to the customer.
     *
     * @return carrier
     */
    @javax.annotation.Nullable public String getCarrier() {
        return carrier;
    }

    public void setCarrier(String carrier) {
        this.carrier = carrier;
    }

    public OrderPackage shipTime(OffsetDateTime shipTime) {
        this.shipTime = shipTime;
        return this;
    }

    /**
     * The exact time when this package was handed over to the carrier and began its journey to the customer. In [ISO
     * 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) format.
     *
     * @return shipTime
     */
    @javax.annotation.Nullable public OffsetDateTime getShipTime() {
        return shipTime;
    }

    public void setShipTime(OffsetDateTime shipTime) {
        this.shipTime = shipTime;
    }

    public OrderPackage shippingService(String shippingService) {
        this.shippingService = shippingService;
        return this;
    }

    /**
     * The specific shipping method or service used for delivering this package.
     *
     * @return shippingService
     */
    @javax.annotation.Nullable public String getShippingService() {
        return shippingService;
    }

    public void setShippingService(String shippingService) {
        this.shippingService = shippingService;
    }

    public OrderPackage trackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber;
        return this;
    }

    /**
     * The carrier-provided tracking number that customers can use to monitor the package&#39;s delivery progress.
     *
     * @return trackingNumber
     */
    @javax.annotation.Nullable public String getTrackingNumber() {
        return trackingNumber;
    }

    public void setTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber;
    }

    public OrderPackage shipFromAddress(MerchantAddress shipFromAddress) {
        this.shipFromAddress = shipFromAddress;
        return this;
    }

    /**
     * Get shipFromAddress
     *
     * @return shipFromAddress
     */
    @javax.annotation.Nullable public MerchantAddress getShipFromAddress() {
        return shipFromAddress;
    }

    public void setShipFromAddress(MerchantAddress shipFromAddress) {
        this.shipFromAddress = shipFromAddress;
    }

    public OrderPackage packageItems(List<PackageItem> packageItems) {
        this.packageItems = packageItems;
        return this;
    }

    public OrderPackage addPackageItemsItem(PackageItem packageItemsItem) {
        if (this.packageItems == null) {
            this.packageItems = new ArrayList<>();
        }
        this.packageItems.add(packageItemsItem);
        return this;
    }

    /**
     * A list of all order items included in this specific package.
     *
     * @return packageItems
     */
    @javax.annotation.Nullable public List<PackageItem> getPackageItems() {
        return packageItems;
    }

    public void setPackageItems(List<PackageItem> packageItems) {
        this.packageItems = packageItems;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderPackage orderPackage = (OrderPackage) o;
        return Objects.equals(this.packageReferenceId, orderPackage.packageReferenceId)
                && Objects.equals(this.createdTime, orderPackage.createdTime)
                && Objects.equals(this.packageStatus, orderPackage.packageStatus)
                && Objects.equals(this.carrier, orderPackage.carrier)
                && Objects.equals(this.shipTime, orderPackage.shipTime)
                && Objects.equals(this.shippingService, orderPackage.shippingService)
                && Objects.equals(this.trackingNumber, orderPackage.trackingNumber)
                && Objects.equals(this.shipFromAddress, orderPackage.shipFromAddress)
                && Objects.equals(this.packageItems, orderPackage.packageItems);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                packageReferenceId,
                createdTime,
                packageStatus,
                carrier,
                shipTime,
                shippingService,
                trackingNumber,
                shipFromAddress,
                packageItems);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderPackage {\n");
        sb.append("    packageReferenceId: ")
                .append(toIndentedString(packageReferenceId))
                .append("\n");
        sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
        sb.append("    packageStatus: ").append(toIndentedString(packageStatus)).append("\n");
        sb.append("    carrier: ").append(toIndentedString(carrier)).append("\n");
        sb.append("    shipTime: ").append(toIndentedString(shipTime)).append("\n");
        sb.append("    shippingService: ")
                .append(toIndentedString(shippingService))
                .append("\n");
        sb.append("    trackingNumber: ")
                .append(toIndentedString(trackingNumber))
                .append("\n");
        sb.append("    shipFromAddress: ")
                .append(toIndentedString(shipFromAddress))
                .append("\n");
        sb.append("    packageItems: ").append(toIndentedString(packageItems)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /** Convert the given object to string with each line indented by 4 spaces (except the first line). */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("packageReferenceId");
        openapiFields.add("createdTime");
        openapiFields.add("packageStatus");
        openapiFields.add("carrier");
        openapiFields.add("shipTime");
        openapiFields.add("shippingService");
        openapiFields.add("trackingNumber");
        openapiFields.add("shipFromAddress");
        openapiFields.add("packageItems");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("packageReferenceId");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to OrderPackage
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!OrderPackage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in OrderPackage is not found in the empty JSON string",
                        OrderPackage.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries =
                jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!OrderPackage.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(
                        "The field `%s` in the JSON string is not defined in the `OrderPackage` properties. JSON: %s",
                        entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : OrderPackage.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s",
                        requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("packageReferenceId").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `packageReferenceId` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("packageReferenceId").toString()));
        }
        // validate the optional field `packageStatus`
        if (jsonObj.get("packageStatus") != null
                && !jsonObj.get("packageStatus").isJsonNull()) {
            PackageStatus.validateJsonElement(jsonObj.get("packageStatus"));
        }
        if ((jsonObj.get("carrier") != null && !jsonObj.get("carrier").isJsonNull())
                && !jsonObj.get("carrier").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `carrier` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("carrier").toString()));
        }
        if ((jsonObj.get("shippingService") != null
                        && !jsonObj.get("shippingService").isJsonNull())
                && !jsonObj.get("shippingService").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `shippingService` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("shippingService").toString()));
        }
        if ((jsonObj.get("trackingNumber") != null
                        && !jsonObj.get("trackingNumber").isJsonNull())
                && !jsonObj.get("trackingNumber").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `trackingNumber` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("trackingNumber").toString()));
        }
        // validate the optional field `shipFromAddress`
        if (jsonObj.get("shipFromAddress") != null
                && !jsonObj.get("shipFromAddress").isJsonNull()) {
            MerchantAddress.validateJsonElement(jsonObj.get("shipFromAddress"));
        }
        if (jsonObj.get("packageItems") != null && !jsonObj.get("packageItems").isJsonNull()) {
            JsonArray jsonArraypackageItems = jsonObj.getAsJsonArray("packageItems");
            if (jsonArraypackageItems != null) {
                // ensure the json data is an array
                if (!jsonObj.get("packageItems").isJsonArray()) {
                    throw new IllegalArgumentException(String.format(
                            "Expected the field `packageItems` to be an array in the JSON string but got `%s`",
                            jsonObj.get("packageItems").toString()));
                }

                // validate the optional field `packageItems` (array)
                for (int i = 0; i < jsonArraypackageItems.size(); i++) {
                    PackageItem.validateJsonElement(jsonArraypackageItems.get(i));
                }
                ;
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!OrderPackage.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'OrderPackage' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<OrderPackage> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(OrderPackage.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<OrderPackage>() {
                        @Override
                        public void write(JsonWriter out, OrderPackage value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public OrderPackage read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of OrderPackage given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of OrderPackage
     * @throws IOException if the JSON string is invalid with respect to OrderPackage
     */
    public static OrderPackage fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, OrderPackage.class);
    }

    /**
     * Convert an instance of OrderPackage to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
