/**
 * The Selling Partner API for Promotions
 * The Selling Partner API for Promotions enables selling partners to create and manage promotions.
 *
 * The version of the OpenAPI document: 2025-12-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'

/**
 * The Schedule model module.
 * @module promotions_v2025_12_01/model/Schedule
 * @version 2025-12-01
 */
export class Schedule {
  /**
   * Constructs a new <code>Schedule</code>.
   * A promotion&#39;s start and end dates with optional event association.
   * @alias module:promotions_v2025_12_01/model/Schedule
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>Schedule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {Schedule} obj Optional instance to populate.
   * @return {Schedule} The populated <code>Schedule</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new Schedule()
      if (data.hasOwnProperty('startDate')) { obj.startDate = ApiClient.convertToType(data.startDate, 'Date') }
      if (data.hasOwnProperty('endDate')) { obj.endDate = ApiClient.convertToType(data.endDate, 'Date') }
      if (data.hasOwnProperty('eventId')) { obj.eventId = ApiClient.convertToType(data.eventId, 'String') }
    }
    return obj
  }
}

/**
 * The promotion's start date and time. Formatted in ISO 8601 format, including the timezone. For example: `1970-01-01T00:00:00-07:00`.
 * @member {Date} startDate
 * @type {Date}
 */
Schedule.prototype.startDate = undefined

/**
 * The promotion's end date and time. Formatted in ISO 8601 format, including the timezone. For example: `1970-01-01T00:00:00-07:00`.
 * @member {Date} endDate
 * @type {Date}
 */
Schedule.prototype.endDate = undefined

/**
 * An event identifier that associates the promotion with a specific event. For event promotions, this field contains the event name when available (for example, `Prime Day`). For historic event promotions, this field may contain `EVENT` as a placeholder.
 * @member {String} eventId
 * @type {String}
 */
Schedule.prototype.eventId = undefined
