export type CapacityType = "SCHEDULED_CAPACITY" | "AVAILABLE_CAPACITY" | "ENCUMBERED_CAPACITY" | "RESERVED_CAPACITY";
/**
 * @typedef {'SCHEDULED_CAPACITY'|'AVAILABLE_CAPACITY'|'ENCUMBERED_CAPACITY'|'RESERVED_CAPACITY'} CapacityType
 */
export const CapacityType: Readonly<{
    SCHEDULED_CAPACITY: "SCHEDULED_CAPACITY";
    AVAILABLE_CAPACITY: "AVAILABLE_CAPACITY";
    ENCUMBERED_CAPACITY: "ENCUMBERED_CAPACITY";
    RESERVED_CAPACITY: "RESERVED_CAPACITY";
}>;
//# sourceMappingURL=CapacityType.d.ts.map