/**
 * Selling Partner API for Services
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The CreateReservationResponse model module.
 * @module services_v1/model/CreateReservationResponse
 * @version v1
 */
export declare class CreateReservationResponse {
    /**
     * Constructs a new <code>CreateReservationResponse</code>.
     * Response schema for the &#x60;createReservation&#x60; operation.
     * @alias module:services_v1/model/CreateReservationResponse
     * @class
     */
    constructor();
    /**
     * Constructs a <code>CreateReservationResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {CreateReservationResponse} obj Optional instance to populate.
     * @return {CreateReservationResponse} The populated <code>CreateReservationResponse</code> instance.
     */
    static constructFromObject(data: Object, obj: CreateReservationResponse): CreateReservationResponse;
}
//# sourceMappingURL=CreateReservationResponse.d.ts.map