/*
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon store products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-05-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package software.amazon.spapi.models.pricing.v2022_05_01;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import software.amazon.spapi.JSON;

/** A promotion applicable to the offer. */
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        comments = "Generator version: 7.9.0")
public class Promotion {
    public static final String SERIALIZED_NAME_PROMOTION_TYPE = "promotionType";

    @SerializedName(SERIALIZED_NAME_PROMOTION_TYPE)
    private String promotionType;

    public static final String SERIALIZED_NAME_PROMOTION_SAVINGS = "promotionSavings";

    @SerializedName(SERIALIZED_NAME_PROMOTION_SAVINGS)
    private PromotionSavings promotionSavings;

    public static final String SERIALIZED_NAME_PURCHASE_REQUIREMENTS = "purchaseRequirements";

    @SerializedName(SERIALIZED_NAME_PURCHASE_REQUIREMENTS)
    private PurchaseRequirements purchaseRequirements;

    public Promotion() {}

    public Promotion promotionType(String promotionType) {
        this.promotionType = promotionType;
        return this;
    }

    /**
     * Indicates the type of promotion based on the customer-facing experience. Possible values include: - COUPON: The
     * offer has a live coupon that customers can clip and apply at checkout. - DEAL: The offer has a live deal (for
     * example, Lightning Deal or Best Deal). Deals are time-limited, require meeting quality criteria, and
     * automatically apply a discount when the customer purchases the item. - BASKET_BUILDING: The offer has a
     * basket-building (multi-quantity) promotion where customers purchase multiple quantities of the same or different
     * qualifying items to receive a discount on eligible items. Promotions created in Seller Central -&gt; Advertising
     * -&gt; Manage Promotions fall into this category
     *
     * @return promotionType
     */
    @javax.annotation.Nonnull
    public String getPromotionType() {
        return promotionType;
    }

    public void setPromotionType(String promotionType) {
        this.promotionType = promotionType;
    }

    public Promotion promotionSavings(PromotionSavings promotionSavings) {
        this.promotionSavings = promotionSavings;
        return this;
    }

    /**
     * Get promotionSavings
     *
     * @return promotionSavings
     */
    @javax.annotation.Nonnull
    public PromotionSavings getPromotionSavings() {
        return promotionSavings;
    }

    public void setPromotionSavings(PromotionSavings promotionSavings) {
        this.promotionSavings = promotionSavings;
    }

    public Promotion purchaseRequirements(PurchaseRequirements purchaseRequirements) {
        this.purchaseRequirements = purchaseRequirements;
        return this;
    }

    /**
     * Get purchaseRequirements
     *
     * @return purchaseRequirements
     */
    @javax.annotation.Nullable public PurchaseRequirements getPurchaseRequirements() {
        return purchaseRequirements;
    }

    public void setPurchaseRequirements(PurchaseRequirements purchaseRequirements) {
        this.purchaseRequirements = purchaseRequirements;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Promotion promotion = (Promotion) o;
        return Objects.equals(this.promotionType, promotion.promotionType)
                && Objects.equals(this.promotionSavings, promotion.promotionSavings)
                && Objects.equals(this.purchaseRequirements, promotion.purchaseRequirements);
    }

    @Override
    public int hashCode() {
        return Objects.hash(promotionType, promotionSavings, purchaseRequirements);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Promotion {\n");
        sb.append("    promotionType: ").append(toIndentedString(promotionType)).append("\n");
        sb.append("    promotionSavings: ")
                .append(toIndentedString(promotionSavings))
                .append("\n");
        sb.append("    purchaseRequirements: ")
                .append(toIndentedString(purchaseRequirements))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /** Convert the given object to string with each line indented by 4 spaces (except the first line). */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("promotionType");
        openapiFields.add("promotionSavings");
        openapiFields.add("purchaseRequirements");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("promotionType");
        openapiRequiredFields.add("promotionSavings");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to Promotion
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!Promotion.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format(
                        "The required field(s) %s in Promotion is not found in the empty JSON string",
                        Promotion.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries =
                jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!Promotion.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format(
                        "The field `%s` in the JSON string is not defined in the `Promotion` properties. JSON: %s",
                        entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : Promotion.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(
                        "The required field `%s` is not found in the JSON string: %s",
                        requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("promotionType").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(
                    "Expected the field `promotionType` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("promotionType").toString()));
        }
        // validate the required field `promotionSavings`
        PromotionSavings.validateJsonElement(jsonObj.get("promotionSavings"));
        // validate the optional field `purchaseRequirements`
        if (jsonObj.get("purchaseRequirements") != null
                && !jsonObj.get("purchaseRequirements").isJsonNull()) {
            PurchaseRequirements.validateJsonElement(jsonObj.get("purchaseRequirements"));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!Promotion.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'Promotion' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Promotion> thisAdapter = gson.getDelegateAdapter(this, TypeToken.get(Promotion.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<Promotion>() {
                        @Override
                        public void write(JsonWriter out, Promotion value) throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public Promotion read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of Promotion given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of Promotion
     * @throws IOException if the JSON string is invalid with respect to Promotion
     */
    public static Promotion fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, Promotion.class);
    }

    /**
     * Convert an instance of Promotion to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
