/**
 * Selling Partner API for Retail Procurement Shipments
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The TransportationLabels model module.
 * @module vendorshipments_v1/model/TransportationLabels
 * @version v1
 */
export declare class TransportationLabels {
    /**
     * Constructs a new <code>TransportationLabels</code>.
     * The request schema for the GetShipmentLabels operation.
     * @alias module:vendorshipments_v1/model/TransportationLabels
     * @class
     */
    constructor();
    /**
     * Constructs a <code>TransportationLabels</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {TransportationLabels} obj Optional instance to populate.
     * @return {TransportationLabels} The populated <code>TransportationLabels</code> instance.
     */
    static constructFromObject(data: Object, obj: TransportationLabels): TransportationLabels;
}
//# sourceMappingURL=TransportationLabels.d.ts.map