/**
 * Selling Partner API for Direct Fulfillment Inventory Updates
 * The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The SubmitInventoryUpdateResponse model module.
 * @module vendordfinventory_v1/model/SubmitInventoryUpdateResponse
 * @version v1
 */
export declare class SubmitInventoryUpdateResponse {
    /**
     * Constructs a new <code>SubmitInventoryUpdateResponse</code>.
     * The response schema for the submitInventoryUpdate operation.
     * @alias module:vendordfinventory_v1/model/SubmitInventoryUpdateResponse
     * @class
     */
    constructor();
    /**
     * Constructs a <code>SubmitInventoryUpdateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {SubmitInventoryUpdateResponse} obj Optional instance to populate.
     * @return {SubmitInventoryUpdateResponse} The populated <code>SubmitInventoryUpdateResponse</code> instance.
     */
    static constructFromObject(data: Object, obj: SubmitInventoryUpdateResponse): SubmitInventoryUpdateResponse;
}
//# sourceMappingURL=SubmitInventoryUpdateResponse.d.ts.map