export type TransactionStatus = "EXPIRED" | "FAILED" | "FAILED_CREDITS_APPLIED" | "IN_PROGRESS" | "PENDING_USER_APPROVAL" | "SUCCESSFUL";
/**
 * @typedef {'EXPIRED'|'FAILED'|'FAILED_CREDITS_APPLIED'|'IN_PROGRESS'|'PENDING_USER_APPROVAL'|'SUCCESSFUL'} TransactionStatus
 */
export const TransactionStatus: Readonly<{
    EXPIRED: "EXPIRED";
    FAILED: "FAILED";
    FAILED_CREDITS_APPLIED: "FAILED_CREDITS_APPLIED";
    IN_PROGRESS: "IN_PROGRESS";
    PENDING_USER_APPROVAL: "PENDING_USER_APPROVAL";
    SUCCESSFUL: "SUCCESSFUL";
}>;
//# sourceMappingURL=TransactionStatus.d.ts.map