/**
 * Selling Partner API for FBA Inventory
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * The AddInventoryRequest model module.
 * @module fbainventory_v1/model/AddInventoryRequest
 * @version v1
 */
export declare class AddInventoryRequest {
    /**
     * Constructs a new <code>AddInventoryRequest</code>.
     * The object with the list of Inventory to be added
     * @alias module:fbainventory_v1/model/AddInventoryRequest
     * @class
     */
    constructor();
    /**
     * Constructs a <code>AddInventoryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {AddInventoryRequest} obj Optional instance to populate.
     * @return {AddInventoryRequest} The populated <code>AddInventoryRequest</code> instance.
     */
    static constructFromObject(data: Object, obj: AddInventoryRequest): AddInventoryRequest;
}
//# sourceMappingURL=AddInventoryRequest.d.ts.map