name: Build Java SDK

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: selling-partner-api-sdk
    - uses: actions/checkout@v4
      with:
        repository: amzn/selling-partner-api-models
        path: selling-partner-api-models
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Download swagger codegen
      working-directory: ./selling-partner-api-sdk/java
      run: curl -O https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.63/swagger-codegen-cli-3.0.63.jar
    - name: Remove old sdk files
      working-directory: ./selling-partner-api-sdk/java/sdk
      run: rm -r *
    - name: Execute swagger codegen
      working-directory: ./selling-partner-api-sdk/java
      run: |
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/amazon-warehousing-and-distribution-model/awd_2024-05-09.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/aplus-content-api-model/aplusContent_2020-11-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/application-integrations-api-model/appIntegrations-2024-04-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/application-management-api-model/application_2023-11-30.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/catalog-items-api-model/catalogItems_2022-04-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/data-kiosk-api-model/dataKiosk_2023-11-15.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/easy-ship-model/easyShip_2022-03-23.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/fba-inbound-eligibility-api-model/fbaInbound.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/fba-inventory-api-model/fbaInventory.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/feeds-api-model/feeds_2021-06-30.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/finances-api-model/financesV0.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/finances-api-model/finances_2024-06-19.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/fulfillment-inbound-api-model/fulfillmentInboundV0.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/fulfillment-inbound-api-model/fulfillmentInbound_2024-03-20.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/fulfillment-outbound-api-model/fulfillmentOutbound_2020-07-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/invoices-api-model/InvoicesApiModel_2024-06-19.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/listings-items-api-model/listingsItems_2021-08-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/listings-restrictions-api-model/listingsRestrictions_2021-08-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/merchant-fulfillment-api-model/merchantFulfillmentV0.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/messaging-api-model/messaging.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/notifications-api-model/notifications.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/orders-api-model/ordersV0.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/product-fees-api-model/productFeesV0.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/product-pricing-api-model/productPricingV0.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/product-pricing-api-model/productPricing_2022-05-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/product-type-definitions-api-model/definitionsProductTypes_2020-09-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/replenishment-api-model/replenishment-2022-11-07.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/reports-api-model/reports_2021-06-30.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/sales-api-model/sales.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/sellers-api-model/sellers.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/services-api-model/services.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/shipment-invoicing-api-model/shipmentInvoicingV0.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/shipping-api-model/shippingV2.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/solicitations-api-model/solicitations.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/supply-sources-api-model/supplySources_2020-07-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/tokens-api-model/tokens_2021-03-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/uploads-api-model/uploads_2020-11-01.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/vendor-direct-fulfillment-inventory-api-model/vendorDirectFulfillmentInventoryV1.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/vendor-direct-fulfillment-orders-api-model/vendorDirectFulfillmentOrders_2021-12-28.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/vendor-direct-fulfillment-payments-api-model/vendorDirectFulfillmentPaymentsV1.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/vendor-direct-fulfillment-shipping-api-model/vendorDirectFulfillmentShipping_2021-12-28.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/vendor-direct-fulfillment-transactions-api-model/vendorDirectFulfillmentTransactions_2021-12-28.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/vendor-invoices-api-model/vendorInvoices.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/vendor-orders-api-model/vendorOrders.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/vendor-shipments-api-model/vendorShipments.json -l java -t config/templates -o sdk -c config/config.json && \
        java -jar swagger-codegen-cli-3.0.63.jar generate -i ../../selling-partner-api-models/models/vendor-transaction-status-api-model/vendorTransactionStatus.json -l java -t config/templates -o sdk -c config/config.json
    - name: Copy Auth&Auth lib
      working-directory: ./selling-partner-api-sdk/java
      run: cp -R tmp/com sdk/src/main/java
    - name: Make gradlew executable
      working-directory: ./selling-partner-api-sdk/java/sdk
      run: chmod +x ./gradlew
    - name: Build SDK jar with Gradle
      working-directory: ./selling-partner-api-sdk/java/sdk
      run: ./gradlew fatJar
    - name: Create PR
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update Java SDK
        title: 'Update Java SDK'
        body: |
          Update Java SDK with latest changes from upstream.
        branch: feature/update-java-sdk
        assignees: mafge
        reviewers: mafge
        path: ./selling-partner-api-sdk
