name: Build Java SDK

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ trigger-build ]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: selling-partner-api-sdk
      - uses: actions/checkout@v4
        with:
          repository: amzn/selling-partner-api-models
          path: selling-partner-api-models
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install OpenAPI Generator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Remove old sdk files
        run: |
          rm -r ./selling-partner-api-sdk/java/sdk/src/main/java/software/amazon/spapi/*
          rm -r ./selling-partner-api-sdk/java/sdk/src/test/java/software/amazon/spapi/*
      - name: Execute OpenAPI Generator
        working-directory: ./selling-partner-api-sdk/java
        run: bash ../scripts/generate-sdk.sh java
      - name: Copy rate limit configuration
        working-directory: ./selling-partner-api-sdk
        run: cp -R resources java/sdk/src/main
      - name: Make gradlew executable
        working-directory: ./selling-partner-api-sdk/java/sdk
        run: chmod +x ./gradlew
      - name: Run linter
        working-directory: ./selling-partner-api-sdk/java/sdk
        run: ./gradlew spotlessApply
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Java SDK
          title: 'Update Java SDK'
          body: |
            Update Java SDK with latest changes from upstream.
          branch: feature/update-java-sdk
          path: ./selling-partner-api-sdk
          token: ${{ secrets.MAFGE_PAT }}
