name: Build PHP SDK

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: selling-partner-api-sdk
      - uses: actions/checkout@v4
        with:
          repository: leonardonakagawa/selling-partner-api-models
          path: selling-partner-api-models
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, curl, json, openssl
          tools: composer:v2
          coverage: none
      - name: Download openapi codegen
        working-directory: ./selling-partner-api-sdk/php
        run: curl -O https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.9.0/openapi-generator-cli-7.9.0.jar
      - name: Remove old sdk files
        working-directory: ./selling-partner-api-sdk/php/sdk
        run: rm -r *
      - name: Remove old config files
        working-directory: ./selling-partner-api-sdk/php/config
        run: rm -r *
      - name: Copy new config files
        run: cp -R selling-partner-api-models/clients/sellingpartner-api-aa-php/resources/openapi-generator selling-partner-api-sdk/php/config
      - name: Copy Auth&Auth lib
        run: cp -R selling-partner-api-models/clients/sellingpartner-api-aa-php/src selling-partner-api-sdk/php/sdk/src
      - name: Copy Composer dependencies
        run: cp -R selling-partner-api-models/clients/sellingpartner-api-aa-php/composer.json selling-partner-api-sdk/php
      - name: Execute openapi codegen
        working-directory: ./selling-partner-api-sdk/php
        run: |
          java -jar openapi-generator-cli-7.9.0.jar generate -i ../../selling-partner-api-models/models/sellers-api-model/sellers.json -g php -t config/templates -o sdk -c config/config.json --additional-properties=composerVendorName=amazon,composerPackageName=selling-partner-api-aa-php,modelPackage=Model\\sellers && \
          java -jar openapi-generator-cli-7.9.0.jar generate -i ../../selling-partner-api-models/models/orders-api-model/ordersV0.json -g php -t config/templates -o sdk  -c config/config.json --additional-properties=composerVendorName=amazon,composerPackageName=selling-partner-api-aa-php,modelPackage=Model\\orders
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update PHP SDK
          title: 'Update PHP SDK'
          body: |
            Update PHP SDK with latest changes from upstream.
          branch: feature/update-php-sdk
          assignees: nakagleo
          reviewers: nakagleo
          path: ./selling-partner-api-sdk
