name: Build Java SDK

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: selling-partner-api-sdk
    - uses: actions/checkout@v4
      with:
        repository: amzn/selling-partner-api-models
        path: selling-partner-api-models
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: maven
    - name: Build Auth&Auth jar with Maven
      working-directory: ./selling-partner-api-models/clients/sellingpartner-api-aa-java
      run: mvn package
    - name: Add Auth&Auth lib to local maven repo
      working-directory: ./selling-partner-api-models/clients/sellingpartner-api-aa-java
      run: mvn install:install-file -Dfile=target/sellingpartnerapi-aa-java-2.0-jar-with-dependencies.jar -DgroupId=com.amazon.sellingpartnerapi -DartifactId=sellingpartnerapi-aa-java -Dversion=2.0 -Dpackaging=jar
    - name: Download swagger codegen
      run: curl -O https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.63/swagger-codegen-cli-3.0.63.jar
    - name: Execute swagger codegen
      run: java -jar swagger-codegen-cli-3.0.63.jar generate -i selling-partner-api-sdk/selling-partner-api.json -l java -t selling-partner-api-models/clients/sellingpartner-api-aa-java/resources/swagger-codegen/templates -o tmp/sdk -c selling-partner-api-models/clients/sellingpartner-api-aa-java/resources/java/config.json
    - name: Add Auth&Auth lib to pom.xml
      working-directory: ./tmp/sdk
      run: sed -i '/<dependencies>/a\<dependency><groupId>com.amazon.sellingpartnerapi</groupId><artifactId>sellingpartnerapi-aa-java</artifactId><version>2.0</version></dependency>' pom.xml
    - name: Add Maven assembly plugin to pom.xml
      working-directory: ./tmp/sdk
      run: sed -i '/<plugins>/a\<plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-assembly-plugin</artifactId><version>3.1.1</version><executions><execution><id>build-assembly</id><phase>package</phase><goals><goal>single</goal></goals></execution></executions><configuration><descriptorRefs><descriptorRef>jar-with-dependencies</descriptorRef></descriptorRefs></configuration></plugin>' pom.xml
    - name: Build SDK jar with Maven
      working-directory: ./tmp/sdk
      run: mvn package
    - uses: actions/upload-artifact@v4
      name: Upload Java SDK jar
      with:
        name: java-sdk
        path: tmp/sdk/target/swagger-java-client-2.0-jar-with-dependencies.jar
