name: Build Csharp SDK

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: selling-partner-api-sdk
      - uses: actions/checkout@v4
        with:
          repository: amzn/selling-partner-api-models
          path: selling-partner-api-models
      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install OpenAPI Generator
        run: npm install @openapitools/openapi-generator-cli -g && openapi-generator-cli version-manager set 7.9.0
      - name: Remove old sdk files
        working-directory: ./selling-partner-api-sdk/csharp/sdk
        run: rm -r *
      - name: Execute openapi codegen
        working-directory: ./selling-partner-api-sdk/csharp
        run: bash ../scripts/generate-sdk.sh csharp
      - name: Print workspace path
        run: echo "$GITHUB_WORKSPACE"
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
      - name: Copy auth lib files to sdk directory
        working-directory: ./selling-partner-api-sdk/csharp/sdk/src/software.amzn.spapi/
        run: |
            mkdir Authlib
            cp ../../../authlib/* ./Authlib/
      - name: Restore dependencies
        working-directory: ./selling-partner-api-sdk/csharp/sdk/src/software.amzn.spapi/
        run: dotnet restore
      - name: Build SDK and generate artifact
        working-directory: ./selling-partner-api-sdk/csharp/sdk/src/software.amzn.spapi/
        run: |
            dotnet build --configuration Release --no-restore
      - name: copy README here
        working-directory: ./selling-partner-api-sdk/csharp/sdk/src/software.amzn.spapi/
        run: cp ../../../README.md .
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Csharp SDK
          title: 'Update Csharp SDK'
          body: |
            Update Csharp SDK with latest changes from upstream.
          branch: feature/update-csharp-sdk
          delete-branch: true  # Overwrite if branch exists
          path: ./selling-partner-api-sdk
          token: ${{ secrets.MAFGE_PAT}}
