name: Build PHP SDK

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: selling-partner-api-sdk
      - uses: actions/checkout@v4
        with:
          repository: amzn/selling-partner-api-models
          path: selling-partner-api-models
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, json, openssl
          tools: composer:v2
          coverage: none
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install OpenAPI Generator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Remove old sdk files
        working-directory: ./selling-partner-api-sdk/php
        run: |
          find sdk -mindepth 1 -maxdepth 1 \
              ! -name 'src' \
              ! -name '.*' \
              ! -name 'phpunit.xml' \
              -exec rm -rf {} +
      - name: Execute openapi codegen
        working-directory: ./selling-partner-api-sdk/php
        run: bash ../scripts/generate-sdk.sh php
      - name: Copy README
        run: cp ./selling-partner-api-sdk/php/README.md ./selling-partner-api-sdk/php/sdk/README.md
      # This operation should be removed when vendorDirectFulfillmentOrders_2021-12-28.json is fixed
      - name: Fix PHP vendorDirectFulfillmentOrders bool default value
        working-directory: ./selling-partner-api-sdk/php/sdk
        run: |
          sed -i "s/?bool \$include_details = 'true'/?bool \$include_details = true/g" lib/Api/vendor/df/orders/v2021_12_28/VendorOrdersApi.php
      - name: Copy rate limit configuration
        working-directory: ./selling-partner-api-sdk
        run: cp -R resources php/sdk
      - name: Run composer install
        working-directory: ./selling-partner-api-sdk/php/sdk
        run: composer install
      - name: Run linter
        working-directory: ./selling-partner-api-sdk/php/sdk
        run: PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer fix
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update PHP SDK
          title: 'Update PHP SDK'
          body: |
            Update PHP SDK with latest changes from upstream.
          branch: feature/update-php-sdk
          path: ./selling-partner-api-sdk
          token: ${{ secrets.MAFGE_PAT }}
