name: Build Python SDK

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ trigger-build ]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: selling-partner-api-sdk
      - uses: actions/checkout@v4
        with:
          repository: amzn/selling-partner-api-models
          path: selling-partner-api-models
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - uses: actions/setup-node@v4  # needed for openapi-generator-cli
        with:
          node-version: '20'
      - name: Pre-process OpenAPI schemas with duplicate/missings tags or other issues
        run: bash ./selling-partner-api-sdk/python/dev-toolkit/scripts/schema-fixer.sh
      - name: Install OpenAPI Generator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Remove old sdk files
        working-directory: ./selling-partner-api-sdk/python/sdk
        run: rm -r *
      - name: Copy Auth&Auth and other SDK required files # make sure to update if packages change in the generation below
        working-directory: ./selling-partner-api-sdk/python
        run: |
          mkdir -p sdk/spapi/auth
          cp -R dev-toolkit/auth/** sdk/spapi/auth
          cp dev-toolkit/client.py sdk/spapi/
          cp dev-toolkit/.openapi-generator-ignore sdk/spapi/
      - name: Execute openapi codegen
        working-directory: ./selling-partner-api-sdk/python
        run: bash ../scripts/generate-sdk.sh python
      - name: Create SDK python package __init__.py file
        working-directory: ./selling-partner-api-sdk/python
        run: python3 dev-toolkit/scripts/script_create_init.py
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update Python SDK
          title: 'Update Python SDK'
          body: |
            Update Python SDK with latest changes from upstream.
          branch: feature/python-sdk-update
          path: ./selling-partner-api-sdk
          token: ${{ secrets.MAFGE_PAT }}
