name: Build JavaScript SDK

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: selling-partner-api-sdk
      - uses: actions/checkout@v4
        with:
          repository: amzn/selling-partner-api-models
          path: selling-partner-api-models
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install openapi generator
        run: npm install -g @openapitools/openapi-generator-cli
      - name: Remove old sdk files
        working-directory: ./selling-partner-api-sdk/javascript
        run: |
          echo "Remove all files under sdk except .openapi-generator-ignore, sample-node-app, package.json, helper and readme"
          find sdk -mindepth 1 -maxdepth 1 \
              ! -name '.openapi-generator-ignore' \
              ! -name 'sample-node-app' \
              ! -name 'package.json' \
              ! -name 'package-lock.json' \
              ! -name 'README.md' \
              ! -name 'helper' \
              ! -name 'tsconfig.json' \
              -exec rm -rf {} +
      - name: Create DefaultRateLimitMap.mjs file
        working-directory: ./selling-partner-api-sdk/javascript
        run: |
          chmod +x scripts/create-rate-limit-map.sh
          ./scripts/create-rate-limit-map.sh
      - name: Execute OpenAPI generator
        working-directory: ./selling-partner-api-sdk/javascript
        run: bash ../scripts/generate-sdk.sh javascript
      - name: Generate consolidated index.js file
        working-directory: ./selling-partner-api-sdk/javascript
        run: |
          chmod +x scripts/generate-consolidated-index.sh
          ./scripts/generate-consolidated-index.sh
      - name: Run linter
        working-directory: ./selling-partner-api-sdk/javascript/sdk
        continue-on-error: true
        run: npm install standard --global && standard "src/**/*.js" --fix
      - name: Create TypeScript type files
        working-directory: ./selling-partner-api-sdk/javascript/sdk
        run:  npm install typescript --global && npx tsc
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update JavaScript SDK
          title: 'Update JavaScript SDK'
          body: |
            Update JavaScript SDK with latest changes from upstream.
          branch: feature/update-javascript-sdk
          path: ./selling-partner-api-sdk
          token: ${{ secrets.MAFGE_PAT }}
