name: Create Java Release

on:
  workflow_dispatch:
    inputs:
      newVersionNumber:
        type: string
        description: New version number
        required: true
  workflow_call:
    inputs:
      newVersionNumber:
        type: string
        required: true

env:
  SDK_VERSION: ${{ github.event.inputs.newVersionNumber }}

jobs:
  release_java:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.JAVA_OSSRH_USER_NAME }}
      ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.JAVA_OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.JAVA_SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.JAVA_SIGNING_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish Java SDK to Maven Central
        working-directory: java/sdk
        run: ./gradlew publish

  tag_and_release:
    needs: [ release_java ]
    uses: ./.github/workflows/create-tag-release.yml
    with:
      tagName: "java-${{ github.event.inputs.newVersionNumber }}"