name: Deploy PackageA to Separate Repo

on:
  push:
    paths:
      - "php/sdk/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy php/sdk to Temporary Directory
        run: |
          mkdir sdk
          cp -r php/sdk/* sdk/
          cd sdk

      - name: Push sdk to Separate Repository
        run: |
          git init
          git remote add origin https://github.com/amzn/selling-partner-api-php-release.git
          git add .
          git commit -m "Deploy PHP SDK"
          git push origin main --force