name: Auto Deploy PHP SDK

on:
  push:
    paths:
      - "php/sdk/**"
    branches:
      - main
  workflow_dispatch:
    inputs:
      newVersionNumber:
        type: string
        description: New version number
        required: true

env:
  SDK_VERSION: ${{ github.event.inputs.newVersionNumber }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create a new branch for changes
        run: |
          BRANCH_NAME="deploy-sdk-${{ env.SDK_VERSION }}-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME
          
          # Add all changes (even if no changes are made)
          git add -A
          git commit -m "Automated Deploy PHP SDK - Version ${{ env.SDK_VERSION }}" || echo "No changes to commit"
          
          # Push to origin
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.MAFGE_PAT }}

      - name: Add Remote for Target Repository
        run: |
          git remote add release-repo https://github.com/amzn/selling-partner-api-php-release.git
        env:
          GITHUB_TOKEN: ${{ secrets.MAFGE_PAT }}

      - name: Push to Target Repository
        run: |
          git push release-repo $BRANCH_NAME --force
        env:
          GITHUB_TOKEN: ${{ secrets.MAFGE_PAT }}

      - name: Create a Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MAFGE_PAT }}
          branch: $BRANCH_NAME
          base: main
          title: "Automated PR: Deploy PHP SDK - Version ${{ github.event.inputs.newVersionNumber }}"
          body: |
            This PR is automatically created by GitHub Actions.
            - Changes: `php/sdk/`
            - Version: ${{ github.event.inputs.newVersionNumber }}
            - Tag: `sdk-release-${{ github.event.inputs.newVersionNumber }}`
          labels: automated, sdk-update

      - name: Auto-Merge the PR
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.MAFGE_PAT }}
        with:
          mergeMethod: "squash"
          base: "main"
