name: Merge swagger files into one single file

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./selling-partner-api-sdk/openapi-merge

    steps:
    - uses: actions/checkout@v4
      with:
        path: selling-partner-api-sdk
    - uses: actions/checkout@v4
      with:
        repository: amzn/selling-partner-api-models
        path: selling-partner-api-models
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: selling-partner-api-sdk/openapi-merge/package-lock.json
    - run: npm ci
    - run: npx openapi-merge-cli
    - name: Create PR
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update selling-partner-api.json
        branch: feature/update-unified-swagger-file
        assignees: mafge
        reviewers: mafge
