name: Test PHP SDK

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-php:
    name: test php sdk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: json, curl, simplexml, spl, pcre
          coverage: xdebug

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Validate composer.json and composer.lock
        working-directory: ./php/sdk
        run: composer validate --strict

      - name: Install dependencies
        working-directory: ./php/sdk
        run: composer install --prefer-dist --no-progress

      - name: Install backend mock dependencies
        working-directory: ./test
        run: npm install

      - name: Start backend mock
        working-directory: ./test
        run: node src/index.js &

      - name: Run tests
        working-directory: ./php/sdk
        run: |
          mkdir -p build/reports
          vendor/bin/phpunit --testdox

      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: php-test-reports
          path: php/sdk/build/reports
