name: Test Python SDK

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: test python sdk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        working-directory: ./python/sdk
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run pytest
        working-directory: ./python/sdk
        run: pytest test --html=report/index.html --self-contained-html
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: ./python/sdk/report
