/**
 * Selling Partner API for Orders
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellingPartnerApiForOrders);
  }
}(this, function(expect, SellingPartnerApiForOrders) {
  'use strict';

  var instance;

  beforeEach(function() {
    try{
     instance = new SellingPartnerApiForOrders.Address();
    } catch (e) {
     //Handle the cases when this model extends another model by using Model.call(this);
     instance = Object.create(SellingPartnerApiForOrders.Address.prototype);
    }
  });

  afterEach(function() {
    instance = null;
  })

  describe('Address', function() {
    it('should create an instance of Address', function() {
      expect(instance).to.be.a(SellingPartnerApiForOrders.Address);
    });

    it('should have the property name (base name: "Name")', function() {
      // verify property exists
      expect(instance).to.have.property('name');

      // set and verify value
      var validValue = generateMockData('String');
      instance.name = validValue;
      expect(instance.name).to.equal(validValue);
    });

    it('should have the property companyName (base name: "CompanyName")', function() {
      // verify property exists
      expect(instance).to.have.property('companyName');

      // set and verify value
      var validValue = generateMockData('String');
      instance.companyName = validValue;
      expect(instance.companyName).to.equal(validValue);
    });

    it('should have the property addressLine1 (base name: "AddressLine1")', function() {
      // verify property exists
      expect(instance).to.have.property('addressLine1');

      // set and verify value
      var validValue = generateMockData('String');
      instance.addressLine1 = validValue;
      expect(instance.addressLine1).to.equal(validValue);
    });

    it('should have the property addressLine2 (base name: "AddressLine2")', function() {
      // verify property exists
      expect(instance).to.have.property('addressLine2');

      // set and verify value
      var validValue = generateMockData('String');
      instance.addressLine2 = validValue;
      expect(instance.addressLine2).to.equal(validValue);
    });

    it('should have the property addressLine3 (base name: "AddressLine3")', function() {
      // verify property exists
      expect(instance).to.have.property('addressLine3');

      // set and verify value
      var validValue = generateMockData('String');
      instance.addressLine3 = validValue;
      expect(instance.addressLine3).to.equal(validValue);
    });

    it('should have the property city (base name: "City")', function() {
      // verify property exists
      expect(instance).to.have.property('city');

      // set and verify value
      var validValue = generateMockData('String');
      instance.city = validValue;
      expect(instance.city).to.equal(validValue);
    });

    it('should have the property county (base name: "County")', function() {
      // verify property exists
      expect(instance).to.have.property('county');

      // set and verify value
      var validValue = generateMockData('String');
      instance.county = validValue;
      expect(instance.county).to.equal(validValue);
    });

    it('should have the property district (base name: "District")', function() {
      // verify property exists
      expect(instance).to.have.property('district');

      // set and verify value
      var validValue = generateMockData('String');
      instance.district = validValue;
      expect(instance.district).to.equal(validValue);
    });

    it('should have the property stateOrRegion (base name: "StateOrRegion")', function() {
      // verify property exists
      expect(instance).to.have.property('stateOrRegion');

      // set and verify value
      var validValue = generateMockData('String');
      instance.stateOrRegion = validValue;
      expect(instance.stateOrRegion).to.equal(validValue);
    });

    it('should have the property municipality (base name: "Municipality")', function() {
      // verify property exists
      expect(instance).to.have.property('municipality');

      // set and verify value
      var validValue = generateMockData('String');
      instance.municipality = validValue;
      expect(instance.municipality).to.equal(validValue);
    });

    it('should have the property postalCode (base name: "PostalCode")', function() {
      // verify property exists
      expect(instance).to.have.property('postalCode');

      // set and verify value
      var validValue = generateMockData('String');
      instance.postalCode = validValue;
      expect(instance.postalCode).to.equal(validValue);
    });

    it('should have the property countryCode (base name: "CountryCode")', function() {
      // verify property exists
      expect(instance).to.have.property('countryCode');

      // set and verify value
      var validValue = generateMockData('String');
      instance.countryCode = validValue;
      expect(instance.countryCode).to.equal(validValue);
    });

    it('should have the property phone (base name: "Phone")', function() {
      // verify property exists
      expect(instance).to.have.property('phone');

      // set and verify value
      var validValue = generateMockData('String');
      instance.phone = validValue;
      expect(instance.phone).to.equal(validValue);
    });

    it('should have the property extendedFields (base name: "ExtendedFields")', function() {
      // verify property exists
      expect(instance).to.have.property('extendedFields');

      // set and verify value
      var validValue = generateMockData('AddressExtendedFields');
      instance.extendedFields = validValue;
      expect(instance.extendedFields).to.equal(validValue);
    });

    it('should have the property addressType (base name: "AddressType")', function() {
      // verify property exists
      expect(instance).to.have.property('addressType');

      // set and verify value
      var validValue = ['Residential', 'Commercial', ][0];
      instance.addressType = validValue;
      expect(instance.addressType).to.equal(validValue);
    });

  });

  // Helper function to generate random test data
  function generateMockData(dataType, isArray = false) {
    if (!dataType) return {};

    // Handle array types
    if (isArray) {
      return [generateMockData(dataType), generateMockData(dataType)];
    }

    switch(dataType) {
      case 'String':
        return 'mock-' + Math.random().toString(36).substring(2, 10);
      case 'Number':
        return Math.floor(Math.random() * 1000);
      case 'Boolean':
        return Math.random() > 0.5;
      case 'Date':
        return new Date().toISOString();
      default:
        try {
          const ModelClass = SellingPartnerApiForOrders[dataType];
          if (ModelClass) {
            const instance = Object.create(ModelClass.prototype);
            return instance;
          }
        } catch (e) {
          console.error("Error creating instance of", dataType);
          return {};
        }
        return {};
    }
  }

}));
